module.exports = [
  { code: '/arte-obragaleria', name: 'Obra en galería', brandSafe: true,
    rubros: ['arte'],
    prompt: "Artwork displayed in a minimalist gallery: large canvas on a white wall, dramatic museum spotlight from above, 35mm elegant framing, quiet contemplative atmosphere, crisp neutral tones, prestigious exhibition presence, true collector presentation." },
  { code: '/arte-proceso', name: 'Artista pintando', brandSafe: true,
    rubros: ['arte'],
    prompt: "Artist painting in a sunlit studio: brush mid-stroke on a large canvas, paint-splattered apron, warm window light, 50mm intimate documentary framing, creative flow in action, vibrant authentic colors, inspiring behind-the-scenes artistry." },
  { code: '/arte-detallepincelada', name: 'Macro de pincelada', brandSafe: true,
    rubros: ['arte'],
    prompt: "Extreme macro of oil paint brushstrokes: thick impasto ridges catching raking side light, 100mm macro framing, rich textural detail, vivid pigment layers, tactile artistic depth, mesmerizing close-up, craft you can feel." },
  { code: '/arte-escultura', name: 'Escultura', brandSafe: true,
    rubros: ['arte'],
    prompt: "Marble sculpture in a gallery: classical figure dramatically lit from the side, deep shadows sculpting the form, 50mm reverent framing, timeless masterful craftsmanship, soft white stone glow, museum-quality artistic presence." },
  { code: '/arte-mural', name: 'Mural callejero', brandSafe: true,
    rubros: ['arte'],
    prompt: "Street artist painting a giant mural: colorful wall coming alive, artist on scaffolding at golden hour, 24mm bold wide framing, urban creative energy, vivid saturated colors, public art transforming the city, inspiring street culture." },
  { code: '/arte-ceramica', name: 'Cerámica en torno', brandSafe: true,
    rubros: ['arte'],
    prompt: "Potter shaping clay on a spinning wheel: hands guiding wet clay, studio window light, 50mm intimate framing, earthy creative focus, warm terracotta tones, ancient craft alive, meditative handmade artistry." },
  { code: '/arte-acuarela', name: 'Acuarela', brandSafe: true,
    rubros: ['arte'],
    prompt: "Watercolor painting in progress: delicate washes blooming on textured paper, soft natural daylight, 50mm close framing, gentle pigment gradients, dreamy translucent colors, serene artistic delicacy, poetic fluid beauty." },
  { code: '/arte-retratooleo', name: 'Retrato al óleo', brandSafe: true,
    rubros: ['arte'],
    prompt: "Oil portrait on an easel: richly painted face emerging from dark background, dramatic chiaroscuro lighting, 50mm classical framing, masterful brushwork detail, deep umbers and warm flesh tones, timeless fine-art portraiture." },
  { code: '/arte-abstracto', name: 'Obra abstracta', brandSafe: true,
    rubros: ['arte'],
    prompt: "Large abstract painting: bold gestural strokes in vivid color, gallery spotlight emphasizing texture, 35mm dynamic framing, emotional chromatic energy, striking contemporary composition, powerful modern expression, captivating visual rhythm." },
  { code: '/arte-taller', name: 'Taller del artista', brandSafe: true,
    rubros: ['arte'],
    prompt: "Artist studio interior: canvases stacked, brushes in jars, paint tubes scattered, warm afternoon window light, 24mm atmospheric wide framing, creative beautiful chaos, rich authentic colors, inspiring maker sanctuary." },
  { code: '/arte-marmol', name: 'Detalle en mármol', brandSafe: true,
    rubros: ['arte'],
    prompt: "Marble sculpture detail in a sunlit atrium: chiseled drapery catching soft daylight, 85mm refined framing, classical elegance, luminous white stone, masterful stone carving, timeless sculptural poetry." },
  { code: '/arte-fotografia', name: 'Serie fotográfica', brandSafe: true,
    rubros: ['arte'],
    prompt: "Fine-art photography series on a gallery wall: black-and-white prints in a row under spotlights, 35mm curatorial framing, quiet powerful storytelling, crisp monochrome tones, prestigious photographic exhibition, collector-worthy presentation." },
  { code: '/arte-digital', name: 'Arte digital', brandSafe: true,
    rubros: ['arte'],
    prompt: "Digital artist at a drawing tablet: stylus creating glowing artwork on screen, soft monitor light in a dim studio, 50mm modern framing, vibrant screen colors, cutting-edge creative process, futuristic artistic workflow." },
  { code: '/arte-grabado', name: 'Grabado', brandSafe: true,
    rubros: ['arte'],
    prompt: "Printmaker pulling an etching: inked plate pressed onto paper, hands in focused motion, warm studio lamplight, 50mm craft-detail framing, rich black ink textures, traditional printmaking artistry, timeless graphic craft." },
  { code: '/arte-mosaico', name: 'Mosaico', brandSafe: true,
    rubros: ['arte'],
    prompt: "Colorful mosaic artwork: thousands of tiny tiles forming a vivid image, raking light revealing texture, 50mm detailed framing, dazzling chromatic intricacy, ancient technique with modern vision, mesmerizing handcrafted detail." },
  { code: '/arte-vidrio', name: 'Vidrio soplado', brandSafe: true,
    rubros: ['arte'],
    prompt: "Glassblower shaping molten glass: glowing orange gather on the pipe, sparks in a dark workshop, 50mm dramatic framing, intense furnace light, mesmerizing fiery craft, translucent amber beauty, ancient artistry in motion." },
  { code: '/arte-joyeria', name: 'Joyería artesanal', brandSafe: true,
    rubros: ['arte', 'otro'],
    prompt: "Handcrafted jewelry on dark velvet: gold ring with gemstone under focused spotlight, 100mm macro framing, sparkling facets, luxurious intimate detail, rich warm metallics, exquisite artisanal luxury, wearable art masterpiece." },
  { code: '/arte-telar', name: 'Textil en telar', brandSafe: true,
    rubros: ['arte'],
    prompt: "Weaver at a wooden loom: colorful threads interlacing, hands working the shuttle, soft workshop window light, 50mm heritage framing, rhythmic textile craft, vibrant woven patterns, ancestral artistry alive." },
  { code: '/arte-instalacionluz', name: 'Instalación de luz', brandSafe: true,
    rubros: ['arte'],
    prompt: "Immersive light installation: visitors walking through glowing neon corridors, long-exposure light trails, 24mm wide framing, futuristic sensory wonder, electric vivid colors, unforgettable experiential art, mesmerizing luminous journey." },
  { code: '/arte-carbonilla', name: 'Dibujo al carboncillo', brandSafe: true,
    rubros: ['arte'],
    prompt: "Charcoal drawing in progress: artist hand smudging deep blacks on large paper, dramatic side light, 50mm intimate framing, raw expressive marks, rich monochrome depth, powerful figurative study, timeless drawing mastery." },
  { code: '/arte-bronce', name: 'Escultura en bronce', brandSafe: true,
    rubros: ['arte'],
    prompt: "Bronze sculpture in a garden: patinated figure gleaming in dappled sunlight, 50mm dignified framing, timeless metallic warmth, masterful casting detail, verdigris and gold tones, enduring monumental artistry." },
  { code: '/arte-botanico', name: 'Arte botánico', brandSafe: true,
    rubros: ['arte'],
    prompt: "Botanical watercolor illustration: exquisite flowers rendered in delicate detail, soft even daylight, 50mm scientific-art framing, precise natural beauty, fresh vibrant hues, elegant nature study, refined artistic botany." },
  { code: '/arte-caligrafia', name: 'Caligrafía', brandSafe: true,
    rubros: ['arte'],
    prompt: "Calligrapher writing with a broad nib: ink flowing into elegant letterforms, close-up under warm lamplight, 50mm macro framing, meditative precise strokes, deep black on cream paper, timeless lettering artistry." },
  { code: '/arte-collage', name: 'Collage', brandSafe: true,
    rubros: ['arte'],
    prompt: "Mixed-media collage artwork: layered paper, photos and paint on canvas, gallery spotlight, 50mm textured framing, playful visual storytelling, rich eclectic colors, contemporary creative assemblage, captivating layered narrative." },
  { code: '/arte-cinetico', name: 'Arte cinético', brandSafe: true,
    rubros: ['arte'],
    prompt: "Kinetic sculpture in motion: spinning metal elements blurring gracefully, museum spotlight with motion blur, 50mm dynamic framing, mesmerizing mechanical poetry, polished steel reflections, hypnotic moving art, engineering as beauty." },
  { code: '/arte-madera', name: 'Escultura en madera', brandSafe: true,
    rubros: ['arte'],
    prompt: "Wood sculptor carving: chisel biting into oak, curls of shavings flying, warm workshop light, 50mm craft-action framing, raw organic transformation, rich wood grain tones, primal creative force, masterful handwork." },
  { code: '/arte-bordado', name: 'Bordado artístico', brandSafe: true,
    rubros: ['arte'],
    prompt: "Embroidered textile art: intricate stitches forming a floral design, hoop held in hands, soft window light, 100mm macro framing, delicate thread textures, vibrant silky colors, meticulous needlework poetry, wearable fine craft." },
  { code: '/arte-muralinterior', name: 'Mural interior', brandSafe: true,
    rubros: ['arte'],
    prompt: "Interior mural in a restaurant: sweeping painted landscape across the dining wall, warm ambient lighting, 24mm wide framing, immersive artistic atmosphere, rich harmonious colors, signature space-defining artwork, memorable venue identity." },
  { code: '/arte-reciclado', name: 'Arte reciclado', brandSafe: true,
    rubros: ['arte'],
    prompt: "Sculpture made from recycled materials: imaginative forms from reclaimed metal and wood, bright studio light, 50mm inventive framing, eco-conscious creativity, surprising textures and colors, sustainable art with soul, powerful green statement." },
  { code: '/arte-acuarelamascota', name: 'Retrato de mascota en acuarela', brandSafe: true,
    rubros: ['arte'],
    prompt: "Custom watercolor pet portrait: beloved dog painted in loose expressive washes, soft daylight on the paper, 50mm heartwarming framing, personality shining through, gentle warm colors, cherished keepsake artwork, pure pet love." },
  { code: '/arte-vitral', name: 'Vitral', brandSafe: true,
    rubros: ['arte'],
    prompt: "Stained-glass window glowing: colored light streaming through intricate leaded panes, sun backlighting the glass, 35mm luminous framing, jewel-toned radiance, sacred kaleidoscope beauty, centuries-old luminous craft." },
  { code: '/arte-origami', name: 'Origami', brandSafe: true,
    rubros: ['arte'],
    prompt: "Origami installation: hundreds of paper cranes suspended mid-air, soft gallery lighting, 50mm delicate framing, floating paper poetry, clean whites with subtle shadows, meditative fragile beauty, mesmerizing paper art." },
  { code: '/arte-espejos', name: 'Instalación de espejos', brandSafe: true,
    rubros: ['arte'],
    prompt: "Mirror installation art: infinite reflections multiplying visitors, dramatic gallery spotlights, 24mm disorienting wide framing, mind-bending spatial illusion, brilliant silver light play, immersive reflective wonder, unforgettable perceptual art." },
  { code: '/arte-subasta', name: 'Obra en subasta', brandSafe: true,
    rubros: ['arte'],
    prompt: "Artwork at auction: painting on an easel under dramatic podium spotlight, paddle raised in blurred foreground, 50mm tense framing, high-stakes art market, rich dramatic lighting, prestigious coveted masterpiece, thrilling sale moment." },
  { code: '/arte-performance', name: 'Performance', brandSafe: true,
    rubros: ['arte'],
    prompt: "Live performance art: artist mid-gesture before an engaged audience, dramatic stage lighting, 35mm documentary framing, raw emotional intensity, bold theatrical colors, unforgettable ephemeral art, powerful human expression." },
  { code: '/arte-serigrafia', name: 'Serigrafía', brandSafe: true,
    rubros: ['arte'],
    prompt: "Screen printing in action: squeegee pulling vivid ink across the mesh, hands in rhythmic motion, bright studio light, 50mm craft framing, bold graphic colors, handmade printmaking energy, vibrant DIY artistry." },
  { code: '/arte-tatuaje', name: 'Arte de tatuaje', brandSafe: true,
    rubros: ['arte'],
    prompt: "Tattoo artwork close-up: fresh intricate blackwork on skin, artist gloved hands finishing detail, focused studio lighting, 100mm macro framing, precise linework, bold skin-canvas artistry, striking permanent masterpiece." },
  { code: '/arte-encuadre', name: 'Obra enmarcada', brandSafe: true,
    rubros: ['arte'],
    prompt: "Freshly framed artwork: elegant frame being fitted around a painting, craftsman hands, warm workshop light, 50mm detail framing, gallery-ready finish, rich wood and canvas tones, the final touch of presentation." },
  { code: '/arte-serie', name: 'Serie de obras', brandSafe: true,
    rubros: ['arte'],
    prompt: "Cohesive art series on a studio wall: five paintings in a row sharing a palette, even gallery lighting, 35mm curatorial framing, unified artistic vision, harmonious color story, collectible body of work, impressive creative range." },
  { code: '/arte-vernissage', name: 'Vernissage', brandSafe: true,
    rubros: ['arte'],
    prompt: "Gallery opening night: crowd admiring new artworks with wine glasses, warm festive lighting, 35mm lively framing, celebrated artistic debut, sophisticated social buzz, vibrant cultural evening, art finding its audience." },
];
