module.exports = [
  { code: '/auto-motordetalle', name: 'Motor en detalle', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Clean engine bay macro photography: polished pistons, chrome covers and braided hoses in sharp focus, bright overhead workshop fluorescents, shallow depth of field at f/2.8, symmetrical composition celebrating mechanical precision and care.' },
  { code: '/auto-fosaauto', name: 'Auto en fosa', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Low-angle photograph from inside a service pit: car undercarriage, exhaust and suspension looming overhead, mechanic legs at the edge, dramatic rim lighting from pit lamps, wide-angle lens emphasizing scale and professional inspection work.' },
  { code: '/auto-pulidofaro', name: 'Pulido de faro', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Split-composition headlight restoration photo: left side yellowed and oxidized, right side crystal clear after polishing, detailer gloved hand with polisher mid-motion, bright garage lighting, macro lens capturing the dramatic before-and-after transformation.' },
  { code: '/auto-llantadetalle', name: 'Llanta en detalle', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Close-up of an alloy wheel with red sport brake caliper behind the spokes, low afternoon sun raking across the rim, shallow depth of field, dynamic three-quarter angle, tire tread texture visible, performance and style in one frame.' },
  { code: '/auto-servicebox', name: 'Auto en elevador', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Full car lifted on a hydraulic two-post lift inside a clean workshop, mechanic working underneath with a wrench, bright even ceiling lights, wide symmetrical composition, floor reflections, conveying a serious and equipped service operation.' },
  { code: '/auto-ceramico', name: 'Sellado cerámico', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Detailer applying ceramic coating to a glossy black hood, applicator pad gliding over deep reflections, water beads forming on treated paint, soft diffused studio lighting, macro lens, luxurious liquid-glass finish as the hero.' },
  { code: '/auto-interiorcuero', name: 'Interior de cuero', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Luxurious car interior detail: stitched leather seats and dashboard in warm cognac tones, soft window light streaming through glass, 50mm lens with creamy bokeh, close crop on craftsmanship, comfort and premium care.' },
  { code: '/auto-cockpitnoche', name: 'Cockpit nocturno', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Driver cockpit at night: illuminated dashboard dials, ambient LED strips and touchscreen glowing, city lights blurred through the windshield, low-light photography with balanced exposure, cinematic wide composition, modern driving experience.' },
  { code: '/auto-escape', name: 'Escape deportivo', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Polished dual exhaust tips close-up with subtle heat shimmer, dark studio background, single hard rim light tracing chrome edges, macro lens, shallow focus, aggressive performance attitude without showing the whole car.' },
  { code: '/auto-polarizado', name: 'Polarizado de vidrios', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Technician applying window tint film to a car side glass, squeegee smoothing out water, bright workshop backlight making the film glow, side-angle composition, precision craft moment, clean professional installation scene.' },
  { code: '/auto-bateria', name: 'Cambio de batería', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Mechanic hands installing a new car battery, terminals and red-black cables in crisp focus, bright garage work light, overhead angle, shallow depth of field, trustworthy maintenance moment frozen mid-task.' },
  { code: '/auto-frenos', name: 'Service de frenos', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Brake disc and caliper macro: drilled rotor, fresh pads and hardware in sharp detail, cool white workshop lighting from the side, shallow focus, technical composition celebrating safety and stopping power.' },
  { code: '/auto-alineacion', name: 'Alineación 3D', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Car on an alignment rack with laser targets clamped to each wheel, glowing green laser lines in a dimmed workshop, wide-angle composition, high-tech precision atmosphere, modern equipment as the protagonist.' },
  { code: '/auto-diagnostico', name: 'Diagnóstico computarizado', brandSafe: true,
    rubros: ['autos'],
    prompt: 'OBD diagnostic scanner plugged into a car with live data on its screen, mechanic reviewing fault codes, cool blue workshop lighting, over-the-shoulder composition, technology-driven troubleshooting you can trust.' },
  { code: '/auto-aceite', name: 'Cambio de aceite', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Golden motor oil pouring in a smooth stream into the engine filler neck, mechanic steady hand, bright garage lighting with warm highlights, high-speed frozen motion, macro detail, the ritual of proper maintenance.' },
  { code: '/auto-lavado', name: 'Lavado premium', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Thick white foam cascading over a car hood from a foam cannon, detailer in the background, bright daylight with sparkling reflections, wide dynamic composition, satisfying deep-clean moment, premium car wash energy.' },
  { code: '/auto-interiorvapor', name: 'Limpieza interior', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Detailer steam-cleaning car upholstery, vapor rising from the nozzle over fabric seats, vacuum hose nearby, bright interior lighting, close action composition, the invisible work behind a spotless cabin.' },
  { code: '/auto-opticas', name: 'Ópticas restauradas', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Pair of restored crystal-clear headlights on a car front at dusk, sharp beams cutting through light haze, low three-quarter angle, dramatic twilight sky, transformation complete, like-new front end.' },
  { code: '/auto-cubiertas', name: 'Cubiertas nuevas', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Stack of brand-new tires with crisp tread patterns and stickers, warehouse window light raking across rubber, low-angle composition, shallow depth of field, the promise of grip and safe kilometers ahead.' },
  { code: '/auto-pintura', name: 'Chapa y pintura', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Car body inside a paint booth, painter spraying a fine mist of color with a spray gun, glowing booth lights and ventilation haze, cinematic wide shot, craftsmanship behind a flawless finish.' },
  { code: '/auto-sacabollos', name: 'Sacabollos sin pintar', brandSafe: true,
    rubros: ['autos'],
    prompt: 'PDR technician specialized rods and reflector board working a door panel dent, bright focused task lighting, macro composition on tools and metal, invisible repair magic, original paint untouched.' },
  { code: '/auto-parabrisas', name: 'Cambio de parabrisas', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Two technicians setting a new windshield into place with suction cups, bright workshop lighting, car interior visible through the opening, coordinated teamwork composition, precision glass installation.' },
  { code: '/auto-aireac', name: 'Aire acondicionado', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Macro shot of AC manifold gauges connected to a car, pressure needles sharp in focus, technician hand adjusting a valve, cool blue garage lighting, tight technical composition, the promise of cold air restored.' },
  { code: '/auto-bujias', name: 'Service de bujías', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Row of new spark plugs lined up on a clean workbench next to the old worn ones, bright task lighting, shallow depth of field, flat composition, small parts with a big job.' },
  { code: '/auto-distribucion', name: 'Distribución completa', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Timing belt kit laid out in order: belt, tensioners and water pump on a dark bench, dramatic side lighting, top-down technical composition, the heart surgery of preventive maintenance.' },
  { code: '/auto-embrague', name: 'Kit de embrague', brandSafe: true,
    rubros: ['autos'],
    prompt: 'New clutch kit components arranged on a workshop bench: disc, pressure plate and release bearing, strong overhead lighting, symmetrical flat composition, mechanical renewal ready to install.' },
  { code: '/auto-amortiguadores', name: 'Amortiguadores nuevos', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Pair of new shock absorbers standing on a garage floor next to the worn ones, bright even lighting, low-angle product composition, the difference between bouncing and gliding.' },
  { code: '/auto-refrigeracion', name: 'Sistema de refrigeración', brandSafe: true,
    rubros: ['autos'],
    prompt: 'New aluminum radiator with attached coolant hoses and green coolant visible in a funnel, bright workshop lighting, three-quarter product angle, shallow focus, engine temperature finally under control.' },
  { code: '/auto-turbo', name: 'Turbo', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Turbocharger macro: polished compressor wheel and housing catching a hard rim light on dark background, shallow depth of field, dramatic low-key lighting, pure forced-induction desire.' },
  { code: '/auto-inyeccion', name: 'Limpieza de inyectores', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Fuel injectors mounted on an ultrasonic cleaning bench with graduated test tubes, blue backlight glowing through the machine, macro technical composition, precision fuel spray restored again.' },
  { code: '/auto-electrico', name: 'Carga eléctrica', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Electric car charging at night, cable plugged in with glowing charge port, city lights bokeh behind, cool blue ambient lighting, cinematic wide composition, silent electric future arriving.' },
  { code: '/auto-hibrido', name: 'Tecnología híbrida', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Hybrid engine bay with bright orange high-voltage cables and the hybrid badge sharp in focus, clean bright workshop lighting, macro detail composition, efficient technology working quietly under the hood.' },
  { code: '/auto-4x4', name: 'Aventura 4x4', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Pickup truck splashing through a muddy off-road trail, water and mud frozen mid-air, golden hour backlight, dynamic low-angle action shot, adventure-ready machine earning its scars.' },
  { code: '/auto-clasico', name: 'Clásico restaurado', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Vintage classic car in a restoration shop, half-polished chrome bumper catching warm tungsten light, tools and parts around, nostalgic wide composition, automotive heritage brought back to life.' },
  { code: '/auto-moto', name: 'Service de moto', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Motorcycle raised on a workshop stand while a mechanic adjusts the drive chain, bright even garage lighting, low dynamic angle, shallow depth of field, two-wheeled freedom receiving professional care.' },
  { code: '/auto-gnc', name: 'Equipo de GNC', brandSafe: true,
    rubros: ['autos'],
    prompt: 'GNC cylinder mounted in a car trunk with copper lines and valves neatly routed and secured, bright workshop lighting, clean technical composition, economical fuel conversion executed with professional care.' },
  { code: '/auto-llaves', name: 'Llaves codificadas', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Car key fob being programmed beside a diagnostic tablet glowing on the workbench, new key shell sharp in focus, warm desk lamp lighting, macro composition, modern automotive locksmith precision.' },
  { code: '/auto-inspeccion', name: 'Inspección pre-compra', brandSafe: true,
    rubros: ['autos'],
    prompt: 'Inspector with clipboard and flashlight examining a used car engine in a bright outdoor lot, open hood and detailed checklist visible, strong daylight with crisp shadows, documentary composition, buying with total confidence.' },
  { code: '/auto-auxilio', name: 'Auxilio mecánico', brandSafe: true,
    rubros: ['autos', 'servicios'],
    prompt: 'Tow truck with flashing amber beacons loading a car at night on a highway, light trails from passing traffic, dramatic low-light wide shot, help arriving when it matters most.' },
  { code: '/auto-showroom', name: 'Showroom', brandSafe: true,
    rubros: ['autos'],
    prompt: 'New car gleaming under dealership spotlights on a polished reflective floor, dramatic overhead light cones, symmetrical wide composition, the dream car moment before the first drive.' },
];
