module.exports = [
  { code: '/bar-tragofuego', name: 'Cóctel flameado', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Flaming cocktail photography: coupe glass with blue flames dancing on the surface, dark bar background with warm bokeh, bartender hand holding a lighter, dramatic low light, frozen motion on the fire.' },
  { code: '/bar-cervezatirada', name: 'Pinta tirada', brandSafe: true,
    rubros: ['bar', 'gastronomia'],
    prompt: 'Fresh-poured pint photography: tall glass of amber lager with foam overflowing down the sides, beer tap blurred behind, condensation droplets on the glass, warm pub backlight, extreme refreshment mood.' },
  { code: '/bar-barranoche', name: 'Barra de noche', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Night bar photography: long illuminated bar counter with glowing bottles lined up, warm pendant lights, golden bokeh reflections on polished wood, empty stools inviting, cinematic wide angle.' },
  { code: '/bar-fernet', name: 'Fernet con coca', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Fernet con coca photography: tall glass with dark fernet, cola foam crown and big ice cubes, lime wedge on the rim, condensation drops, Argentine bar table, warm casual night light.' },
  { code: '/bar-mojito', name: 'Mojito', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Mojito macro photography: muddled mint leaves and lime wedges crushed at the glass bottom, crushed ice, soda bubbles rising, extreme close-up on the fresh mint, bright refreshing light.' },
  { code: '/bar-caipirinha', name: 'Caipirinha', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Caipirinha photography: short glass with muddled lime chunks, cachaça and crushed ice, sugar crystals visible, lime wheel garnish, vibrant green tones, bright tropical bar light.' },
  { code: '/bar-negroni', name: 'Negroni', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Negroni photography: short crystal glass with large clear ice cube, deep amber cocktail, orange peel twist releasing oils, dark elegant bar background, dramatic side light, classic aperitivo mood.' },
  { code: '/bar-gintonic', name: 'Gin tonic', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Gin tonic photography: large copa glass with tonic bubbles, juniper berries and botanicals floating, cucumber ribbon, big ice cubes, backlit to make the drink glow, fresh botanical mood.' },
  { code: '/bar-aperol', name: 'Spritz de atardecer', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Aperol spritz photography: orange cocktail with prosecco bubbles and orange slice, golden hour terrace light, city blur behind, condensation on the glass, carefree summer aperitivo mood.' },
  { code: '/bar-margarita', name: 'Margarita', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Margarita photography: salt-rimmed glass with frosty frozen margarita, lime wheel, salt crystals in macro detail, vibrant turquoise bar backdrop, bright festive summer light, celebration mood.' },
  { code: '/bar-oldfashioned', name: 'Old fashioned', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Old fashioned photography: heavy rocks glass with spherical ice, amber whiskey, expressed orange peel, cherry, dark leather-and-wood bar background, moody dramatic side light, timeless classic mood.' },
  { code: '/bar-espressomartini', name: 'Espresso martini', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Espresso martini photography: coupe glass with velvety coffee crema, three coffee beans floating, dark roast tones, elegant dark bar background, dramatic spotlight, sophisticated night mood.' },
  { code: '/bar-piscosour', name: 'Pisco sour', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Pisco sour photography: coupe with thick white foam cap, drops of angostura bitters in a pattern, lime aroma, bright bar light, extreme close-up on the silky foam texture.' },
  { code: '/bar-daiquirifrozen', name: 'Daiquiri frozen', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Frozen daiquiri photography: frosty hurricane glass with icy strawberry daiquiri, sugar-frosted rim, fresh strawberry garnish, condensation, vibrant pink tones, bright tropical party light, fun celebration mood.' },
  { code: '/bar-moscowmule', name: 'Moscow mule', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Moscow mule photography: hammered copper mug with frost, ginger beer bubbles, lime wedge and mint, condensation on the metal, dark rustic bar background, dramatic side light.' },
  { code: '/bar-pinacolada', name: 'Piña colada en piña', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Piña colada photography: creamy cocktail served inside a hollowed pineapple, toasted coconut flakes, cherry and umbrella, tropical leaves behind, bright vacation light, playful overhead angle.' },
  { code: '/bar-tragocapas', name: 'Shot en capas', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Layered shot photography: B-52 shot glass with perfect distinct layers of coffee liqueur, Irish cream and orange liqueur, extreme macro on the clean layer lines, dark bar background, dramatic backlight.' },
  { code: '/bar-tequilashot', name: 'Shots de tequila', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Tequila shots photography: row of shot glasses with golden tequila, salt piles and lime wedges lined up, bar counter perspective, warm party light, fun night-out energy.' },
  { code: '/bar-vermut', name: 'Vermut con sifón', brandSafe: true,
    rubros: ['bar', 'gastronomia'],
    prompt: 'Vermouth photography: classic vermouth glass with siphon soda streaming mid-pour, olive and orange slice, vintage Argentine bar counter, warm nostalgic light, timeless aperitivo ritual mood.' },
  { code: '/bar-gancia', name: 'Gancia con limón', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Gancia photography: tall glass of golden americano with lemon slice and big ice, bubbles rising, condensation, Argentine bar table at sunset, warm relaxed after-office light.' },
  { code: '/bar-clericot', name: 'Clericot en jarra', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Clericó photography: large glass pitcher of white wine punch with floating orange, apple and strawberry slices, mint, condensation on the glass, bright summer afternoon light, festive sharing mood.' },
  { code: '/bar-sangria', name: 'Sangría', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Sangria photography: glass pitcher of red sangria with orange and apple chunks, cinnamon stick, wine glasses being filled, warm golden light, joyful Spanish-inspired gathering mood.' },
  { code: '/bar-malbec', name: 'Copa de malbec', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Malbec wine photography: large glass of deep red malbec backlit to glow ruby, wine swirl frozen in motion, dark elegant background, dramatic side light, premium Argentine wine mood.' },
  { code: '/bar-espumante', name: 'Espumante', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Sparkling wine photography: flute with rising bubble streams in extreme macro, golden sparkling wine, dark celebratory background with bokeh lights, elegant festive mood, dramatic backlight.' },
  { code: '/bar-vinoblanco', name: 'Vino blanco helado', brandSafe: true,
    rubros: ['bar'],
    prompt: 'White wine photography: chilled glass with condensation droplets, pale golden wine, fresh grapes beside it, bright crisp daylight, extreme close-up on the dewy glass, refreshing summer mood.' },
  { code: '/bar-ipa', name: 'IPA artesanal', brandSafe: true,
    rubros: ['bar'],
    prompt: 'IPA beer photography: tulip glass of hazy IPA with thick foam head, hop cones and citrus beside it, golden backlight through the beer, craft brewery mood, extreme refreshment detail.' },
  { code: '/bar-stout', name: 'Stout cremosa', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Stout beer photography: pint of dark stout with cascading creamy foam settling, nitro bubbles visible, dark roasted tones, dramatic pub backlight, extreme close-up on the velvety head.' },
  { code: '/bar-vuelocerveza', name: 'Vuelo de cervezas', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Beer flight photography: wooden paddle with four small glasses of different beer colors from pale to dark, brewery background blurred, warm tasting-room light, overhead three-quarter angle.' },
  { code: '/bar-canillas', name: 'Canillas del bar', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Beer taps photography: row of brass taps with chalkboard labels, fresh pint being poured with foam, brewery bar glow, shallow depth of field on the pouring stream, craft beer atmosphere.' },
  { code: '/bar-bartenderflair', name: 'Bartender en acción', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Bartender flair photography: bartender tossing a bottle mid-air, cocktail shaker in motion, bar lights streaking, frozen action with motion blur on the bottle, electric nightlife energy.' },
  { code: '/bar-coctelhumo', name: 'Cóctel con humo', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Smoked cocktail photography: cocktail glass under a glass cloche filled with swirling applewood smoke, bartender lifting the dome, dark moody bar, dramatic spotlight through the smoke.' },
  { code: '/bar-hielotallado', name: 'Hielo tallado', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Carved ice photography: crystal-clear ice sphere held in tongs over a rocks glass, whiskey pouring, macro detail on the perfect ice, dark luxurious bar background, dramatic side light.' },
  { code: '/bar-tiki', name: 'Cóctel tiki', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Tiki cocktail photography: carved tiki mug with flaming lime shell on top, tropical flowers and bamboo, bamboo bar background, warm exotic light, playful polynesian party mood.' },
  { code: '/bar-michelada', name: 'Michelada', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Michelada photography: tall glass with chamoy and tajín rim, golden beer with lime, tamarind candy straw, extreme close-up on the spicy rim, vibrant Mexican bar colors, bright light.' },
  { code: '/bar-ponchera', name: 'Ponchera de fiesta', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Punch bowl photography: large glass bowl of ruby punch with floating fruit and big ice block, ladle mid-pour into glasses, festive party table, warm joyful light, celebration mood.' },
  { code: '/bar-happyhour', name: 'Brindis 2x1', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Cheers photography: two colorful cocktails clinking in a toast, hands raised, bar bokeh lights behind, frozen motion on the clink, joyful happy-hour energy, warm night light.' },
  { code: '/bar-picadatrago', name: 'Vermut con picada', brandSafe: true,
    rubros: ['bar', 'gastronomia'],
    prompt: 'Vermouth and picada photography: vermouth glass beside a wooden board of salami, cheese and olives, classic Argentine bar table, warm nostalgic light, perfect pairing scene.' },
  { code: '/bar-afteroffice', name: 'After office', brandSafe: true,
    rubros: ['bar'],
    prompt: 'After-office toast photography: group of colleagues toasting with spritz cocktails, office windows blurred behind, golden evening light, laughter and motion, relaxed warm end-of-day celebration mood.' },
  { code: '/bar-djpista', name: 'Copa en la pista', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Party cocktail photography: hand raising a glowing cocktail above a dancing crowd, DJ booth lights and lasers behind, motion and energy frozen, electric nightclub atmosphere, vibrant colors.' },
  { code: '/bar-neon', name: 'Cartel de neón', brandSafe: true,
    rubros: ['bar'],
    prompt: 'Neon bar sign photography: glowing pink neon cocktail sign on a dark brick wall, silhouetted bar interior with drinks below, moody night light, urban nightlife aesthetic, cinematic wide shot.' },
];
