module.exports = [
  { code: '/barb-fadedetalle', name: 'Fade quirúrgico macro', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Extreme macro of surgical skin fade: seamless gradient from bald to dark, dramatic side light raking texture, 100mm macro lens, dark barbershop backdrop, precision craft photography, flawless blend.' },
  { code: '/barb-navaja', name: 'Afeitado a navaja', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Straight razor shave ritual: barber blade gliding through rich foam, warm tungsten barbershop light, 85mm lens, leather chair blur, classic gentleman grooming theater, timeless craft.' },
  { code: '/barb-barbalarga', name: 'Arreglo de barba larga', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Long beard grooming session: barber sculpting full beard with hot towel steam rising, moody warm light, 85mm lens, vintage barbershop interior, master craft atmosphere, careful detail.' },
  { code: '/barb-corteclasico', name: 'Corte clásico tijera y peine', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Classic scissor-over-comb cut: barber hands mid-technique, crisp daylight from storefront window, 70mm lens, timeless barbershop mood, old-school craftsmanship photography, precise sections, with refined detail and cinematic color.' },
  { code: '/barb-pompadour', name: 'Pompadour con volumen', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Voluminous pompadour styling: sculpted quiff catching window light, 85mm portrait lens, dark moody background, rockabilly barber aesthetic, bold silhouette photography, glossy hold, with luminous detail and authentic color.' },
  { code: '/barb-texturizado', name: 'Texturizado a tijera', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Textured scissor work detail: piecey layered crown under raking side light, 90mm lens, motion in strands, modern barber technique showcase, editorial hair photography, lived-in finish.' },
  { code: '/barb-contornosnavaja', name: 'Contornos a navaja', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Razor-sharp lineup detail: crisp hairline and temple edges, dramatic low-key lighting, 100mm macro lens, dark background, surgical precision barber photography, mirror-clean lines, with vivid detail and true-to-life color.' },
  { code: '/barb-disenofreestyle', name: 'Diseño freestyle a navaja', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Freestyle hair design art: geometric razor pattern carved in fade, neon accent lighting, 90mm lens, dark studio background, barber artistry portfolio shot, bold creativity, with tack-sharp detail and natural tones.' },
  { code: '/barb-ritualbarba', name: 'Ritual de barba con aceites', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Beard oil ritual: dropper releasing golden oil onto full beard, warm backlight glow, 100mm macro lens, wood and leather barbershop textures, premium grooming service, nourished shine.' },
  { code: '/barb-toallacaliente', name: 'Toalla caliente con vapor', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Hot towel treatment: steaming towel draped on client face, barber hands pressing gently, moody warm light, 70mm lens, old-school barbershop luxury ritual, deep relaxation, with crisp detail and balanced tones.' },
  { code: '/barb-espumamoldada', name: 'Espuma moldeada a brocha', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Badger brush lathering: thick shaving foam swirled on cheek, warm side light, 100mm macro lens, vintage porcelain bowl, classic wet-shave barber theater, rich lather texture.' },
  { code: '/barb-cejasbarber', name: 'Perfilado de cejas barber', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Barber brow detailing: precise razor cleanup of thick masculine brows, bright focused LED light, 90mm lens, sharp contrast, finishing-touch grooming service, clean definition, with tack-sharp detail and natural tones.' },
  { code: '/barb-limpiezacutis', name: 'Limpieza de cutis barber', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Men facial cleansing: purifying mask on relaxed client in barber chair, cool spa-like light, 70mm lens, modern barbershop skincare service, calm masculine wellness, fresh skin.' },
  { code: '/barb-mascarillanegra', name: 'Mascarilla de puntos negros', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Blackhead peel-off mask: charcoal mask mid-peel reveal, dramatic side lighting, 90mm lens, dark background, satisfying skincare transformation, barber facial service, clean pores, with crisp detail and balanced tones.' },
  { code: '/barb-masajecraneal', name: 'Masaje craneal', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Head massage finale: barber hands kneading scalp post-cut, warm dim barbershop glow, 70mm lens, pure relaxation expression, signature service-closer photography, tension release, with refined detail and cinematic color.' },
  { code: '/barb-sillonvintage', name: 'Sillón de barbero clásico', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Vintage barber chair hero shot: chrome and oxblood leather throne, dramatic spotlight from above, 35mm wide lens, empty shop anticipation, iconic barbershop identity, nostalgic grandeur.' },
  { code: '/barb-maquinadetalle', name: 'Máquina de corte detalle', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Clipper detail macro: premium cordless machine with engraved blade, dramatic rim light, 100mm macro lens, dark metal background, barber tool fetish photography, pro-grade hardware, with rich detail and natural color.' },
  { code: '/barb-antesdespuesfade', name: 'Antes y después del fade', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Before-and-after fade reveal: split composition overgrown hair versus surgical fade, even studio light, 50mm lens, transformation storytelling, barber results showcase, dramatic contrast, with vivid detail and true-to-life color.' },
  { code: '/barb-cortenino', name: 'Corte de niño', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Kids haircut moment: smiling boy with fresh textured crop, booster seat, bright cheerful daylight, 50mm lens, family-friendly barbershop warmth, proud little client, fun atmosphere, with tack-sharp detail and natural tones.' },
  { code: '/barb-caballerocanas', name: 'Caballero de canas', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Distinguished silver-fox cut: salt-and-pepper taper on mature gentleman, elegant window light, 85mm portrait lens, refined barbershop sophistication, timeless style, confident maturity, with rich detail and natural color.' },
  { code: '/barb-noviobarba', name: 'Novio barba perfecta', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Groom wedding-day beard: immaculately edged full beard, soft morning light, 85mm lens, suit and boutonniere blur, wedding-morning barber service photography, flawless detail, with vivid detail and true-to-life color.' },
  { code: '/barb-estilourbano', name: 'Estilo urbano', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Urban street style cut: high skin fade with textured top, client on city sidewalk, golden hour backlight, 50mm lens, streetwear barber culture, confident attitude, city energy.' },
  { code: '/barb-curlytop', name: 'Curly top con fade', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Curly top fade: defined coils above crisp skin fade, raking daylight sculpting texture, 85mm lens, urban backdrop blur, curl-specialist barber photography, natural volume celebration, with luminous detail and authentic color.' },
  { code: '/barb-mulletmoderno', name: 'Mullet moderno', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Modern mullet revival: business front party back with textured layers, neon barbershop glow, 85mm lens, rebellious retro aesthetic, statement cut photography, fearless style, with crisp detail and balanced tones.' },
  { code: '/barb-buzzdegradado', name: 'Buzz cut degradado', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Faded buzz cut: military-clean gradient on scalp, hard side light revealing blend, 90mm lens, minimal dark background, precision clipper craft, sharp geometry, disciplined finish, with refined detail and cinematic color.' },
  { code: '/barb-cropfrances', name: 'Crop francés', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'French crop detail: blunt textured fringe with skin fade sides, soft daylight, 85mm lens, European minimalist barber mood, clean architectural haircut, effortless cool, with luminous detail and authentic color.' },
  { code: '/barb-lineupfrente', name: 'Lineup de frente', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Frontal lineup macro: razor-crisp forehead hairline, dramatic low-key light, 100mm macro lens, dark background, barber precision signature shot, geometric perfection, with crisp detail and balanced tones.' },
  { code: '/barb-barbacorta', name: 'Barba corta aliñada', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Short groomed beard: neat stubble with defined cheek line, soft window light, 85mm portrait lens, corporate-friendly barber finish, sharp professional look, tidy edges, with refined detail and cinematic color.' },
  { code: '/barb-barbaestilizada', name: 'Barba estilizada con contorno', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Sculpted beard contour: carved jawline definition on full beard, dramatic chiaroscuro light, 85mm lens, dark background, barber sculpting artistry, chiseled masculinity, with luminous detail and authentic color.' },
  { code: '/barb-bigoteclasico', name: 'Bigote clásico con cera', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Classic handlebar mustache: waxed curled tips, barber applying finishing wax, warm vintage light, 100mm macro lens, gentleman dandy aesthetic, retro craft, meticulous grooming, with crisp detail and balanced tones.' },
  { code: '/barb-patinabarba', name: 'Pátina en barba', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Beard tinting service: camouflage color blending grays, barber brush application, bright salon light, 90mm lens, subtle age-defying transformation, modern barber menu, natural result, with refined detail and cinematic color.' },
  { code: '/barb-platinadohombre', name: 'Platinado masculino', brandSafe: true,
    rubros: ['barberia', 'belleza'],
    prompt: 'Bleached platinum crop on man: icy buzzed texture, cool blue studio light, 85mm lens, bold fashion-forward barber color service, striking contrast portrait, fearless transformation, with luminous detail and authentic color.' },
  { code: '/barb-trenzashombre', name: 'Trenzas masculinas', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Men braided style: tight cornrows with fade sides, dramatic side light, 90mm lens, urban studio background, protective style barber craftsmanship, sharp cultural style, with crisp detail and balanced tones.' },
  { code: '/barb-dreadsmantenimiento', name: 'Mantenimiento de dreads', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Loc maintenance session: barber retwisting mature locs, warm natural light, 85mm lens, textured detail, dread specialist barber service, cultural craft respect, healthy roots, with refined detail and cinematic color.' },
  { code: '/barb-exfoliacionfacial', name: 'Exfoliación facial', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Men facial exfoliation: scrub application on t-zone, fresh bright light, 90mm lens, clean modern barbershop skincare corner, grooming upgrade service, renewed skin texture, with luminous detail and authentic color.' },
  { code: '/barb-combocortebarba', name: 'Combo corte + barba', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Full service transformation: fresh fade with sculpted beard, client checking mirror, warm barbershop glow, 50mm lens, complete look reveal, signature combo package, total renewal, with crisp detail and balanced tones.' },
  { code: '/barb-ambientecafe', name: 'Barbería con café', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Barbershop coffee corner: espresso cup beside vintage chair, warm morning light through blinds, 35mm lens, lifestyle hospitality detail, third-place barbershop culture, welcoming ritual, with refined detail and cinematic color.' },
  { code: '/barb-nochebarber', name: 'Noche de barbería', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Barbershop night event: friends with fresh cuts under string lights, warm festive glow, 35mm lens, community gathering energy, local culture celebration photography, good vibes, with luminous detail and authentic color.' },
  { code: '/barb-planmensual', name: 'Plan mensual de cortes', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Monthly membership lifestyle: regular client greeting barber by name, bright welcoming light, 50mm lens, loyalty and belonging mood, subscription service storytelling, always sharp, with crisp detail and balanced tones.' },
  { code: '/barb-barberotrabajando', name: 'Barbero en acción', brandSafe: true,
    rubros: ['barberia'],
    prompt: 'Barber at work documentary: focused hands blending with clippers, motion blur on wrist, warm shop light, 50mm lens, craft-in-action storytelling, authentic trade pride, masterful flow.' },
];
