module.exports = [
  { code: '/bel-uniasnails', name: 'Uñas con esmaltado perfecto', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Extreme macro of freshly manicured nails with flawless glossy gel polish, softbox side light, 100mm macro lens, shallow depth of field, elegant hand pose on silk fabric, salon luxury mood, crisp reflections.' },
  { code: '/bel-facialspa', name: 'Facial en spa', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Serene spa facial photography: esthetician hands applying cream mask, white towels, soft diffused daylight, eucalyptus sprigs, calm luxury wellness mood, shallow depth of field, tranquil interior bokeh.' },
  { code: '/bel-peluqueriabarrido', name: 'Barrido en pelo largo', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Dynamic hair sweep photography: long glossy hair mid-motion with balayage highlights, backlit golden hour window light, 85mm portrait lens, frozen movement, flowing salon energy, clean bright background.' },
  { code: '/bel-cejasdiseno', name: 'Diseño de cejas primer plano', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Close-up brow design photography: perfectly shaped eyebrow with precise strokes, ring light reflection, 90mm macro lens, neutral beige background, hyper-detailed texture, professional brow studio aesthetic, symmetrical framing.' },
  { code: '/bel-maquillajenovia', name: 'Makeup de novia luz suave', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Bridal makeup portrait: soft romantic glow, dewy skin, nude lips, diffused window daylight, 85mm lens at f2, blurred white florals, elegant timeless bridal mood, gentle highlights on cheekbones.' },
  { code: '/bel-bobcorte', name: 'Corte bob detalle', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Precision bob haircut detail: sharp blunt ends, glossy straight texture, dramatic side lighting, 70mm lens, dark studio background, geometric editorial salon photography, crisp architectural lines, polished finish.' },
  { code: '/bel-rubioplatino', name: 'Rubio platinado', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Platinum blonde transformation: icy luminous strands catching cool daylight, slow-motion hair flip, 85mm portrait lens, minimalist white studio, high-fashion color service showcase, mirror-like shine, with rich detail and natural color.' },
  { code: '/bel-balayagedetalle', name: 'Balayage detalle', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Balayage color detail: sun-kissed hand-painted strands, warm backlight through hair, 85mm lens, shallow depth of field, caramel dimension on dark base, premium salon color work, seamless blend.' },
  { code: '/bel-rizosdefinidos', name: 'Rizos definidos', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Defined curl photography: bouncy hydrated ringlets with brilliant shine, soft diffused natural light, 85mm lens, dark warm background, curl specialist salon mood, texture celebration, frizz-free definition.' },
  { code: '/bel-recogidofiesta', name: 'Recogido de fiesta', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Elegant updo hairstyle: intricate twisted bun with face-framing strands, warm chandelier glow, 85mm lens at f2, blurred ballroom bokeh, bridal party sophistication, timeless glamour, delicate hair accessories.' },
  { code: '/bel-trenzasdetalle', name: 'Trenzas detalle', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Intricate braided hairstyle detail: tight cornrows with golden cuffs, dramatic side light sculpting texture, 100mm macro lens, dark background, artistic protective-style salon photography, regal patterns.' },
  { code: '/bel-keratinabril', name: 'Alisado con keratina', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Keratin-smooth hair reveal: mirror-gloss straight hair catching window light streaks, slow hair flip, 85mm lens, clean salon backdrop, frizz-free transformation showcase, silky weightless movement, with rich detail and natural color.' },
  { code: '/bel-extensionesvolumen', name: 'Extensiones con volumen', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Hair extensions volume reveal: cascading thick waves, golden backlight, 85mm portrait lens, wind-blown motion, luxurious length transformation, premium extension service photography, undetectable blend, with vivid detail and true-to-life color.' },
  { code: '/bel-colorfantasia', name: 'Color fantasía', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Vivid fantasy hair color: pastel pink and lavender melted tones, neon-tinted studio lighting, 85mm lens, dark backdrop, bold creative colorist portfolio shot, electric saturation, dreamy gradient.' },
  { code: '/bel-maquillajesocial', name: 'Makeup social de noche', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Night-out glam makeup: smoky eyes with shimmer, contoured glow, city lights bokeh behind, 85mm lens at f1.8, warm tungsten ambience, party-ready beauty editorial, confident allure.' },
  { code: '/bel-maquillajeeditorial', name: 'Makeup editorial', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Avant-garde editorial makeup: bold graphic liner, sculpted skin, hard studio strobe, 100mm lens, stark white background, high-fashion beauty campaign aesthetic, striking contrast, artistic vision, with rich detail and natural color.' },
  { code: '/bel-delineadografico', name: 'Delineado gráfico macro', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Extreme close-up of graphic winged eyeliner: razor-sharp black line, ring light catchlight, 100mm macro lens, flawless skin texture, precision makeup artistry showcase, symmetrical wings, with vivid detail and true-to-life color.' },
  { code: '/bel-labiosrojos', name: 'Labios rojos macro', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Macro red lipstick detail: velvet matte crimson lips, soft diffused beauty light, 100mm macro lens, porcelain skin, luxury cosmetics campaign mood, sensual color focus, crisp lip line.' },
  { code: '/bel-sombraahumada', name: 'Sombra ahumada ojo macro', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Smoky eye macro photography: blended charcoal and bronze shimmer, dramatic side lighting, 100mm macro lens, dark moody background, sultry evening makeup artistry, seamless gradient blend.' },
  { code: '/bel-pielperfecta', name: 'Piel perfecta base', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Flawless base makeup close-up: airbrushed luminous skin, soft beauty dish light, 90mm lens, seamless foundation finish, professional MUA portfolio, dewy natural perfection, second-skin effect, with rich detail and natural color.' },
  { code: '/bel-glowiluminador', name: 'Glow con iluminador', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Radiant highlighter glow portrait: lit-from-within cheekbones, golden hour backlight, 85mm lens at f2, sun flare, summer dewy makeup trend, luminous skin celebration, fresh radiance, with vivid detail and true-to-life color.' },
  { code: '/bel-pestanasefecto', name: 'Pestañas efecto rímel', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Dramatic lash extension close-up: fanned voluminous lashes, ring light sparkle, 100mm macro lens, downcast gaze, lash studio artistry, dark elegant background, feathery texture, with tack-sharp detail and natural tones.' },
  { code: '/bel-laminadocejas', name: 'Laminado de cejas', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Brow lamination result: brushed-up fluffy full brows, soft diffused daylight, 90mm lens, before-after reveal energy, modern brow bar aesthetic, crisp detail, feathered finish, with rich detail and natural color.' },
  { code: '/bel-microbladingproceso', name: 'Microblading en proceso', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Microblading procedure in progress: artist hand with fine blade, numbed brow area, clinical bright LED light, 90mm lens, hygienic studio setting, trust-building service photography, precise strokes.' },
  { code: '/bel-limpiezafacial', name: 'Limpieza facial profunda', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Deep facial cleansing treatment: gentle foam cleanse on relaxed client, steamed spa ambience, soft diffused light, 70mm lens, white towels and botanicals, purifying skincare ritual, serene expression.' },
  { code: '/bel-mascarillatratamiento', name: 'Mascarilla de tratamiento', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Clay mask treatment moment: green botanical mask on serene face, cucumber slices, soft spa daylight, 70mm lens, eucalyptus steam, detox skincare service photography, calm luxury.' },
  { code: '/bel-dermapen', name: 'Microneedling dermapen', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Microneedling dermapen session: professional device gliding on cheek, bright clinical LED light, 90mm lens, sterile premium clinic setting, advanced skincare treatment photography, rejuvenation promise, with luminous detail and authentic color.' },
  { code: '/bel-peelingglow', name: 'Peeling con glow', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Chemical peel glow reveal: luminous post-treatment skin, soft beauty light, 85mm lens, fresh radiant complexion, dermatology-grade skincare service, clean clinical luxury, glass-skin finish, with crisp detail and balanced tones.' },
  { code: '/bel-masajefacial', name: 'Masaje facial gua sha', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Gua sha facial massage: jade tool sculpting jawline, warm candlelight spa glow, 70mm lens, serene closed eyes, botanical oils, sculpting wellness ritual photography, lymphatic flow.' },
  { code: '/bel-piedrascalientes', name: 'Masaje con piedras calientes', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Hot stone massage therapy: smooth basalt stones on back, dim amber spa lighting, 50mm lens, orchid petals, deep relaxation wellness photography, tranquil luxury mood, soothing warmth.' },
  { code: '/bel-depilacionlaser', name: 'Depilación láser', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Laser hair removal session: modern device on smooth leg, cool blue clinical light, 70mm lens, sterile premium aesthetic clinic, confident smooth-skin service photography, painless technology.' },
  { code: '/bel-ceraespanola', name: 'Depilación con cera', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Waxing service detail: warm wax application strip, soft salon lighting, 70mm lens, clean treatment room, professional depilation studio, smooth skin promise photography, gentle technique, with rich detail and natural color.' },
  { code: '/bel-manicurarusa', name: 'Manicura rusa', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Russian manicure precision: perfect cuticle work under magnifier lamp, bright LED task light, 100mm macro lens, nude polish finish, elite nail studio craftsmanship, immaculate detail.' },
  { code: '/bel-pedicuraspa', name: 'Pedicura spa', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Spa pedicure ritual: feet in petal-filled soak basin, soft morning light, 50mm lens, white towels and orchids, pampering nail salon experience, tranquil luxury, self-care moment.' },
  { code: '/bel-nailartmanoalzada', name: 'Nail art mano alzada', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Hand-painted nail art detail: miniature floral design on almond nails, bright macro LED light, 100mm macro lens, artist brush mid-stroke, wearable miniature art photography, delicate precision.' },
  { code: '/bel-efectoaurora', name: 'Uñas efecto aurora', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Aurora chrome nails macro: iridescent shifting color play, dramatic side light, 100mm macro lens, dark background, futuristic nail trend photography, holographic shimmer, glass-like finish, with luminous detail and authentic color.' },
  { code: '/bel-pressonnails', name: 'Press-on nails', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Press-on nail kit product shot: elegant reusable nail sets in premium packaging, soft daylight, 50mm lens, salon-quality at home concept, beauty retail photography, effortless glamour.' },
  { code: '/bel-corporalreductor', name: 'Tratamiento corporal reductor', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Body contouring treatment: professional applicator on waist, modern aesthetic clinic, cool clinical light, 70mm lens, confident wellness transformation, premium body service photography, visible results, with vivid detail and true-to-life color.' },
  { code: '/bel-drenajelinfatico', name: 'Drenaje linfático', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Lymphatic drainage massage: gentle rhythmic hand movements on legs, soft spa daylight, 70mm lens, serene wellness setting, detox body ritual, calm therapeutic photography, lightness sensation.' },
  { code: '/bel-maquillajequince', name: 'Makeup de quinceañera', brandSafe: true,
    rubros: ['belleza'],
    prompt: 'Quinceañera makeup portrait: soft pink glam, long lashes, golden backlight, 85mm lens at f2, blurred celebration decor, dreamy milestone beauty photography, radiant youthful elegance, with luminous detail and authentic color.' },
];
