module.exports = [
  { code: '/cafe-barista', name: 'Latte art cenital', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Overhead latte art photography: perfect rosetta in a white ceramic cup, centered top-down composition, velvety microfoam texture in macro detail, warm café light, minimalist wooden table.' },
  { code: '/cafe-espresso', name: 'Espresso en extracción', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Espresso extraction photography: rich espresso streaming from the portafilter into a small cup, tiger-striped crema forming, extreme macro on the flowing coffee, warm dramatic café light.' },
  { code: '/cafe-capuccino', name: 'Capuccino clásico', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Cappuccino photography: classic cup with thick foam cap dusted with cocoa powder, heart shape in the foam, white ceramic on a saucer, warm morning café light, cozy Italian mood.' },
  { code: '/cafe-flatwhite', name: 'Flat white', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Flat white photography: double ristretto with silky steamed milk, minimalist tulip art, small ceramic cup, extreme close-up on the glossy surface, soft natural window light, specialty café mood.' },
  { code: '/cafe-cortado', name: 'Cortado en vaso', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Cortado photography: small glass showing the perfect layered line between espresso and steamed milk, warm backlight glowing through the glass, minimalist composition, specialty coffee bar mood.' },
  { code: '/cafe-submarino', name: 'Submarino', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Submarino photography: tall glass of hot milk with a dark chocolate bar melting inside, chocolate swirls rising, steam curling up, cozy Argentine café light, nostalgic comfort mood.' },
  { code: '/cafe-cafeconleche', name: 'Café con leche y medialuna', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Argentine breakfast photography: café con leche in a classic glass cup beside a buttery medialuna on a white plate, morning light through the café window, timeless porteño bar mood.' },
  { code: '/cafe-medialunamanteca', name: 'Medialunas con manteca', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Medialunas photography: golden flaky medialunas with melted butter glistening on top, extreme macro on the crisp layers, warm bakery light, steam rising, irresistible fresh-from-the-oven mood.' },
  { code: '/cafe-metodo', name: 'V60 filtrado', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Pour-over photography: V60 dripper with coffee blooming, thin steam rising, gooseneck kettle mid-pour, soft window light creating a gentle glow, calm serene slow-bar ritual mood.' },
  { code: '/cafe-lattehelado', name: 'Latte helado en capas', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Iced latte photography: tall glass with distinct layers of milk and espresso over clear ice cubes, condensation droplets, dramatic side light through the glass, refreshing summer café mood.' },
  { code: '/cafe-frappe', name: 'Frappé con crema', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Frappé photography: tall glass of blended iced coffee crowned with whipped cream and chocolate drizzle, striped straw, condensation, bright cheerful light, playful summer refreshment mood.' },
  { code: '/cafe-moka', name: 'Moka', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Mocha photography: glass mug with visible layers of chocolate, espresso and steamed milk, cocoa dusted on the foam, warm cozy light, extreme close-up on the layered colors.' },
  { code: '/cafe-matcha', name: 'Matcha latte', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Matcha latte photography: vibrant green matcha with delicate foam, bamboo whisk beside the cup, minimalist Japanese-inspired styling, soft natural window light, calm zen café mood.' },
  { code: '/cafe-chailatte', name: 'Chai latte', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Chai latte photography: spiced milk tea with cinnamon sticks and star anise, foam dusted with cinnamon, warm amber tones, cozy autumn light, comforting spiced aroma mood.' },
  { code: '/cafe-chocolatecaliente', name: 'Chocolate caliente', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Hot chocolate photography: thick dark hot chocolate with melting marshmallows, chocolate shavings on top, steam rising, hands warming around the mug, cozy winter café light.' },
  { code: '/cafe-limonada', name: 'Limonada con menta', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Mint lemonade photography: glass pitcher of fresh lemonade with muddled mint and lemon wheels, crushed ice, condensation, bright sunny light, extreme freshness and refreshment mood.' },
  { code: '/cafe-licuadobanana', name: 'Licuado de banana', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Banana smoothie photography: creamy licuado in a tall glass with banana slices and cinnamon dust, thick texture visible, bright morning light, healthy energizing breakfast mood.' },
  { code: '/cafe-jugonaranja', name: 'Jugo de naranja exprimido', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Fresh orange juice photography: glass of just-squeezed juice with pulp, halved oranges and a manual juicer beside it, bright citrusy morning light, vibrant healthy start-of-day mood.' },
  { code: '/cafe-tostado', name: 'Tostado de la plancha', brandSafe: true,
    rubros: ['cafeteria', 'gastronomia'],
    prompt: 'Grilled tostado photography: pressed ham and cheese sandwich cut diagonally, molten cheese stretching between halves, golden crispy bread, extreme close-up on the cheese pull, warm diner light.' },
  { code: '/cafe-avocadotoast', name: 'Tostada con palta', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Avocado toast photography: sourdough slice with smashed avocado, poached egg with runny yolk, chili flakes and seeds, bright fresh morning light, modern brunch styling, overhead angle.' },
  { code: '/cafe-croissant', name: 'Croissant hojaldrado', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Croissant macro photography: flaky golden croissant with visible honeycomb layers at the torn edge, butter glistening, extreme close-up on the crisp texture, warm bakery morning light.' },
  { code: '/cafe-churros', name: 'Churros con chocolate', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Churros photography: sugar-dusted churros stacked beside a cup of thick hot chocolate for dipping, cinnamon sugar sparkle, warm cozy light, festive warm Argentine-Spanish merienda mood.' },
  { code: '/cafe-facturas', name: 'Docena de facturas', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Facturas box photography: open box of assorted Argentine facturas — medialunas, vigilantes, tortitas negras — colorful sugary variety, warm bakery light, overhead angle, weekend indulgence mood.' },
  { code: '/cafe-alfajor', name: 'Alfajor partido', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Alfajor photography: chocolate alfajor broken in half with dulce de leche oozing out, crumbs and chocolate coating in macro detail, warm nostalgic light, iconic Argentine treat mood.' },
  { code: '/cafe-cookie', name: 'Cookie recién horneada', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Cookie photography: warm chocolate chip cookie broken open with molten chocolate chips stretching, sea salt flakes, extreme macro on the gooey center, warm bakery light, irresistible fresh-baked mood.' },
  { code: '/cafe-brownie', name: 'Brownie tibio con helado', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Brownie photography: warm fudgy brownie with a melting vanilla ice cream scoop, hot chocolate sauce dripping, cocoa powder dust, extreme close-up on the contrast, cozy dessert mood.' },
  { code: '/cafe-carrotcake', name: 'Carrot cake', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Carrot cake photography: slice with thick cream cheese frosting and walnut crunch, moist spiced crumb visible, cinnamon dust, warm bakery light, homemade warm comfort mood.' },
  { code: '/cafe-budinlimon', name: 'Budín de limón', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Lemon budín photography: slice of moist lemon loaf with glossy citrus glaze dripping, lemon zest on top, bright fresh light, extreme close-up on the tender crumb, cheerful tea-time mood.' },
  { code: '/cafe-lemonpie', name: 'Lemon pie', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Lemon pie photography: slice with torched golden meringue peaks, vibrant lemon curd layer, buttery crust, extreme macro on the caramelized meringue, bright elegant pastry light.' },
  { code: '/cafe-tortachoco', name: 'Torta de chocolate', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Chocolate cake photography: tall slice with glossy ganache dripping down dark rich moist layers, chocolate shavings, extreme close-up on the dripping ganache, dramatic patisserie light.' },
  { code: '/cafe-cheesecakerjos', name: 'Cheesecake de frutos rojos', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Cheesecake photography: creamy silky New York slice topped with glossy berry compote dripping down, biscuit base visible, fresh berries, bright elegant light, refined dessert mood.' },
  { code: '/cafe-muffin', name: 'Muffin de arándanos', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Blueberry muffin photography: domed muffin with bursting blueberries and sugar-crystal top, paper wrapper peeled slightly, extreme macro on the juicy berries, warm morning bakery light.' },
  { code: '/cafe-molinillo', name: 'Granos y molienda', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Coffee beans photography: freshly roasted beans tumbling from a grinder, some mid-air frozen, rich brown tones and oily sheen in macro detail, warm roastery light, craft coffee origin mood.' },
  { code: '/cafe-baristavertido', name: 'Barista vertiendo', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Barista action photography: barista pouring steamed milk from a steel pitcher into a cup, latte art forming, focused hands in motion, warm café backlight, craft and passion mood.' },
  { code: '/cafe-mesadesayuno', name: 'Mesa de desayuno', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Breakfast table photography: full café breakfast spread — coffee, medialunas, juice, tostadas — morning sunlight streaming across the table, long shadows, inviting weekend morning mood, wide angle.' },
  { code: '/cafe-meriendados', name: 'Merienda para dos', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Merienda for two photography: two cappuccinos with latte art and a shared cake plate on a small marble table, intimate café corner, warm afternoon light, perfect date-promo scene.' },
  { code: '/cafe-vidriera', name: 'Vidriera de tortas', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Café display photography: glass showcase filled with cakes, tarts and facturas, warm display lighting making everything glow, shallow depth of field, tempting patisserie window mood.' },
  { code: '/cafe-rinconlector', name: 'Rincón lector', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Cozy reading corner photography: cappuccino steaming on a small wooden table beside an armchair and open book, warm lamp light, rain-softened window blur, quiet literary café mood.' },
  { code: '/cafe-lluvia', name: 'Café en día de lluvia', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Rainy day café photography: hot latte on a windowsill with raindrops streaking the glass behind, city blur, steam rising from the cup, moody blue-grey light, melancholic cozy refuge mood.' },
  { code: '/cafe-trabajo', name: 'Café y laptop', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Digital nomad photography: laptop open beside a flat white on a café table, notebook and phone, warm productive light, shallow depth of field, modern work-from-café lifestyle mood.' },
  { code: '/cafe-momentomerienda', name: 'Momento merienda', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Hands breaking open a buttery medialuna, flaky layers and steam, classic glass cup of cafe con leche beside it on a marble bar counter, warm morning window light, porteno ritual mood, documentary candid feel, upper third clean for a headline.' },
  { code: '/cafe-baristaaccion', name: 'Barista en acción', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Barista mid-pour of latte art in motion, milk stream frozen, focused face visible, apron with house identity, warm cafe light, craft and oficio pride, unposed working moment, upper third clean for a headline.' },
  { code: '/cafe-mesaservida', name: 'Mesa servida social', brandSafe: true,
    rubros: ['cafeteria'],
    prompt: 'Bar table with two complete meriendas (cafe con leche, medialunas, tostadas), hands of two people reaching in, warm morning light through the window, social ritual moment, candid and inviting, upper third clean for a headline.' },
];
