module.exports = [
  { code: "/deco-livingnordico", name: "Living nórdico en luz de mañana", brandSafe: true,
    rubros: ["deco"],
    prompt: "Scandinavian living room bathed in soft morning sunlight through sheer curtains, light oak sofa, wool throw, birch coffee table, editorial interior photography, 35mm wide composition, airy minimalist styling." },
  { code: "/deco-mesaratona", name: "Mesa ratona con styling", brandSafe: true,
    rubros: ["deco"],
    prompt: "Styled oak coffee table with stacked art books, ceramic vase with dried pampas grass and a scented candle, warm window light, 50mm eye-level shot, shallow depth, editorial home styling photograph." },
  { code: "/deco-paredgaleria", name: "Pared galería con cuadros", brandSafe: true,
    rubros: ["deco"],
    prompt: "Eclectic gallery wall with black-framed prints and one oversized abstract canvas above a walnut console, even gallery spot lighting, straight-on architectural photograph, symmetrical balanced composition." },
  { code: "/deco-velaaromatica", name: "Vela encendida con humo", brandSafe: true,
    rubros: ["deco"],
    prompt: "Lit amber glass candle with a thin curl of smoke rising, dark moody background, single warm side light, macro 85mm lens, dramatic chiaroscuro, cozy luxury product photography." },
  { code: "/deco-dormitoriolinen", name: "Dormitorio con ropa de lino arrugada", brandSafe: true,
    rubros: ["deco"],
    prompt: "Bed dressed in rumpled natural linen bedding in oatmeal tones, morning light raking across the fabric texture, oak bed frame, 35mm wide shot, relaxed lived-in luxury bedroom photography." },
  { code: "/deco-cocinaencimera", name: "Cocina con encimera de mármol", brandSafe: true,
    rubros: ["deco"],
    prompt: "Marble kitchen island styled with olive oil bottles, wooden board and fresh herbs, bright daylight from large window, brass faucet detail, 24mm wide interior shot, clean architectural composition." },
  { code: "/deco-rinconlectura", name: "Rincón de lectura con sillón", brandSafe: true,
    rubros: ["deco"],
    prompt: "Cozy reading nook with boucle armchair, brass arc floor lamp and small side table with open book, warm pool of lamplight at dusk, 50mm three-quarter view, inviting editorial interior photograph." },
  { code: "/deco-comedorpendiente", name: "Comedor con lámpara colgante de rattan", brandSafe: true,
    rubros: ["deco"],
    prompt: "Dining room with oversized rattan pendant light glowing above a solid wood table set for dinner, warm tungsten ambience, low-angle 35mm shot, convivial editorial interior photography." },
  { code: "/deco-recibidor", name: "Recibidor con consola y espejo redondo", brandSafe: true,
    rubros: ["deco"],
    prompt: "Entryway console table with round brass mirror, ceramic tray and dried bouquet, soft daylight from side window, straight-on 35mm composition, welcoming editorial hallway photograph, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/deco-plantarincón", name: "Rincón jungla de plantas de interior", brandSafe: true,
    rubros: ["deco"],
    prompt: "Lush corner of indoor plants in terracotta and ceramic pots at varying heights, monstera and fiddle leaf fig, bright diffused window light, 35mm wide shot, fresh biophilic interior photography." },
  { code: "/deco-textilesmanta", name: "Mantas y almohadones apilados", brandSafe: true,
    rubros: ["deco"],
    prompt: "Stack of folded throws and cushions in bouclé, linen and chunky knit textures, earthy palette, soft window light raking across fibers, 60mm close composition, tactile textile product photography." },
  { code: "/deco-oficinacasa", name: "Home office con escritorio de roble", brandSafe: true,
    rubros: ["deco"],
    prompt: "Home office with solid oak desk, ergonomic chair, floating shelves with books and a small plant, daylight from left window, 35mm three-quarter shot, calm productive workspace photography." },
  { code: "/deco-balconverde", name: "Balcón con sillones y macetas colgantes", brandSafe: true,
    rubros: ["deco"],
    prompt: "Small balcony with two wicker chairs, hanging planters and string lights, golden hour glow, city backdrop softly blurred, 35mm wide shot, dreamy outdoor living photography." },
  { code: "/deco-cocinarustica", name: "Cocina rústica de madera y hierro", brandSafe: true,
    rubros: ["deco"],
    prompt: "Rustic kitchen with reclaimed wood cabinets, black iron hardware and stone backsplash, warm morning light, copper pots hanging, 24mm wide interior shot, artisanal countryside editorial photography." },
  { code: "/deco-bañoazulejo", name: "Baño con azulejos estampados", brandSafe: true,
    rubros: ["deco"],
    prompt: "Bathroom with patterned cement tiles, brass fixtures and round mirror, skylight daylight, eucalyptus sprig in vase, 24mm wide architectural shot, boutique hotel style interior photography." },
  { code: "/deco-chimeneasillon", name: "Chimenea de leña con sillón de cuero", brandSafe: true,
    rubros: ["deco"],
    prompt: "Crackling wood fireplace with worn leather armchair and wool blanket beside it, firelight as the main warm source, 50mm intimate framing, cozy winter editorial interior photograph." },
  { code: "/deco-cuartoniño", name: "Cuarto infantil con tipi y guirnalda", brandSafe: true,
    rubros: ["deco"],
    prompt: "Children bedroom with canvas tipi tent, string lights and low wooden bed with colorful bedding, soft afternoon light, 35mm wide playful composition, cheerful kids interior photography." },
  { code: "/deco-vestidorabierto", name: "Vestidor abierto con barras de madera", brandSafe: true,
    rubros: ["deco"],
    prompt: "Open walk-in closet with wooden rails, neatly hung garments sorted by tone and woven baskets below, even daylight from doorway, 24mm straight-on shot, aspirational organization photography." },
  { code: "/deco-terrazanoche", name: "Terraza de noche con guirnaldas de luces", brandSafe: true,
    rubros: ["deco"],
    prompt: "Terrace at night strung with warm fairy lights over an outdoor sofa set, candles on the table, deep blue sky, 35mm wide shot at blue hour, magical outdoor entertaining photography." },
  { code: "/deco-pasilloarte", name: "Pasillo largo con cuadros y apliques", brandSafe: true,
    rubros: ["deco"],
    prompt: "Long hallway with framed art prints and brass wall sconces casting warm pools of light on limewashed walls, one-point perspective 24mm shot, gallery-like editorial interior photography." },
  { code: "/deco-cocinaazul", name: "Cocina azul petróleo con herrajes dorados", brandSafe: true,
    rubros: ["deco"],
    prompt: "Petrol blue kitchen cabinetry with brushed brass handles, white quartz counters and open oak shelf, crisp daylight, 24mm wide architectural shot, bold color-trend interior photography." },
  { code: "/deco-dormitoriocabecero", name: "Dormitorio con cabecero tapizado capitoné", brandSafe: true,
    rubros: ["deco"],
    prompt: "Bedroom with tall tufted velvet headboard in sage green, layered bedding and brass bedside lamps glowing, soft evening light, 50mm three-quarter view, luxurious boutique hotel photography." },
  { code: "/deco-barrincon", name: "Rincón bar con estantería de botellas", brandSafe: true,
    rubros: ["deco"],
    prompt: "Home bar corner with backlit bottle shelf, marble countertop and two leather stools, moody amber lighting, 35mm three-quarter shot, speakeasy-style entertaining photography, gentle atmospheric haze adds depth, vivid natural color grading." },
  { code: "/deco-cortinalino", name: "Ventana con cortinas de lino y luz filtrada", brandSafe: true,
    rubros: ["deco"],
    prompt: "Floor-to-ceiling linen curtains diffusing bright daylight into a neutral living room, sheer fabric glowing, 50mm detail composition, soft airy textile-focused interior photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/deco-alfombramesa", name: "Mesa de comedor sobre alfombra de yute", brandSafe: true,
    rubros: ["deco"],
    prompt: "Round jute rug anchoring a wooden dining table with rattan chairs, overhead 24mm wide shot from slight angle, natural daylight, layered texture editorial interior photography." },
  { code: "/deco-tvpanelmadera", name: "Living con panel de madera para TV", brandSafe: true,
    rubros: ["deco"],
    prompt: "Living room with slatted wood panel wall behind the TV, low media console and linen sofa, even daylight, straight-on 35mm architectural shot, modern media-wall interior photography." },
  { code: "/deco-cocinadesayunador", name: "Cocina con barra desayunadora", brandSafe: true,
    rubros: ["deco"],
    prompt: "Kitchen with breakfast bar, two oak stools and pendant lights above, croissants and coffee styled on the counter, morning window light, 35mm three-quarter shot, lifestyle kitchen photography." },
  { code: "/deco-bañoespejoredondo", name: "Baño con espejo redondo retroiluminado", brandSafe: true,
    rubros: ["deco"],
    prompt: "Bathroom vanity with backlit round mirror glowing, stone vessel sink and brushed nickel tap, soft evening ambience, 50mm straight-on shot, spa-like modern interior photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/deco-dormitorioplanta", name: "Dormitorio con monstera en maceta", brandSafe: true,
    rubros: ["deco"],
    prompt: "Bedroom corner with a large monstera in a ceramic pot beside the bed, morning light through blinds casting striped shadows, 35mm wide shot, fresh green-accent interior photography." },
  { code: "/deco-comedormadera", name: "Comedor con mesa de madera maciza", brandSafe: true,
    rubros: ["deco"],
    prompt: "Dining room centered on a solid wood table with live edge, linen runner and handmade ceramics, warm pendant light above, 35mm three-quarter view, artisanal craftsmanship photography." },
  { code: "/deco-cocinaestante", name: "Cocina con estantes abiertos y cerámica", brandSafe: true,
    rubros: ["deco"],
    prompt: "Kitchen open shelves styled with handmade ceramics, glass jars and trailing pothos, bright side window light, 50mm straight-on composition, curated shelfie interior photography, clean background separation, professional commercial polish throughout." },
  { code: "/deco-livingchimenea", name: "Living con chimenea empotrada", brandSafe: true,
    rubros: ["deco"],
    prompt: "Modern living room with linear gas fireplace set into a plaster wall, low boucle sofa facing it, flames as warm accent light, 35mm wide shot, contemporary hearth interior photography." },
  { code: "/deco-recibidorbanco", name: "Recibidor con banco y canastos", brandSafe: true,
    rubros: ["deco"],
    prompt: "Entryway with wooden bench, woven baskets underneath and hooks with coats above, soft daylight from glass door, 35mm straight-on shot, practical mudroom styling photography, delicate rim light defines edges, refined editorial finish." },
  { code: "/deco-dormitorioblanco", name: "Dormitorio todo blanco con luz cenital", brandSafe: true,
    rubros: ["deco"],
    prompt: "All-white bedroom with crisp bedding and pale wood floor, skylight pouring overhead daylight, minimal styling, 24mm wide architectural shot, serene minimalist interior photography, natural vignette draws the eye, authentic documentary feel." },
  { code: "/deco-cocinanegra", name: "Cocina negra mate con isla", brandSafe: true,
    rubros: ["deco"],
    prompt: "Matte black kitchen with central island, oak stools and marble backsplash veining, dramatic contrast lighting, 24mm wide shot, bold contemporary interior photography, fine detail in highlights and shadows, premium magazine look." },
  { code: "/deco-terrazadesayuno", name: "Terraza con mesa de desayuno para dos", brandSafe: true,
    rubros: ["deco"],
    prompt: "Terrace breakfast table for two with coffee, medialunas and a small flower vase, morning sun flares, plants framing the scene, 50mm lifestyle shot, al fresco morning photography." },
  { code: "/deco-estanterialibros", name: "Estantería de libros ordenada por color", brandSafe: true,
    rubros: ["deco"],
    prompt: "Tall bookshelf with books arranged in a color gradient, a few ceramic objects as accents, even daylight, straight-on 50mm composition, satisfying organization interior photography, soft glow on key surfaces, harmonious balanced composition." },
  { code: "/deco-bañoplanta", name: "Baño con plantas colgantes", brandSafe: true,
    rubros: ["deco"],
    prompt: "Bathroom with hanging pothos and ferns above a freestanding tub, steam-softened daylight from frosted window, 35mm wide shot, tropical spa bathroom photography, crisp focus with creamy bokeh, high-end production value." },
  { code: "/deco-comedorbanco", name: "Comedor con banco corrido tapizado", brandSafe: true,
    rubros: ["deco"],
    prompt: "Dining nook with upholstered built-in bench, round pedestal table and linen cushions, bay window daylight, 35mm three-quarter shot, cozy banquette interior photography, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/deco-cocinaisla", name: "Cocina con isla central y banquetas", brandSafe: true,
    rubros: ["deco"],
    prompt: "Kitchen with large central island, four leather bar stools and sculptural pendants above, bright open-plan daylight, 24mm wide architectural shot, entertaining-ready kitchen photography, gentle atmospheric haze adds depth, vivid natural color grading." },
];
