// image-styles-rubros/educacion.js — Presets de estilos de imagen: EDUCACIÓN (cursos, capacitación, institutos).
// 40 presets. Formato: { code, name, brandSafe, rubros[], prompt }
// code único global con prefijo '/edu-'. Todos brandSafe: fotografía real que respeta la escena.
'use strict';

module.exports = [
  { code: '/edu-aulavirtual', name: 'Clase online en vivo', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Online class photography: smiling teacher on a large monitor teaching a live virtual lesson, warm ring-light glow on their face, 50mm lens, shallow depth, engaging remote-learning energy.' },
  { code: '/edu-tallerpresencial', name: 'Manos en el taller', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Workshop close-up photography: hands actively working on a hands-on project, tools and materials in frame, bright task lighting, 50mm macro feel, shallow depth, learning-by-doing authenticity.' },
  { code: '/edu-certificado', name: 'Entrega de diploma', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Diploma ceremony photography: graduate receiving a certificate on stage, proud handshake moment, warm stage lighting, 70mm lens, shallow depth, applauding audience blurred behind, achievement and celebration emotion.' },
  { code: '/edu-pizarra', name: 'Pizarra con esquemas', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Whiteboard teaching photography: instructor beside a board filled with clear colorful diagrams, bright classroom light, 35mm lens, crisp legible schemes, marker in hand, knowledge-made-visual clarity.' },
  { code: '/edu-aulamoderna', name: 'Aula luminosa', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Modern classroom photography: bright airy room with students at designer desks, daylight flooding through big windows, 24mm wide-angle, laptops open, collaborative focused learning atmosphere, green plants.' },
  { code: '/edu-docente', name: 'Retrato del docente', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Teacher portrait photography: friendly instructor arms-crossed in a bright classroom, soft window light, 85mm lens, shallow depth of field, bookshelf behind, approachable expert personal brand.' },
  { code: '/edu-grupoestudio', name: 'Grupo de estudio', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Study group photography: students collaborating around a table with notebooks and laptops, warm library light, 35mm lens, genuine interaction, shared notes and open books, community learning vibe.' },
  { code: '/edu-graduacion', name: 'Graduación', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Graduation photography: joyful graduates tossing caps with wide smiles under a bright sky, 35mm lens, frozen motion, confetti in the air, gowns fluttering, triumphant end-of-journey celebration.' },
  { code: '/edu-aprobado', name: 'Festejo de aprobado', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Exam success photography: student celebrating a passed exam with raised arms beside cheering friends, bright daylight, 35mm lens, candid joy, hugs all around, hard-work-pays-off storytelling.' },
  { code: '/edu-biblioteca', name: 'Biblioteca de estudio', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Study library photography: grand reading room with wooden desks and green-shaded lamps, warm tungsten glow, 24mm wide-angle, students deep in books, quiet focused academic atmosphere.' },
  { code: '/edu-laboratorio', name: 'Laboratorio', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Science lab photography: students in goggles conducting a colorful chemistry experiment, bright lab lighting, 50mm lens, bubbling flasks in focus, pipettes and notes, discovery excitement.' },
  { code: '/edu-idiomas', name: 'Clase de idiomas', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Language class photography: small group practicing lively conversation with the teacher, bright classroom, 35mm lens, animated expressions, flashcards on the table, immersive cultural exchange energy.' },
  { code: '/edu-musica', name: 'Clase de música', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Music lesson photography: teacher patiently guiding small hands on piano keys, warm studio light, 50mm lens, shallow depth, sheet music glowing nearby, intimate mentorship moment.' },
  { code: '/edu-cocina', name: 'Curso de cocina', brandSafe: true,
    rubros: ['educacion', 'gastronomia'],
    prompt: 'Cooking class photography: chef instructor demonstrating knife technique to students around a steel counter, bright kitchen light, 35mm lens, steam and action everywhere, delicious learning.' },
  { code: '/edu-deporte', name: 'Clase en cancha', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Sports training photography: coach instructing kids with cones on a sunny field, 70mm lens, frozen action, dust and energy, whistle around neck, grassroots athletic development.' },
  { code: '/edu-arte', name: 'Taller de arte', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Art workshop photography: students painting at easels with paint-splattered hands, bright north light, 35mm lens, palettes full of color, creative mess everywhere, expressive artistic freedom.' },
  { code: '/edu-programacion', name: 'Bootcamp de programación', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Coding bootcamp photography: pair of students programming with code glowing on screens, cool monitor light in a modern room, 35mm lens, sticky notes wall, focused tech-career intensity.' },
  { code: '/edu-webinar', name: 'Webinar en vivo', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Live webinar photography: confident speaker presenting to camera with slides on a monitor behind, professional ring light, 50mm lens, branded backdrop, polished online-event production setup.' },
  { code: '/edu-mentoria', name: 'Mentoría 1 a 1', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'One-on-one mentoring photography: mentor and student reviewing notes over coffee, warm cafe window light, 50mm lens, shallow depth, open notebook, personal guidance warmth and genuine smiles.' },
  { code: '/edu-apuntes', name: 'Apuntes prolijos', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Study notes flat-lay photography: neat curated handwritten notes with highlighters and sticky tabs, top-down composition, soft daylight, 50mm lens, washi tape details, aesthetic study motivation.' },
  { code: '/edu-tablet', name: 'Estudio digital', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Digital study photography: student writing with a stylus on a tablet, glowing screen in a cozy room, warm lamp light, 50mm lens, modern learning tools.' },
  { code: '/edu-diplomamano', name: 'Diploma en manos', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Diploma close-up photography: graduate hands proudly holding a certificate, campus blurred behind in golden light, 50mm lens, shallow depth, rolled diploma with ribbon, tangible achievement.' },
  { code: '/edu-kids', name: 'Clase para chicos', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Kids class photography: young children raising hands eagerly in a colorful classroom, bright cheerful light, 35mm lens, joyful curiosity, crayons and drawings everywhere, playful learning.' },
  { code: '/edu-empresa', name: 'Capacitación in-company', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Corporate training photography: professionals in a modern training room with the facilitator at a screen, bright even light, 24mm wide-angle, notebooks open, serious upskilling atmosphere.' },
  { code: '/edu-plataforma', name: 'Aula virtual', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'E-learning platform photography: laptop showing a sleek course dashboard with progress bars, soft desk-lamp light, 50mm lens, shallow depth, completed lessons checked, learn-anywhere promise delivered.' },
  { code: '/edu-debate', name: 'Debate en clase', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Classroom debate photography: students mid-discussion with raised hands and passionate expressions, teacher moderating from the side, bright daylight through windows, 35mm lens, dynamic exchange of ideas.' },
  { code: '/edu-excursion', name: 'Salida educativa', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Field trip photography: students exploring a museum hall with a guide, dramatic glowing architectural light, 35mm lens, wide-eyed wonder, ancient artifacts, discovery beyond the classroom.' },
  { code: '/edu-feria', name: 'Feria de proyectos', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Science fair photography: student presenting a colorful poster project to curious visitors, bright exhibition hall light, 35mm lens, proud young innovator moment, hands gesturing while explaining.' },
  { code: '/edu-teatro', name: 'Taller de teatro', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Theater workshop photography: young actors rehearsing on stage under a single spotlight, dramatic side light, 70mm lens, expressive gestures frozen mid-scene, creative confidence blooming brightly.' },
  { code: '/edu-danza', name: 'Clase de danza', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Dance class photography: dancers mid-movement in a mirrored studio, motion slightly frozen, bright even light, 50mm lens, pointed toes, grace and discipline, flowing skirts and focused faces.' },
  { code: '/edu-fotografia', name: 'Workshop de fotografía', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Photography workshop photography: student holding a camera at golden hour in a scenic spot, warm backlight flaring the lens, 50mm lens, instructor pointing, learning to see light.' },
  { code: '/edu-emprendedor', name: 'Workshop emprendedor', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Entrepreneurship workshop photography: participants around a whiteboard covered with a business model canvas, bright loft light, 35mm lens, markers in hand, startup energy and ambition.' },
  { code: '/edu-ingreso', name: 'Preingreso universitario', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'University prep photography: focused student surrounded by tall stacks of books studying for entrance exams, warm desk-lamp light, 50mm lens, highlighters everywhere, determined late-night effort.' },
  { code: '/edu-defensa', name: 'Defensa de tesis', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Thesis defense photography: postgraduate presenting slides to an academic panel, formal auditorium light, 50mm lens, laser pointer in hand, years of research, milestone academic achievement.' },
  { code: '/edu-intercambio', name: 'Intercambio estudiantil', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Student exchange photography: young travelers with suitcases gazing at an airport departure board, bright terminal light, 35mm lens, backpacks ready, adventure and new beginnings abroad.' },
  { code: '/edu-acto', name: 'Acto escolar', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'School ceremony photography: students on stage in a grand auditorium during a formal act, warm stage lighting, 70mm lens, flags beside them, institutional pride and tradition.' },
  { code: '/edu-patio', name: 'Patio y recreo', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Schoolyard photography: children playing joyfully in a sunny school patio, 35mm lens, frozen laughter mid-game, bright daylight, balls in the air, happy vivid school-life memories.' },
  { code: '/edu-natacion', name: 'Escuela de natación', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Swimming lesson photography: instructor guiding a smiling child in a bright indoor pool, sparkling blue water, 50mm lens, splashes frozen mid-air, kickboard in hand, safe learning fun.' },
  { code: '/edu-robotica', name: 'Taller de robótica', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Robotics workshop photography: kids assembling small robots with glowing LEDs, cool blue tech lighting, 50mm lens, tiny screwdrivers in hand, concentrated young engineers at work.' },
  { code: '/edu-concierto', name: 'Concierto de alumnos', brandSafe: true,
    rubros: ['educacion'],
    prompt: 'Student concert photography: young musicians performing on stage under warm spotlights, 70mm lens, bows moving in unison, motion and emotion, proud showcase night and applause.' },
];
