// image-styles-rubros/eventos.js — Presets de estilos de imagen: EVENTOS (salones, planners, catering).
// 40 presets. Formato: { code, name, brandSafe, rubros[], prompt }
// code único global con prefijo '/event-'. Todos brandSafe: fotografía real que respeta la escena.
'use strict';

module.exports = [
  { code: '/event-salonarmado', name: 'Salón armado', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Event venue photography: grand ballroom fully dressed before guests arrive, dramatic uplighting washing over drapes, 16mm wide-angle, perfect long-table symmetry, electric anticipation before the celebration.' },
  { code: '/event-mesadulce', name: 'Mesa dulce', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Candy table photography: lavish dessert display with tiered sweets and fresh floral accents, soft warm lighting, 50mm lens, shallow depth, glass jars gleaming, irresistible sweet-table temptation.' },
  { code: '/event-pistallena', name: 'Pista llena', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Packed dance floor photography: huge crowd dancing under sweeping laser lights and falling confetti, 24mm wide-angle, high-energy motion, hands in the air, peak-party euphoria tonight.' },
  { code: '/event-ceremonia', name: 'Ceremonia al aire libre', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Outdoor ceremony photography: flower arch altar with guests seated on white chairs, golden-hour backlight, 70mm lens, couple exchanging vows, petals in the air, emotional once-in-a-lifetime moment.' },
  { code: '/event-novios', name: 'Retrato de novios', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Newlywed portrait photography: couple embracing in a blooming garden at sunset, 85mm lens, dreamy bokeh, golden rim light, veil in the breeze, timeless romantic elegance.' },
  { code: '/event-anillos', name: 'Anillos', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Wedding rings macro photography: gold bands resting on a delicate flower petal, soft window light, 100mm macro lens, razor-sharp engraving detail, shallow depth, timeless symbolic close-up.' },
  { code: '/event-ramo', name: 'Ramo de novia', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Bridal bouquet photography: lush fresh bouquet held against a bright window, soft diffused light, 50mm lens, delicate petals in focus, silk ribbon trailing, floral artistry.' },
  { code: '/event-vestido', name: 'Vestido de novia', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Wedding dress photography: gown hanging by a sunlit window, soft backlight glowing through the fabric, 50mm lens, lace details razor-sharp, ethereal bridal dreams and shoes waiting.' },
  { code: '/event-torta', name: 'Torta de casamiento', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Wedding cake photography: elegant multi-tier cake adorned with fresh flowers, soft spotlight from above, 50mm lens, shallow depth, gold leaf details, edible stunning centerpiece artistry.' },
  { code: '/event-montajemesa', name: 'Mesa servida', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Table setting photography: elegant place settings with candles and crystal glassware, warm ambient light, 50mm lens, folded napkins and menu cards, meticulous detail, dinner-party perfection.' },
  { code: '/event-brindis', name: 'Brindis', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Champagne toast photography: raised crystal glasses catching golden light at midnight, 50mm lens, joyful blurred crowd behind, bubbles rising fast, pure shared celebratory sparkle moment.' },
  { code: '/event-fuegos', name: 'Salida con chispas', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Sparkler exit photography: newlywed couple walking through a tunnel of guests holding sparklers at night, 35mm lens, glowing light trails, cheering faces, magical unforgettable farewell.' },
  { code: '/event-dj', name: 'DJ en cabina', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'DJ booth photography: DJ with headphones on mixing with hands on the decks, dramatic club lighting, 35mm lens, crowd silhouette below, lasers overhead, night-energy command.' },
  { code: '/event-show', name: 'Show en vivo', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Live show photography: rock band performing on a huge stage with dramatic spotlights, 70mm lens, frozen motion, guitarist mid-solo, roaring crowd, concert-scale excitement and pyrotechnics.' },
  { code: '/event-cotillon', name: 'Cotillón', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Party props photography: guests wearing fun cotillon accessories caught mid-laugh, colorful party lights swirling, 35mm lens, oversized glasses and hats, candid festive chaos everywhere tonight.' },
  { code: '/event-quince', name: 'Fiesta de 15', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Quinceanera photography: birthday girl with tiara gleaming twirling in her gown during the waltz, 70mm lens, motion blur on the skirt, proud parents watching, fairy-tale fifteen.' },
  { code: '/event-egresados', name: 'Fiesta de egresados', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Graduation party photography: graduates celebrating with confetti cannons under vibrant nightclub lights, 35mm lens, sashes and wide smiles, friends hugging, unforgettable farewell night, class of 2026.' },
  { code: '/event-corporativo', name: 'Evento corporativo', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Corporate event photography: keynote speaker commanding a branded stage, professional stage lighting, 70mm lens, giant LED screen behind, engaged audience, polished business-event production and applause.' },
  { code: '/event-catering', name: 'Catering en acción', brandSafe: true,
    rubros: ['eventos', 'gastronomia'],
    prompt: 'Catering action photography: chef plating gourmet bites in a busy event kitchen, bright task lighting, 50mm lens, tweezers placing microgreens, precision and steam, behind-the-flavor craft.' },
  { code: '/event-barra', name: 'Barra de tragos', brandSafe: true,
    rubros: ['eventos', 'bar'],
    prompt: 'Cocktail bar photography: skilled bartender flairing bottles before a glowing backlit shelf, moody bar light, 50mm lens, citrus garnish flying, liquid art in motion captured.' },
  { code: '/event-primerbaile', name: 'Primer baile', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'First dance photography: newlywed couple dancing under a single spotlight, 85mm lens, soft spotlight glow, guests watching teary-eyed around them, intimate spotlight romance, dry ice swirling.' },
  { code: '/event-fotocabina', name: 'Cabina de fotos', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Photo booth photography: friends posing with silly props in a neon-lit booth, bright flash look, 35mm lens, strip of prints, spontaneous fun memories and laughter.' },
  { code: '/event-livingsalon', name: 'Livings del salón', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Venue lounge photography: stylish chill-out corner with velvet sofas and low marble tables, warm accent lighting, 35mm lens, guests chatting, relaxed social atmosphere and cocktails.' },
  { code: '/event-jardinnoche', name: 'Jardín de noche', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Garden venue night photography: outdoor space strung with fairy lights, 24mm wide-angle, warm glow against the dark sky, fire pits lit, enchanted evening and music.' },
  { code: '/event-carpa', name: 'Carpa con drapeado', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Event tent photography: elegant draped marquee interior with crystal chandeliers, soft warm light, 16mm wide-angle, round tables fully dressed, grand celebration shelter, dance floor ready.' },
  { code: '/event-bautismo', name: 'Bautismo y comunión', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Baptism celebration photography: white-and-gold decorated table with a delicate cake, soft daylight through windows, 50mm lens, tiny shoes keepsake, proud smiling godparents, tender family milestone.' },
  { code: '/event-cumpleinfantil', name: 'Cumple infantil', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Kids birthday photography: colorful candy-themed decor with a star pinata, bright cheerful light, 35mm lens, birthday kid beaming, friends cheering, pure childhood joy and balloons.' },
  { code: '/event-babyshower', name: 'Baby shower', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Baby shower photography: pastel dessert table with a dreamy balloon garland, soft window light, 50mm lens, mom-to-be glowing, tiny booties decor, sweet anticipation and gifts.' },
  { code: '/event-aniversario', name: 'Bodas de oro', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Golden anniversary photography: elegant gold-accented table celebrating fifty years together, warm candlelight glow, 50mm lens, framed wedding photo as centerpiece, grandchildren around, legacy of love.' },
  { code: '/event-lanzamiento', name: 'Lanzamiento de marca', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Brand launch photography: product reveal on stage with dramatic lighting and bold branding, 50mm lens, curtain dropping, spotlight hitting, high-impact unveiling moment, crowd gasping and applause.' },
  { code: '/event-stand', name: 'Stand en feria', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Expo booth photography: striking trade-show stand with visitors engaging staff, buzzing, bright exhibition light, 24mm wide-angle, bold backlit graphics, samples in hand, brand-presence power today.' },
  { code: '/event-backstage', name: 'Detrás de escena', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Behind-the-scenes photography: event planner with a headset coordinating during setup before doors open, practical work light, 35mm lens, clipboard in hand, crew rushing, the-invisible-work magic.' },
  { code: '/event-invitacion', name: 'Papelería e invitación', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Invitation suite flat-lay photography: elegant calligraphy stationery with a gold wax seal and dried flowers, top-down, soft daylight, 50mm lens, silk ribbon curls, first-impression luxury.' },
  { code: '/event-souvenir', name: 'Souvenirs', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Party favors photography: artful display of personalized souvenirs on a rustic table, warm display lighting, 50mm lens, custom tags tied with twine, take-home memory detail.' },
  { code: '/event-detalledeco', name: 'Detalle de decoración', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Decor detail macro photography: extreme close-up of floral centerpiece textures, soft side light, 100mm macro lens, dew on petals, craftsmanship in every petal and ribbon.' },
  { code: '/event-gettingready', name: 'La previa', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Getting-ready photography: bride laughing during makeup in a bright bridal suite, soft window light, 50mm lens, bridesmaids in robes around her, champagne flutes, joyful pre-ceremony nerves.' },
  { code: '/event-traje', name: 'Traje del novio', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Groom detail photography: navy suit, luxury watch and boutonniere arranged artfully on linen, soft window light, 50mm lens, polished shoes beside, dapper morning preparation ritual.' },
  { code: '/event-auto', name: 'Auto de llegada', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Arrival car photography: classic gleaming vintage car decorated with white ribbons at the venue entrance, golden-hour light, 35mm lens, chauffeur opening the door, grand-entrance statement.' },
  { code: '/event-discurso', name: 'El discurso', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Speech moment photography: emotional best man toasting with a mic, guests laughing in warm light, 70mm lens, couple tearing up, heartfelt celebration emotion and applause.' },
  { code: '/event-cierrefiesta', name: 'Cierre de fiesta', brandSafe: true,
    rubros: ['eventos'],
    prompt: 'Party finale photography: ecstatic late-night crowd with hands up under dramatic strobing lights, 24mm wide-angle, last-song euphoria, confetti raining down, pure electric closing energy tonight.' },
];
