module.exports = [
  { code: "/fit-pesomuerta", name: "Peso muerto en acción", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Athlete mid-deadlift with chalk dust exploding in the air, dramatic side lighting in a dark industrial gym, frozen powerful motion, 85mm lens, shallow depth, intense sports photography." },
  { code: "/fit-clasefuncional", name: "Clase grupal funcional con energía", brandSafe: true,
    rubros: ["fitness"],
    prompt: "High-energy group functional class doing synchronized kettlebell work, coach in front shouting encouragement, bright gym floodlights, 24mm wide dynamic shot, community fitness photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/fit-proteshake", name: "Shake de proteína con ingredientes", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Protein shake in a tall glass surrounded by banana, peanut butter and protein powder scoop on a dark gym counter, backlit steam of freshness, 60mm food-style close shot, appetizing nutrition photography." },
  { code: "/fit-amanecerun", name: "Running al amanecer", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Runner sprinting on an empty riverside path at sunrise, long shadows and golden backlight, low 35mm tracking angle, motion energy, cinematic dawn running photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/fit-entrenadorpt", name: "Entrenamiento personal con coach", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Personal trainer correcting a client's squat form with hands-on guidance, bright modern gym, encouraging eye contact, 50mm medium shot, trust-building coaching photography, clean background separation, professional commercial polish throughout." },
  { code: "/fit-spinningluces", name: "Clase de spinning con luces de neón", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Spin class in a dark studio with neon blue and magenta lights, riders standing on pedals mid-sprint, instructor lit at the front, 35mm wide shot, nightclub-energy cycling photography." },
  { code: "/fit-boxeosaco", name: "Boxeo con saco pesado", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Boxer striking a heavy bag with wraps and gloves, sweat frozen mid-air, dramatic overhead gym light, 85mm tight crop, raw gritty boxing photography, delicate rim light defines edges, refined editorial finish." },
  { code: "/fit-yogasaludo", name: "Yoga: saludo al sol al aire libre", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Group in upward-facing dog pose on mats in a park at golden hour, serene expressions, warm low sunlight, 35mm wide elevated shot, peaceful outdoor yoga photography." },
  { code: "/fit-crossfitwod", name: "WOD de crossfit con cuerda", brandSafe: true,
    rubros: ["fitness"],
    prompt: "CrossFit athlete climbing a thick rope in a warehouse-style box, chalk marks on hands, harsh industrial lighting, low 24mm angle, heroic functional fitness photography, natural vignette draws the eye, authentic documentary feel." },
  { code: "/fit-pilatesreformer", name: "Pilates en reformer", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Woman in controlled lunge on a Pilates reformer machine, calm bright studio with mirrors, soft daylight, 50mm side profile shot, elegant precise Pilates photography, fine detail in highlights and shadows, premium magazine look." },
  { code: "/fit-dominadasbarra", name: "Dominadas en barra con musculación", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Athlete mid-pull-up on a wall-mounted bar, back muscles tensed, dark gym with single spotlight, 85mm tight framing, powerful calisthenics photography, soft glow on key surfaces, harmonious balanced composition." },
  { code: "/fit-kettlebellswing", name: "Kettlebell swing con técnica", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Athlete at the top of a kettlebell swing, hips extended, kettlebell floating at chest height, side-profile 85mm freeze, dramatic gym lighting, explosive strength photography, crisp focus with creamy bokeh, high-end production value." },
  { code: "/fit-natacioncarril", name: "Natación en carril de pileta", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Swimmer mid-freestyle stroke in a lane, water droplets and wake trailing, bright indoor pool lighting, underwater-level 35mm angle, crisp aquatic sports photography, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/fit-ciclismoruta", name: "Ciclismo en ruta de montaña", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Cyclist climbing a winding mountain road at dawn, mist in the valley below, chase-car 35mm perspective, dramatic landscape cycling photography, gentle atmospheric haze adds depth, vivid natural color grading." },
  { code: "/fit-coreplancha", name: "Entrenamiento de core en grupo", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Class holding forearm planks in a row on gym floor, coach walking between them, bright even lighting, 24mm wide low angle, disciplined core-training photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/fit-estiramientofinal", name: "Estiramiento final de la clase", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Group in deep seated hamstring stretch after class, relaxed faces, soft cool-down lighting, 50mm medium wide shot, calm recovery fitness photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/fit-pesasrusas", name: "Fila de pesas rusas en el box", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Row of kettlebells in ascending sizes on a rubber gym floor, athletes training blurred behind, low 35mm angle, moody industrial equipment photography, clean background separation, professional commercial polish throughout." },
  { code: "/fit-correrparque", name: "Grupo corriendo en el parque", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Running crew jogging together through an autumn park, leaves in the air, morning light filtering through trees, 35mm tracking shot, joyful social running photography, delicate rim light defines edges, refined editorial finish." },
  { code: "/fit-squatrack", name: "Sentadilla pesada en el rack", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Athlete at the bottom of a heavy barbell squat inside a power rack, plates loaded, chalk on shoulders, dramatic side light, 85mm tight shot, raw strength photography." },
  { code: "/fit-batallarope", name: "Battle ropes con olas", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Athlete slamming battle ropes creating big waves, ropes frozen mid-motion, dark gym with rim lighting, 85mm low angle, explosive conditioning photography, natural vignette draws the eye, authentic documentary feel." },
  { code: "/fit-hiitburpee", name: "HIIT: burpees al límite", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Group mid-burpee jump in a HIIT class, synchronized airborne moment, bright high-contrast gym lighting, 24mm wide freeze frame, intense interval training photography, fine detail in highlights and shadows, premium magazine look." },
  { code: "/fit-zumbaenergia", name: "Clase de zumba con fiesta", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Zumba class dancing with raised arms and big smiles, colorful studio lighting, instructor on stage, 24mm wide energetic shot, party-like dance fitness photography, soft glow on key surfaces, harmonious balanced composition." },
  { code: "/fit-aquagym", name: "Aquagym en la pileta", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Aquagym class with foam dumbbells in a bright indoor pool, splashing water, instructor at the edge, 35mm elevated shot, fun low-impact fitness photography, crisp focus with creamy bokeh, high-end production value." },
  { code: "/fit-trailrun", name: "Trail running en la montaña", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Trail runner leaping over rocks on a mountain path, dramatic peaks behind, harsh midday sun, 35mm wide action shot, adventurous trail photography, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/fit-calistenia", name: "Calistenia en barras del parque", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Athlete holding a muscle-up on outdoor park bars, urban skyline behind, golden hour rim light, low 24mm angle, street-workout photography, gentle atmospheric haze adds depth, vivid natural color grading." },
  { code: "/fit-pressbanca", name: "Press de banca con spotter", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Athlete pressing a loaded barbell on a bench with a spotter behind, focused effort, dramatic gym spotlight, 85mm tight crop, classic strength photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/fit-remopesado", name: "Remo con barra pesada", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Athlete bent over rowing a heavy barbell, back muscles engaged, chalk dust in dark gym air, 85mm side profile, gritty back-day photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/fit-boxeomitts", name: "Boxeo con manoplas y coach", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Boxer landing a hook on the coach's focus mitts, sharp focus on gloves, blurred gym background, 85mm action freeze, dynamic boxing training photography, clean background separation, professional commercial polish throughout." },
  { code: "/fit-desayunosaludable", name: "Desayuno saludable post entreno", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Overnight oats bowl with berries, chia and honey on a wooden table by a gym bag, soft morning window light, 50mm overhead food shot, fresh post-workout nutrition photography." },
  { code: "/fit-evaluacionfisica", name: "Evaluación física inicial", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Trainer measuring a new member's body composition with calipers in a bright assessment room, clipboard and charts nearby, 50mm medium shot, professional onboarding photography, delicate rim light defines edges, refined editorial finish." },
  { code: "/fit-grupopostclase", name: "Grupo celebrando post clase", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Sweaty happy class group with raised fists after a workout, coach in the middle, bright gym lighting, 24mm wide celebratory shot, community-driven fitness photography, natural vignette draws the eye, authentic documentary feel." },
  { code: "/fit-vestuariogym", name: "Vestuario moderno del gym", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Modern gym locker room with wooden lockers, benches and folded towels, clean architectural lighting, 24mm wide interior shot, premium facility photography, fine detail in highlights and shadows, premium magazine look." },
  { code: "/fit-masajedeportivo", name: "Masaje deportivo de recuperación", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Sports massage therapist working on an athlete's calf in a recovery room, warm dim lighting, 60mm close detail shot, restorative wellness photography, soft glow on key surfaces, harmonious balanced composition." },
  { code: "/fit-hidratacion", name: "Hidratación durante el entreno", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Athlete drinking from a steel bottle mid-workout, water droplets on skin, blurred gym background, 85mm tight portrait, refreshing hydration lifestyle photography, crisp focus with creamy bokeh, high-end production value." },
  { code: "/fit-zonarecuperacion", name: "Zona de recuperación del gym", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Recovery zone with foam rollers, massage guns and stretching mats in soft light, empty and inviting, 35mm wide shot, calm post-workout space photography, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/fit-clasenoche", name: "Clase nocturna con energía", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Evening functional class under bright white lights, city night visible through big windows, athletes mid-circuit, 24mm wide shot, after-work training photography, gentle atmospheric haze adds depth, vivid natural color grading." },
  { code: "/fit-entrenamientopareja", name: "Entrenamiento en pareja", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Couple doing partner medicine-ball throws facing each other across the gym floor, laughing between reps, bright daylight from tall windows, 50mm medium shot, fun relationship-goals fitness photography." },
  { code: "/fit-maratonentreno", name: "Entrenamiento para maratón", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Marathon trainees on a long road run at dawn, pacer with flag ahead, mist over fields, 35mm wide cinematic shot, endurance goal photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/fit-sentadillagoblet", name: "Sentadilla goblet con kettlebell", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Woman holding a kettlebell at chest in a deep goblet squat, perfect form, bright studio lighting, 85mm side freeze, precise technique photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/fit-cuerdasaltar", name: "Salto a la cuerda con ritmo", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Athlete mid double-under with the rope a blur around them, focused eyes, dramatic gym side light, 85mm high-speed freeze, rhythmic conditioning photography, clean background separation, professional commercial polish throughout." },
  { code: "/fit-pesaslibres", name: "Zona de pesas libres vacía al amanecer", brandSafe: true,
    rubros: ["fitness"],
    prompt: "Empty free-weights area with dumbbell racks and benches, first morning light streaming through windows, 24mm wide architectural shot, pristine gym facility photography, delicate rim light defines edges, refined editorial finish." },
];
