module.exports = [
  { code: "/flor-ramonovias", name: "Ramo de novia", brandSafe: true,
    rubros: ["flores"],
    prompt: "Bridal bouquet of white peonies and roses with trailing silk ribbon on a marble table, soft window light, 85mm shallow depth, romantic wedding floristry photography." },
  { code: "/flor-suculentamaceta", name: "Suculentas en macetas", brandSafe: true,
    rubros: ["flores"],
    prompt: "Cluster of echeveria succulents in handmade ceramic pots on a wooden shelf, bright greenhouse light, 60mm close composition, charming succulent-shop photography, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/flor-puestomercado", name: "Puesto de flores en el mercado", brandSafe: true,
    rubros: ["flores"],
    prompt: "Flower market stall overflowing with buckets of colorful blooms, vendor arranging stems, morning market light, 35mm wide vibrant shot, lively florist photography, gentle atmospheric haze adds depth, vivid natural color grading." },
  { code: "/flor-tallerarmado", name: "Florista armando un ramo", brandSafe: true,
    rubros: ["flores"],
    prompt: "Florist's hands wiring a bouquet at a workbench covered in stems and ribbons, petals in the air, bright atelier light, 60mm close shot, artisanal flower-craft photography." },
  { code: "/flor-centromesa", name: "Centro de mesa para boda", brandSafe: true,
    rubros: ["flores"],
    prompt: "Low lush floral centerpiece with candles on a wedding reception table, evening ambient glow, 50mm three-quarter shot, elegant event floristry photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/flor-orquideablanca", name: "Orquídea blanca en maceta", brandSafe: true,
    rubros: ["flores"],
    prompt: "White phalaenopsis orchid in a ceramic pot against a soft neutral wall, delicate side light, 85mm macro detail, refined botanical photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/flor-girasoles", name: "Ramo de girasoles", brandSafe: true,
    rubros: ["flores"],
    prompt: "Bouquet of giant sunflowers wrapped in kraft paper, held against a blue sky, bright sunny backlight, 50mm cheerful shot, joyful sunflower photography, clean background separation, professional commercial polish throughout." },
  { code: "/flor-tulipanes", name: "Tulipanes de colores", brandSafe: true,
    rubros: ["flores"],
    prompt: "Bunches of pink, yellow and red tulips in glass vases on a shop counter, spring daylight, 60mm close composition, fresh spring florist photography, delicate rim light defines edges, refined editorial finish." },
  { code: "/flor-rosasdocena", name: "Docena de rosas rojas", brandSafe: true,
    rubros: ["flores"],
    prompt: "Dozen long-stem red roses in an elegant black box, velvet ribbon, dramatic dark background with spotlight, 85mm luxurious close shot, romantic gift photography, natural vignette draws the eye, authentic documentary feel." },
  { code: "/flor-arreglocumple", name: "Arreglo floral de cumpleaños", brandSafe: true,
    rubros: ["flores"],
    prompt: "Cheerful birthday arrangement with gerberas and balloons in a gift box, confetti around, bright party light, 50mm festive shot, celebratory florist photography, fine detail in highlights and shadows, premium magazine look." },
  { code: "/flor-coronafuneral", name: "Corona floral sobria", brandSafe: true,
    rubros: ["flores"],
    prompt: "Dignified white funeral wreath of lilies and roses on a stand, soft diffused light, muted tones, 50mm respectful composition, solemn sympathy-florist photography, soft glow on key surfaces, harmonious balanced composition." },
  { code: "/flor-plantainterior", name: "Planta de interior en maceta", brandSafe: true,
    rubros: ["flores"],
    prompt: "Fiddle-leaf fig in a woven basket beside a bright window, dust motes in sunbeam, 35mm wide shot, fresh indoor-plant photography, crisp focus with creamy bokeh, high-end production value." },
  { code: "/flor-cactus", name: "Colección de cactus", brandSafe: true,
    rubros: ["flores"],
    prompt: "Assorted cacti in terracotta pots on a sunny windowsill, sharp spines detailed, bright backlight, 60mm close shot, sculptural cactus photography, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/flor-bonsai", name: "Bonsái en exhibición", brandSafe: true,
    rubros: ["flores"],
    prompt: "Ancient-looking bonsai in a shallow ceramic tray on a wooden stand, minimalist backdrop, soft studio light, 85mm contemplative shot, artistic bonsai photography, gentle atmospheric haze adds depth, vivid natural color grading." },
  { code: "/flor-macetaartesanal", name: "Maceta artesanal con planta", brandSafe: true,
    rubros: ["flores"],
    prompt: "Hand-thrown clay pot with a trailing pothos, artisan hands visible glazing nearby, warm workshop light, 60mm close shot, handmade pottery-plant photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/flor-viveropasillo", name: "Pasillo del vivero", brandSafe: true,
    rubros: ["flores"],
    prompt: "Nursery aisle lined with rows of green plants under a glass roof, mist in the air, bright diffused light, 24mm wide perspective shot, immersive garden-center photography." },
  { code: "/flor-semillero", name: "Semillero con brotes", brandSafe: true,
    rubros: ["flores"],
    prompt: "Seedling trays with tiny green sprouts under grow lights, water droplets on leaves, 60mm macro close shot, hopeful germination photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/flor-huertourbano", name: "Huerta urbana en cajones", brandSafe: true,
    rubros: ["flores"],
    prompt: "Urban vegetable garden in wooden raised beds with tomatoes and herbs, gardener harvesting, golden hour light, 35mm wide shot, wholesome urban-farming photography, clean background separation, professional commercial polish throughout." },
  { code: "/flor-ramoviernes", name: "Ramo fresco de la semana", brandSafe: true,
    rubros: ["flores"],
    prompt: "Florist holding a fresh mixed seasonal bouquet toward the camera, shop blooms blurred behind, bright daylight, 50mm medium shot, inviting weekly-bouquet photography, delicate rim light defines edges, refined editorial finish." },
  { code: "/flor-bodadeco", name: "Decoración floral de boda", brandSafe: true,
    rubros: ["flores"],
    prompt: "Ceremony arch covered in blush roses and greenery, couple blurred beneath, soft outdoor light, 35mm wide shot, dreamy wedding-floristry photography, natural vignette draws the eye, authentic documentary feel." },
  { code: "/flor-peonias", name: "Peonías de primavera", brandSafe: true,
    rubros: ["flores"],
    prompt: "Lush pink peonies in full bloom in a glass vase, petals soft and layered, gentle window light, 85mm shallow close shot, luxurious peony photography, fine detail in highlights and shadows, premium magazine look." },
  { code: "/flor-lavanda", name: "Campo de lavanda", brandSafe: true,
    rubros: ["flores"],
    prompt: "Rows of purple lavender stretching to the horizon at sunset, bees hovering, warm low light, 35mm wide landscape shot, fragrant lavender-field photography, soft glow on key surfaces, harmonious balanced composition." },
  { code: "/flor-cajaregalo", name: "Caja de regalo floral", brandSafe: true,
    rubros: ["flores"],
    prompt: "Hat box filled with fresh roses and eucalyptus, ribbon and gift card attached, bright studio light, 60mm close shot, premium floral-gift photography, crisp focus with creamy bokeh, high-end production value." },
  { code: "/flor-globoyflores", name: "Globo con flores para festejo", brandSafe: true,
    rubros: ["flores"],
    prompt: "Clear balloon filled with small flowers floating above a gift box of blooms, festive bright light, 50mm playful shot, trendy celebration photography, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/flor-sansevieria", name: "Sansevieria en maceta nórdica", brandSafe: true,
    rubros: ["flores"],
    prompt: "Tall snake plant in a minimalist white pot against a bright wall, strong graphic leaves, clean daylight, 50mm straight-on shot, modern houseplant photography, gentle atmospheric haze adds depth, vivid natural color grading." },
  { code: "/flor-monstera", name: "Monstera deliciosa", brandSafe: true,
    rubros: ["flores"],
    prompt: "Monstera deliciosa with dramatic split leaves in a handmade ceramic planter, dappled window light across the foliage, 50mm close composition, iconic tropical-plant photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/flor-hortensia", name: "Hortensias en florero", brandSafe: true,
    rubros: ["flores"],
    prompt: "Blue hydrangea heads overflowing in a vintage cut-glass vase, soft morning daylight from the side, 85mm shallow close shot, romantic hydrangea photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/flor-claveles", name: "Claveles de colores vivos", brandSafe: true,
    rubros: ["flores"],
    prompt: "Vivid carnations in red, pink and white bunched in paper cones at a stall, bright market light, 60mm close shot, cheerful carnation photography, clean background separation, professional commercial polish throughout." },
  { code: "/flor-margaritas", name: "Margaritas silvestres", brandSafe: true,
    rubros: ["flores"],
    prompt: "Wild daisies in a mason jar on a rustic table, meadow blurred behind, soft natural light, 60mm close shot, simple country-flower photography, delicate rim light defines edges, refined editorial finish." },
  { code: "/flor-florerohogar", name: "Florero con flores frescas en casa", brandSafe: true,
    rubros: ["flores"],
    prompt: "Fresh mixed bouquet in a glass vase on a home sideboard, morning light streaming in, 50mm lifestyle shot, welcoming home-florist photography, natural vignette draws the eye, authentic documentary feel." },
  { code: "/flor-jardinvertical", name: "Jardín vertical instalado", brandSafe: true,
    rubros: ["flores"],
    prompt: "Lush vertical garden wall with ferns and philodendrons in a modern lobby, integrated grow lights, 24mm wide shot, impressive green-wall photography, fine detail in highlights and shadows, premium magazine look." },
  { code: "/flor-terrario", name: "Terrario de vidrio", brandSafe: true,
    rubros: ["flores"],
    prompt: "Glass terrarium with layered moss, tiny ferns and stones, miniature world inside, soft diffused light, 60mm macro close shot, enchanting terrarium photography, soft glow on key surfaces, harmonious balanced composition." },
  { code: "/flor-plantacolgar", name: "Planta colgante en macramé", brandSafe: true,
    rubros: ["flores"],
    prompt: "Trailing pothos in a macramé hanger by a bright window, leaves cascading down, soft backlight, 50mm vertical shot, boho hanging-plant photography, crisp focus with creamy bokeh, high-end production value." },
  { code: "/flor-ramootoñal", name: "Ramo otoñal", brandSafe: true,
    rubros: ["flores"],
    prompt: "Autumn bouquet with dahlias, wheat and dried leaves in warm tones, rustic wrap, golden side light, 60mm close shot, cozy fall-florist photography, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/flor-arreglonavidad", name: "Arreglo navideño", brandSafe: true,
    rubros: ["flores"],
    prompt: "Christmas arrangement with red amaryllis, pine branches and gold accents, fairy lights glowing, warm festive light, 60mm close shot, magical holiday photography, gentle atmospheric haze adds depth, vivid natural color grading." },
  { code: "/flor-sanvalentin", name: "Ramo de San Valentín", brandSafe: true,
    rubros: ["flores"],
    prompt: "Valentine bouquet of red roses and baby's breath with a heart card, romantic dim lighting, 85mm shallow close shot, passionate Valentine photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/flor-diamadre", name: "Ramo para el Día de la Madre", brandSafe: true,
    rubros: ["flores"],
    prompt: "Mother's Day bouquet of pastel roses and lilies in a keepsake vase, handwritten card beside, soft morning light, 60mm tender shot, heartfelt gift photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/flor-suscripcion", name: "Suscripción semanal de flores", brandSafe: true,
    rubros: ["flores"],
    prompt: "Delivery person handing a fresh weekly bouquet at a doorstep, smiling recipient, bright daylight, 50mm lifestyle shot, convenient flower-subscription photography, clean background separation, professional commercial polish throughout." },
  { code: "/flor-tallerfloral", name: "Taller floral para clientes", brandSafe: true,
    rubros: ["flores"],
    prompt: "Flower-arranging workshop with participants crafting bouquets at a long table, petals everywhere, bright atelier light, 35mm wide shot, joyful floral-class photography, delicate rim light defines edges, refined editorial finish." },
  { code: "/flor-enramada", name: "Enramada de entrada con flores", brandSafe: true,
    rubros: ["flores"],
    prompt: "Flower shop entrance framed by a lush overhead floral garland installation, customers walking beneath it, bright daylight, 24mm wide shot, showstopping storefront photography, natural vignette draws the eye, authentic documentary feel." },
];
