module.exports = [
  { code: '/foto-quinceanera', name: 'Sesión de 15', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Elegant quinceañera portrait session in a golden wheat field: flowing gown catching warm sunset backlight, dreamy rim light in her hair, shot on 85mm f/1.4 with creamy bokeh, soft lens flare, timeless celebration magic, cinematic warm color grade." },
  { code: '/foto-newborn', name: 'Bebé recién nacido', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Newborn photography session in a softly lit nursery: tiny baby swaddled in cream knit wrap, sleeping on a neutral linen backdrop, diffused window light from the side, 50mm macro detail of little fingers, airy pastel tones, pure tender calm." },
  { code: '/foto-bodacivil', name: 'Boda civil', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Civil wedding ceremony portrait: couple exchanging rings before a judge in a bright modern registry office, soft daylight through tall windows, 35mm documentary framing capturing genuine laughter, shallow depth of field, elegant minimalist celebration, true-to-life colors." },
  { code: '/foto-bodareligiosa', name: 'Boda religiosa', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Religious wedding ceremony inside a historic church: couple at the altar under warm stained-glass light, candles glowing softly, 24-70mm capturing the grand architecture and intimate vows, reverent atmosphere, rich golden tones, timeless sacred emotion." },
  { code: '/foto-preboda', name: 'Preboda', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Pre-wedding couple session at blue hour on a city rooftop: laughing together with skyline lights behind, cool twilight mixed with warm string lights, 50mm f/1.8 intimate framing, motion in her dress, romantic save-the-date energy, soft cinematic grade." },
  { code: '/foto-postboda', name: 'Trash the dress', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Trash-the-dress session on a wild beach at sunset: bride spinning in her gown as waves crash around her, dramatic golden backlight and sea spray, 35mm wide dynamic composition, joyful fearless energy, saturated warm tones, epic editorial finish." },
  { code: '/foto-propuesta', name: 'Propuesta de matrimonio', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Surprise proposal moment at golden hour in a flower garden: partner kneeling with ring box open, genuine shock and tears, 70-200mm telephoto capturing the emotion from afar, warm backlight glow, petals in soft focus foreground, unforgettable romantic storytelling." },
  { code: '/foto-maternidad', name: 'Sesión de maternidad', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Maternity portrait in a blooming meadow at sunset: expectant mother in flowing fabric cradling her belly, golden backlight outlining her silhouette, 85mm dreamy bokeh, wind lifting the dress, serene powerful femininity, warm film-like tones." },
  { code: '/foto-maternidadplaya', name: 'Maternidad en la playa', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Beach maternity session at low tide: mother-to-be walking along wet reflective sand, pastel sunset sky mirrored below, 50mm natural framing, soft ocean breeze in her hair, peaceful anticipation, gentle pastel color palette, timeless coastal elegance." },
  { code: '/foto-maternidadestudio', name: 'Maternidad en estudio', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Studio maternity portrait on seamless warm-gray backdrop: dramatic side lighting sculpting the baby bump, sheer fabric drape, 85mm classic fine-art composition, deep shadows with soft fill, elegant timeless black-and-gold mood, gallery-worthy simplicity." },
  { code: '/foto-familiacampo', name: 'Familia en el campo', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Family session in a sunlit countryside field: parents and kids laughing mid-run through tall grass, warm late-afternoon backlight, 35mm lifestyle framing with natural motion, genuine connection, golden nostalgic tones, joyful authentic family storytelling." },
  { code: '/foto-familiaplaya', name: 'Familia en la playa', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Beach family session at golden hour: family splashing at the shoreline, kids lifted into the air laughing, warm sunset glow on wet sand, 35mm candid wide composition, carefree summer joy, vibrant natural colors, playful energy frozen in motion." },
  { code: '/foto-familianavidad', name: 'Familia navideña', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Christmas family portrait by a decorated tree: matching cozy sweaters, warm fireplace glow mixed with twinkling tree lights, 50mm intimate framing, genuine smiles and cuddles, rich festive reds and golds, heartwarming holiday card perfection." },
  { code: '/foto-navidadestudio', name: 'Mini sesión navideña', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Holiday mini session in studio: child peeking from a giant gift box with fairy lights, soft diffused key light, 85mm shallow depth of field, sparkling bokeh background, whimsical Christmas magic, clean bright festive tones, adorable seasonal portrait." },
  { code: '/foto-graduacion', name: 'Graduación', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Graduation portrait on a university campus: graduate tossing cap in the air, historic building softly blurred behind, bright midday light with open shade, 50mm celebratory framing, confetti frozen mid-flight, proud accomplished joy, crisp vibrant colors." },
  { code: '/foto-pareja', name: 'Sesión de pareja', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Couple session in a sun-drenched olive grove: partners forehead to forehead laughing, dappled light filtering through leaves, 85mm romantic close framing, gentle lens flare, tender intimacy, warm Mediterranean tones, effortless love-story elegance." },
  { code: '/foto-aniversario', name: 'Aniversario de bodas', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Anniversary portrait of a long-married couple on their porch at dusk: holding hands with knowing smiles, warm string lights glowing behind, 50mm nostalgic framing, soft blue-hour ambient light, enduring love, cozy cinematic warmth, timeless devotion." },
  { code: '/foto-boudoir', name: 'Sesión boudoir', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Elegant boudoir session in a sunlit bedroom: soft window light draping across silk sheets, tasteful artistic composition with deep shadows, 85mm intimate framing, confident feminine energy, muted warm tones, fine-art sensuality, empowering timeless beauty." },
  { code: '/foto-corporativo', name: 'Retrato corporativo', brandSafe: true,
    rubros: ['fotografia', 'profesionales'],
    prompt: "Corporate executive portrait in a modern office: confident stance against floor-to-ceiling windows, soft diffused daylight with subtle fill, 85mm professional headshot framing, sharp focus on eyes, clean neutral background, trustworthy leadership presence, polished editorial finish." },
  { code: '/foto-linkedin', name: 'Headshot profesional', brandSafe: true,
    rubros: ['fotografia', 'profesionales'],
    prompt: "Professional LinkedIn headshot with clean gray studio backdrop: soft key light with gentle rim separation, 85mm flattering compression, relaxed confident expression, crisp business attire, neutral modern tones, approachable executive polish, razor-sharp detail." },
  { code: '/foto-mascotas', name: 'Sesión con mascotas', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Pet photography session in a bright park: happy dog mid-leap catching a frisbee, owner laughing in soft-focus background, fast shutter freezing motion, 70-200mm at golden hour, warm playful energy, vibrant joyful colors, pure furry happiness." },
  { code: '/foto-cumpleinfantil', name: 'Cumple infantil', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Kids birthday party session: child blowing out candles on a colorful cake, friends cheering around, warm indoor party lights with bokeh, 35mm lively documentary framing, pure childhood delight, vivid festive colors, candid celebration magic." },
  { code: '/foto-smashcake', name: 'Smash cake primer año', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "First-birthday smash cake session: baby gleefully smashing a pastel cake, frosting everywhere, soft studio light with airy backdrop, 50mm playful framing, infectious giggles, bright cheerful pastels, adorable messy milestone, heart-melting cuteness." },
  { code: '/foto-bautismo', name: 'Bautismo', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Baptism ceremony in a softly lit chapel: baby in white gown held over the font, gentle window light with candle warmth, 50mm reverent framing, family watching tenderly, peaceful sacred whites and golds, timeless spiritual family moment." },
  { code: '/foto-comunion', name: 'Primera comunión', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "First communion portrait in a sunlit church garden: child in white dress holding flowers, soft morning light through trees, 85mm serene framing, innocent joyful expression, delicate whites and greens, pure milestone elegance, timeless keepsake portrait." },
  { code: '/foto-babyshower', name: 'Baby shower', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Baby shower celebration in a pastel-decorated garden: mom-to-be laughing with friends under string lights, soft late-afternoon glow, 35mm joyful documentary framing, balloons and gifts in bokeh, sweet anticipation, dreamy pastel tones, warm friendship." },
  { code: '/foto-gemelos', name: 'Sesión de gemelos', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Twin newborn session on a cozy knit blanket: two babies nestled side by side in matching wraps, soft diffused window light, 50mm symmetrical composition, tiny hands touching, double the tenderness, airy neutral tones, heartwarming miracle portrait." },
  { code: '/foto-deportiva', name: 'Retrato deportivo', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Athletic portrait on a track at dawn: runner mid-stride with dramatic low sun backlight, dust kicked up glowing, 70-200mm dynamic telephoto framing, powerful determined expression, gritty cinematic contrast, bold saturated energy, inspiring sports editorial." },
  { code: '/foto-bailarina', name: 'Retrato de bailarina', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Ballerina portrait in an empty theater: dancer mid-arabesque under a single dramatic spotlight, dark background with dust particles glowing, 85mm graceful framing, elegant strength frozen, chiaroscuro artistry, timeless dance elegance, fine-art drama." },
  { code: '/foto-musico', name: 'Retrato de músico', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Musician portrait in a moody recording studio: artist with guitar under warm tungsten practicals, soft haze in the air, 50mm intimate framing, creative intensity in the eyes, rich amber tones with deep shadows, authentic artistic soul." },
  { code: '/foto-chef', name: 'Retrato de chef', brandSafe: true,
    rubros: ['fotografia', 'otro'],
    prompt: "Chef portrait in a bustling kitchen: chef plating a dish with focused precision, warm pass lights glowing, 50mm shallow depth of field, steam rising softly, passionate craftsmanship, rich warm tones, culinary artistry, appetizing editorial mood." },
  { code: '/foto-tatuador', name: 'Retrato de tatuador', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Tattoo artist portrait in a neon-lit studio: artist working with machine under dramatic colored light, ink details sharp, 50mm edgy framing, focused creative intensity, moody magenta and cyan tones, bold underground artistry, striking contemporary portrait." },
  { code: '/foto-escritor', name: 'Retrato de autor', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Author portrait in a cozy book-lined study: writer at a vintage desk with morning window light, 50mm thoughtful framing, pen paused mid-thought, warm literary atmosphere, rich browns and golds, intellectual creative calm, timeless storyteller portrait." },
  { code: '/foto-editorial', name: 'Editorial de moda', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Fashion editorial session in brutalist concrete architecture: model in avant-garde outfit, harsh midday sun creating graphic shadows, 35mm bold wide composition, striking pose, high-contrast monochrome-leaning grade, fearless high-fashion energy, magazine-cover drama." },
  { code: '/foto-surf', name: 'Sesión de surf', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Surf lifestyle session at sunrise: surfer walking with board into glowing waves, golden backlight and ocean spray, 70-200mm telephoto compression, salt and freedom in the air, warm cinematic tones, adventurous coastal spirit, epic ocean energy." },
  { code: '/foto-motoclasica', name: 'Retrato con moto clásica', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Portrait with a vintage motorcycle on an empty desert road: rider leaning on chrome at golden hour, long shadows stretching, 50mm nostalgic framing, rebellious free spirit, warm retro film tones, timeless road adventure, cinematic Americana mood." },
  { code: '/foto-otono', name: 'Mini sesión de otoño', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Autumn mini session in a golden forest: family among falling leaves, warm low sun filtering through amber canopy, 85mm cozy framing, leaves tossed in the air laughing, rich orange and gold palette, nostalgic fall magic, heartwarming seasonal portrait." },
  { code: '/foto-newbornpadres', name: 'Recién nacido con papás', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Newborn session with parents in a bright bedroom: parents cradling tiny baby in soft morning window light, 50mm tender lifestyle framing, foreheads touching, overwhelming new love, airy whites and creams, intimate family beginning, pure emotional warmth." },
  { code: '/foto-quinceurbana', name: '15 en la ciudad', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Quinceanera session in a vibrant city street: elegant gown contrasting colorful murals, late-afternoon sun with urban glow, 35mm dynamic editorial framing, confident joyful twirl, bold saturated colors, modern celebration energy, striking urban fairytale." },
  { code: '/foto-senior', name: 'Retrato senior', brandSafe: true,
    rubros: ['fotografia'],
    prompt: "Senior year portrait on a college campus quad: graduate in gown laughing with friends at sunset, warm backlight and historic arches, 50mm celebratory framing, bright future energy, vivid joyful colors, proud milestone moment, unforgettable graduation glow." },
];
