module.exports = [
  { code: '/gastro-parrilla', name: 'Parrilla con brasas', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Sizzling grill photography: thick vacío steak over glowing red embers, sparks rising into dark smoky air, extreme close-up of glistening fat and charred crust, firelight raking across the meat, a hand with a knife mid-cut slicing the meat, juices flowing, shallow depth of field.' },
  { code: '/gastro-pizzahorno', name: 'Pizza del horno de barro', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Wood-fired oven pizza photography: margherita sliding out on a long wooden peel, flames licking the clay dome behind it, leopard-spotted crust glowing in firelight, flour dust in the air, dramatic side angle.' },
  { code: '/gastro-pizzaqueso', name: 'Pull de queso de la pizza', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Cheese-pull pizza photography: slice lifted high with long molten mozzarella strands stretching, tomato sauce and basil visible, warm backlight making the cheese glow, tight 50mm framing, rustic wooden table.' },
  { code: '/gastro-empanadarepulgue', name: 'Macro del repulgue', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Macro photography of an empanada repulgue: golden braided edge in extreme close-up, flaky layers and toasted spots razor sharp, soft warm side light, shallow depth of field blurring the empanada body behind.' },
  { code: '/gastro-empanadashorno', name: 'Bandeja de empanadas del horno', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Bakery tray photography: dozen golden empanadas on a dark metal tray fresh from the oven, heat shimmer rising, warm oven glow from behind, steam catching the light, rustic overhead three-quarter angle.' },
  { code: '/gastro-milanesacorte', name: 'Corte de milanesa napolitana', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Cross-section food photography: milanesa napolitana sliced open, molten cheese oozing between crispy breaded layers, tomato sauce dripping, knife mid-cut through the crispy layers, cheese stretching in motion, extreme macro on the flowing cheese, warm appetizing side light.' },
  { code: '/gastro-choripan', name: 'Choripán con chimichurri', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Street food photography: choripán on crusty baguette, grilled chorizo split open, chimichurri dripping down the sides, served on brown kraft paper, rustic wooden table, hard midday sunlight with strong shadows.' },
  { code: '/gastro-matambre', name: 'Matambre arrollado', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Argentine matambre photography: rolled matambre slices fanned on a wooden board, egg yolk and red pepper spirals visible in each slice, parsley garnish, warm directional light, dark rustic background.' },
  { code: '/gastro-provoletahierro', name: 'Provoleta en hierro', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Sizzling provoleta photography: bubbling provolone cheese in a black cast-iron skillet, oregano and chili flakes on top, cheese stretching as a fork lifts a piece, dramatic dark background, warm spotlight.' },
  { code: '/gastro-ollapopular', name: 'Guiso en olla de barro', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Rustic stew photography: clay pot of steaming guiso, wooden spoon lifting a hearty ladle, chunks of meat and vegetables visible, steam backlit by window light, dark moody kitchen background.' },
  { code: '/gastro-locro', name: 'Locro patrio', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Traditional locro photography: earthenware bowl of steaming locro topped with red paprika oil swirl, corn and beans visible, rustic table with checkered cloth, warm nostalgic light, patriotic comfort mood.' },
  { code: '/gastro-humita', name: 'Humita en chala', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Humita en chala photography: corn husk opened to reveal creamy humita with melted cheese stretching, grilled corn kernels on top, rustic wooden surface, warm golden side light, steam rising.' },
  { code: '/gastro-pastacasera', name: 'Fettuccine caseros', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Fresh pasta photography: nests of handmade fettuccine dusted with flour, hands tossing pasta in the background, strands catching warm window light, shallow depth of field, artisanal kitchen mood.' },
  { code: '/gastro-noquis', name: 'Ñoquis con tuco', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Ñoquis photography: steaming plate of potato gnocchi in rich tuco sauce, fresh basil leaves, parmesan snowing down from above, warm cozy light, rustic ceramic plate on dark wood.' },
  { code: '/gastro-raviolmanteca', name: 'Ravioles en manteca de salvia', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Ravioli photography: ricotta ravioli glistening in melted sage butter, crispy sage leaves on top, parmesan shavings, extreme close-up on the silky sauce coating each piece, warm side light.' },
  { code: '/gastro-risottohongos', name: 'Risotto de hongos', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Creamy mushroom risotto photography: spoon lifting a rich wave of risotto, parmesan raining down, sautéed mushrooms on top, steam rising, warm overhead light on a dark slate background.' },
  { code: '/gastro-lasagna', name: 'Lasagna en corte', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Lasagna cross-section photography: tall slice revealing distinct layers of pasta, ragù and béchamel, golden gratin top, cheese pull at the cut, warm oven light, rustic Italian trattoria mood.' },
  { code: '/gastro-sushitabla', name: 'Tabla de sushi cenital', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Overhead sushi board photography: precise rows of nigiri and rolls on dark slate, pickled ginger and wasabi accents, soy dish, chopsticks, dramatic top-down composition with moody side light.' },
  { code: '/gastro-pescadoplancha', name: 'Pescado a la plancha', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Grilled fish photography: sea bass fillet with crispy golden skin, charred lemon half and rosemary sprigs, grill marks visible, lemon juice mid-squeeze, bright fresh light on dark ceramic.' },
  { code: '/gastro-salmonrosado', name: 'Salmón rosado', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Salmon fillet photography: coral-pink salmon steak with crispy skin, cross-section showing juicy flesh, dill and lemon, macro detail on the flaky texture, fresh daylight, minimalist plating.' },
  { code: '/gastro-ceviche', name: 'Ceviche en vaso', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Ceviche photography: transparent glass of sea bass ceviche in leche de tigre, red onion and cilantro visible, cancha corn on the side, bright citrusy light, fresh coastal mood, shallow depth of field.' },
  { code: '/gastro-rabas', name: 'Rabas con limón', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Fried calamari photography: golden crispy rabas piled in a metal basket, lemon wedges and alioli dipping bowl, paper lining, crunchy texture in macro detail, bright casual light, seaside cantina vibe.' },
  { code: '/gastro-cazuelamariscos', name: 'Cazuela de mariscos', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Seafood casserole photography: bubbling clay cazuela of mussels, shrimp and calamari in rich broth, steam rising, crusty bread for dipping beside it, warm tavern light, rustic overhead angle.' },
  { code: '/gastro-paella', name: 'Paella cenital', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Overhead paella photography: wide paellera with saffron rice, prawns, mussels and lemon wedges arranged in a ring, peas scattered, vibrant yellow tones, bright daylight, festive Spanish table.' },
  { code: '/gastro-lomito', name: 'Lomito completo', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Lomito completo photography: towering sandwich with grilled lomo, fried egg, ham, cheese and lettuce spilling out, golden fries beside it, cross-section hero angle, warm appetizing diner light.' },
  { code: '/gastro-hamburguesasmash', name: 'Hamburguesa smash', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Smash burger macro photography: double smashed patties with molten cheddar dripping, caramelized onions, glossy brioche bun, extreme close-up on the cheese cascade, dark background, dramatic side light.' },
  { code: '/gastro-sandwichmiga', name: 'Sándwiches de miga', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Miga sandwich photography: triangular sandwiches stacked on a white platter, visible layers of ham, cheese, egg and lettuce, crustless white bread, bright clean light, classic Argentine catering look.' },
  { code: '/gastro-superpancho', name: 'Súper pancho cargado', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Loaded hot dog photography: grilled sausage in a soft bun buried under crispy potato sticks, three sauce drizzles zigzagging on top, ketchup and mustard, playful overhead angle, vibrant street-food colors.' },
  { code: '/gastro-wrap', name: 'Wrap partido', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Wrap cross-section photography: grilled tortilla sliced diagonally revealing colorful layers of chicken, avocado, tomato and lettuce, filling spilling slightly, bright fresh light, clean modern fast-casual styling.' },
  { code: '/gastro-papascono', name: 'Papas en cono con salsas', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Loaded fries photography: paper cone overflowing with golden fries, three sauce cups of cheddar, spicy mayo and barbecue, cheese dripping down, playful 45-degree angle, bright appetizing light.' },
  { code: '/gastro-picada', name: 'Picada argentina', brandSafe: true,
    rubros: ['gastronomia', 'bar'],
    prompt: 'Argentine picada photography: large wooden board with sliced salami, cheeses, olives, nuts and bread, abundant generous arrangement, warm bar light, overhead angle, perfect for sharing.' },
  { code: '/gastro-tortilla', name: 'Tortilla de papas', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Tortilla de papas photography: thick wedge revealing layers of potato and caramelized onion, golden crispy exterior, egg glistening at the cut, rustic ceramic plate, warm Spanish tavern light.' },
  { code: '/gastro-tartaverdura', name: 'Tarta de verduras', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Vegetable tart photography: golden flaky crust tart with roasted zucchini, peppers and goat cheese, slice lifted showing the filling, fresh herbs, bright natural light, homemade bakery mood.' },
  { code: '/gastro-ensaladafresca', name: 'Ensalada fresca', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Fresh salad macro photography: vibrant greens with water droplets glistening, cherry tomatoes, avocado and seeds, extreme close-up on the dewy leaves, bright crisp daylight, healthy fresh mood.' },
  { code: '/gastro-wokfuego', name: 'Wok al fuego', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Wok fire photography: chef tossing noodles and vegetables through tall leaping flames, ingredients frozen mid-air, sparks and fire glow, dark kitchen background, dramatic high-speed capture.' },
  { code: '/gastro-bondiola', name: 'Bondiola braseada', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Slow-braised bondiola photography: shredded pork glistening with dark glaze, pulled apart with a fork, caramelized edges in macro detail, rustic wooden board, warm smoky light, comfort-food mood.' },
  { code: '/gastro-polloasador', name: 'Pollo al asador', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Rotisserie chicken photography: whole golden chicken on the spit, crispy skin glistening, juices dripping, flames blurred behind, extreme close-up on the crackling skin, warm firelight.' },
  { code: '/gastro-flan', name: 'Flan con dulce de leche', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Flan photography: silky flan slice with amber caramel cascading down, generous dulce de leche spoonful beside it, glossy surface catching warm light, extreme macro on the dripping caramel.' },
  { code: '/gastro-chocotorta', name: 'Chocotorta', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Chocotorta slice photography: tall slice revealing distinct chocolate cookie and dulce de leche layers, cocoa dusted on top, creamy texture at the cut, warm cozy light, nostalgic Argentine dessert mood.' },
  { code: '/gastro-heladoartesanal', name: 'Helado artesanal', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Artisan gelato photography: scoops of dulce de leche and chocolate in a waffle cone, melted chocolate drizzling down, crushed nuts, extreme close-up on the creamy texture, bright summer light.' },
  { code: '/gastro-povplancha', name: 'POV silencioso en la cocina', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'First-person POV from the cook\'s own eyes: two spatulas flipping sizzling smash patties on a smoking flat-top griddle, steam rising toward the lens, cheese slices melting down over the meat, hands toasting buns on the same griddle, raw unpolished process energy, warm kitchen light, no face visible, candid documentary feel, upper third clean and softly blurred for a headline.' },
  { code: '/gastro-cartelpromo', name: 'Plato insignia con precio en titular', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Hero food photography of an abundant Argentine parrillada spread, dramatic warm light, generous overflowing mood, composed with a large clean softly-blurred upper third of dark negative space reserved for a bold price headline added later, dish sharp and appetizing in the lower two thirds.' },
  { code: '/gastro-platoitemizado', name: 'Parrillada itemizada', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Overhead shot of a generous Argentine parrillada on rustic wood, every cut clearly visible and separated (chinchulines, rinoncitos, chorizo, morcilla, vacio), warm tavern light, abundant generous mood, clean calm margins on the left side reserved for an itemized list headline added later.' },
  { code: '/gastro-cocineroacara', name: 'Cocinero a cámara en acción', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Argentine cook mid-action talking straight to camera with energy, visible face, stained apron with the house identity, tongs in hand over live fire and glowing coals behind, flames and sparks, warm firelight on the face, candid unposed energy, upper third clean for an on-screen hook headline added later.' },
  { code: '/gastro-historialocal', name: 'La historia del local', brandSafe: true,
    rubros: ['gastronomia'],
    prompt: 'Documentary photograph of a neighborhood Argentine restaurant: the owners (parrillero at the grill, moza carrying plates) mid-service, warm dining room with regulars at tables, lived-in authentic atmosphere, no staging, upper third softly blurred for a headline.' },
];
