module.exports = [
  { code: '/hogar-pinturapared', name: 'Pared recién pintada', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Paint roller laying a perfect stripe of fresh color on a wall, crisp tape line edge, bright natural window light, close action composition, the most satisfying home upgrade.' },
  { code: '/hogar-cocinarenovada', name: 'Cocina renovada', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Newly renovated kitchen with shaker cabinets, stone countertop and brass fixtures, soft morning light through the window, wide inviting composition, the heart of the home reborn.' },
  { code: '/hogar-pisoflotante', name: 'Piso flotante', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Installer clicking laminate planks into place, rubber mallet mid-tap, bright room light across the new floor, low-angle process composition, warm wood tones transforming the space.' },
  { code: '/hogar-banorenovado', name: 'Baño renovado', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Newly renovated bathroom with large-format tiles, floating vanity and rainfall shower head, soft spa-like lighting, wide serene composition, a private daily retreat to unwind at home.' },
  { code: '/hogar-microcemento', name: 'Microcemento', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Craftsman troweling smooth microcement across a bathroom wall, the wet sheen catching dramatic side light, close texture composition, seamless modern surfaces taking elegant form by hand.' },
  { code: '/hogar-durlock', name: 'Tabique de durlock', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Drywall sheets being screwed onto galvanized metal framing, drill driver in action, bright construction lighting, dynamic process composition, brand-new rooms appearing from open space in hours.' },
  { code: '/hogar-revoque', name: 'Revoque perfecto', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Plasterer steel trowel smoothing fresh render across a wall, the flawless surface catching dramatic raking light, close craft composition, the invisible art behind every perfect paint job.' },
  { code: '/hogar-ceramica', name: 'Cerámica colocada', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Tiler setting ceramic tiles with plastic spacers in a perfect grid, notched trowel and adhesive within reach, bright work lighting, top-down precision composition, geometry you can walk on.' },
  { code: '/hogar-porcelanato', name: 'Porcelanato gran formato', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Huge porcelain slabs being laid across a living room floor, suction cups and long levels in use, bright natural daylight, wide luxurious composition, stone elegance without the quarry price.' },
  { code: '/hogar-parquet', name: 'Parquet de madera', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Hardwood parquet blocks arranged in a herringbone pattern, installer tapping the final piece into place, warm side lighting revealing the wood grain, rich close composition, timeless floors crafted by hand.' },
  { code: '/hogar-deck', name: 'Deck de madera', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Newly built wooden deck with outdoor furniture at golden hour, warm sunlight glowing on oiled boards, wide inviting composition, the backyard officially turned into another living room.' },
  { code: '/hogar-pergola', name: 'Pérgola', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'New wooden pergola framing a patio dining set, young climbing plants reaching upward, soft afternoon light filtering through the slats, charming wide composition, shade with real character.' },
  { code: '/hogar-quincho', name: 'Quincho', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Rustic quincho with a brick parrilla grill, long wooden table and string lights glowing at dusk, warm light everywhere, wide convivial composition, the place where weekends become memories.' },
  { code: '/hogar-placard', name: 'Placard a medida', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Custom-built closet with organized shelves, soft-close drawers and warm LED strips inside, craftsman adjusting a door, bright interior lighting, satisfying tidy composition, every single centimeter working hard.' },
  { code: '/hogar-cocinaamedida', name: 'Cocina a medida', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Carpenter fitting custom kitchen cabinetry into place, clamps holding a tall unit steady, bright natural light, dynamic process composition, woodwork measured to the exact millimeter.' },
  { code: '/hogar-mesada', name: 'Mesada nueva', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Polished stone countertop being lowered onto new kitchen cabinets, installers guiding it with suction cups, bright kitchen lighting, dramatic installation moment, the crowning piece of the kitchen.' },
  { code: '/hogar-bacha', name: 'Bacha y grifería', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Undermount sink with a matte black faucet set into a stone countertop, water running crystal clear, bright kitchen lighting, clean detail composition, the finishing touch that completes the kitchen.' },
  { code: '/hogar-ventanas', name: 'Ventanas de aluminio', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'New aluminum window being sealed into a facade opening, installer applying expanding foam around the frame, bright daylight, clean installation composition, natural light and silence perfectly framed.' },
  { code: '/hogar-puerta', name: 'Puerta interior', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'New interior door hung with brushed steel handles, carpenter checking the perfect swing, bright hallway lighting, clean architectural composition, the detail that finishes every single room.' },
  { code: '/hogar-escalera', name: 'Escalera renovada', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Renovated staircase with warm wooden treads and a black metal railing, dramatic side light grazing the steps, elegant upward composition, the sculptural spine of the house.' },
  { code: '/hogar-baranda', name: 'Baranda', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Custom metal railing being installed on a balcony at dusk, craftsman tightening the final bolts, city lights appearing behind, dramatic backlit composition, safety designed with an architect eye.' },
  { code: '/hogar-frente', name: 'Frente renovado', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Freshly painted house facade in warm tones at golden hour, new windows gleaming, tidy landscaped front garden, wide curb-appeal composition, the whole house smiling at the street.' },
  { code: '/hogar-techo', name: 'Techo reparado', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Roofer replacing worn tiles on a pitched roof, fresh tiles stacked within reach, bright midday sun, dynamic elevated composition, the protective umbrella of the house renewed.' },
  { code: '/hogar-canaletas', name: 'Canaletas', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'New seamless gutters and downspouts installed along a roofline, a water test flowing cleanly through them, bright daylight, crisp architectural detail composition, rain redirected with total precision.' },
  { code: '/hogar-patio', name: 'Patio renovado', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Renovated patio with fresh paving, potted plants and string lights glowing at dusk, warm inviting atmosphere, wide lifestyle composition, the outdoor living space fully reclaimed.' },
  { code: '/hogar-jardin', name: 'Jardín diseñado', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Newly landscaped garden with curved beds, fresh mulch and young native plants, soft morning light on green leaves, wide serene composition, nature composed like a living painting.' },
  { code: '/hogar-pileta', name: 'Pileta instalada', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Newly installed swimming pool filled with turquoise water, clean stone coping and wooden deck around it, sparkling midday sun, wide resort-like composition, endless summer permanently at home.' },
  { code: '/hogar-hidromasaje', name: 'Hidromasaje', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Outdoor jacuzzi steaming gently at dusk with jets bubbling, wooden surround and warm accent lights, moody blue-hour atmosphere, indulgent close composition, spa nights without ever leaving home.' },
  { code: '/hogar-luzjardin', name: 'Iluminación exterior', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Garden path illuminated by warm spike lights at night, plants glowing sculpturally against the darkness, the electrician finished work, magical nocturnal wide composition, the garden reborn after dark.' },
  { code: '/hogar-living', name: 'Living renovado', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Renovated living room with a textured feature wall, new flooring and warm designer lighting, soft evening lamps glowing, wide cozy composition, the room where family life happens.' },
  { code: '/hogar-dormitorio', name: 'Dormitorio', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Serene renovated bedroom with an upholstered headboard, layered bedding and soft glowing bedside lamps, calm morning light through linen curtains, wide restful composition, sleep officially upgraded.' },
  { code: '/hogar-homeoffice', name: 'Home office', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Compact home office with a floating desk, ergonomic chair and warm task lighting, tidy organized shelves, bright focused daylight, productive close composition, the corner where careers quietly grow.' },
  { code: '/hogar-lavadero', name: 'Lavadero', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Organized laundry room with stacked washer and dryer, folding counter and tall wall cabinets, bright clean lighting, tidy functional composition, the hardest-working room made beautiful.' },
  { code: '/hogar-vestidor', name: 'Vestidor', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Elegant walk-in closet with glass-front wardrobes, a central island of drawers and warm chandelier light, boutique atmosphere, luxurious wide composition, getting dressed turned into a daily ritual.' },
  { code: '/hogar-demolicion', name: 'Demolición', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Worker breaking an old interior wall with a rotary hammer, dust swirling in dramatic shafts of light, full protective gear on, powerful action composition, beautiful beginnings always look like chaos.' },
  { code: '/hogar-obranueva', name: 'Obra en marcha', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'House under active construction with exposed brickwork and scaffolding, workers on different levels, bright clear daylight, documentary wide composition, the dream taking solid physical shape.' },
  { code: '/hogar-planos', name: 'Proyecto en planos', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Architectural blueprints unrolled on a table with scale ruler and pencil, construction site blurred behind, bright daylight, professional planning composition, every great home starts on paper.' },
  { code: '/hogar-medicion', name: 'Medición láser', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Laser distance measure projecting a sharp red line across an empty room, technician noting dimensions on a tablet, bright natural daylight, precise technical composition, millimeter accuracy before the first cut.' },
  { code: '/hogar-entrega', name: 'Entrega de obra', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Contractor handing the house keys to happy new homeowners at their front door, the finished facade glowing behind them, warm golden daylight, emotional documentary moment, the dream officially delivered.' },
  { code: '/hogar-mantenimiento', name: 'Mantenimiento', brandSafe: true,
    rubros: ['hogar'],
    prompt: 'Handyman carefully touching up paint on a wooden window frame, neat drop cloth protecting below, bright natural daylight, careful close composition, the small fixes that keep a home young.' },
];
