// Auto-generated index: concatena los presets por rubro.
'use strict';
module.exports = [
  ...require('./arte'),
  ...require('./autos'),
  ...require('./bar'),
  ...require('./barberia'),
  ...require('./belleza'),
  ...require('./cafeteria'),
  ...require('./deco'),
  ...require('./educacion'),
  ...require('./eventos'),
  ...require('./fitness'),
  ...require('./flores'),
  ...require('./fotografia'),
  ...require('./gastronomia'),
  ...require('./hogar'),
  ...require('./inmobiliaria'),
  ...require('./joyeria'),
  ...require('./mascotas'),
  ...require('./moda'),
  ...require('./otro'),
  ...require('./profesionales'),
  ...require('./salud'),
  ...require('./servicios'),
  ...require('./tecnologia'),
  ...require('./turismo'),
  ...require('./viajes'),
];
