// image-styles-rubros/inmobiliaria.js — Presets de estilos de imagen: INMOBILIARIA.
// 40 presets. Formato: { code, name, brandSafe, rubros[], prompt }
// code único global con prefijo '/inmo-'. Todos brandSafe: fotografía real que respeta la propiedad.
'use strict';

module.exports = [
  { code: '/inmo-livingluz', name: 'Living con ventanales', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Bright real estate photography: sunlit living room with floor-to-ceiling windows, wide-angle 16mm lens, crisp vertical lines, soft daylight flooding neutral furniture, airy aspirational staging, magazine-quality composition.' },
  { code: '/inmo-cocinachef', name: 'Cocina de diseño', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'High-end kitchen photography: designer chef kitchen with marble island and brass fixtures, warm under-cabinet lighting, 24mm wide-angle, styled with fresh produce, crisp reflections, architectural-digest aesthetic.' },
  { code: '/inmo-frentecasa', name: 'Fachada al atardecer', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Twilight real estate exterior: modern house facade at blue hour, warm light glowing from the windows, 24mm lens from a low three-quarter angle, manicured garden foreground, cinematic inviting mood.' },
  { code: '/inmo-dormitoriosuite', name: 'Dormitorio suite', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Serene master bedroom photography: crisp linen bedding in soft morning light, 35mm lens, shallow depth of field, bedside lamps glowing, calm neutral palette, boutique-hotel styling.' },
  { code: '/inmo-terrazaquincho', name: 'Terraza con quincho', brandSafe: true,
    rubros: ['inmobiliaria', 'eventos'],
    prompt: 'Rooftop terrace lifestyle photography: outdoor grill area with lounge seating at golden hour, city skyline behind, 24mm wide-angle, string lights warming up, aspirational entertaining scene.' },
  { code: '/inmo-banodespa', name: 'Baño estilo spa', brandSafe: true,
    rubros: ['inmobiliaria', 'turismo'],
    prompt: 'Spa-like bathroom photography: freestanding soaking tub beside a frosted window, marble and wood textures, soft diffused daylight, 35mm lens, eucalyptus sprig styling, serene wellness mood.' },
  { code: '/inmo-homeoffice', name: 'Oficina en casa', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Home office photography: minimalist desk by a large window, daylight streaming over laptop and notebook, 35mm lens, green plant accent, shallow depth of field, productive calm atmosphere.' },
  { code: '/inmo-patiointerno', name: 'Patio interno', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Interior courtyard photography: lush vertical garden around a skylit patio, dappled sunlight filtering through leaves, 24mm wide-angle, stone and wood textures, tranquil urban oasis feel.' },
  { code: '/inmo-comedor', name: 'Comedor elegante', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Elegant dining room photography: long table set for dinner under sculptural pendant lights, warm evening glow, 35mm lens, linen and candlelight details, sophisticated hosting atmosphere.' },
  { code: '/inmo-vestidor', name: 'Vestidor', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Walk-in closet photography: organized wardrobe with LED strip lighting, 24mm wide-angle, glass-front drawers and a shoe wall in focus, soft even illumination, luxury boutique dressing-room feel.' },
  { code: '/inmo-pileta', name: 'Pileta con deck', brandSafe: true,
    rubros: ['inmobiliaria', 'turismo'],
    prompt: 'Resort-style pool photography: turquoise pool with wooden deck and loungers, bright midday sun, 16mm wide-angle, palm trees framing the composition, sparkling water reflections, sharp shadows, vacation-at-home mood.' },
  { code: '/inmo-jardin', name: 'Jardín', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Landscaped garden photography: manicured lawn and flowering beds in late-afternoon golden light, 35mm lens, long soft shadows, house facade peeking through greenery, peaceful suburban dream.' },
  { code: '/inmo-lobby', name: 'Hall del edificio', brandSafe: true,
    rubros: ['inmobiliaria', 'turismo'],
    prompt: 'Building lobby photography: double-height entrance hall with designer furniture and a concierge desk, soft daylight from glass walls, 16mm wide-angle, polished stone reflections, prestigious arrival feeling.' },
  { code: '/inmo-amenitygym', name: 'Gym del edificio', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Residential gym photography: modern fitness room with floor-to-ceiling mirrors and premium equipment, bright even lighting, 24mm wide-angle, clean architectural lines, motivating wellness-club atmosphere, rubber flooring detail.' },
  { code: '/inmo-amenitysum', name: 'SUM para eventos', brandSafe: true,
    rubros: ['inmobiliaria', 'eventos'],
    prompt: 'Event hall photography: elegant party room with a long banquet table set for celebration, warm pendant lighting, 24mm wide-angle, festive yet refined styling, ready-for-guests atmosphere.' },
  { code: '/inmo-escalera', name: 'Escalera de diseño', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Architectural staircase photography: sculptural floating stairs under a skylight, dramatic low angle, 24mm lens, strong geometric lines, daylight carving deep shadows, striking design-magazine composition from below.' },
  { code: '/inmo-detallelujo', name: 'Detalle de materiales', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Material detail macro photography: close-up of marble veining, brushed brass handle and oak grain, raking side light revealing texture, 50mm macro lens, shallow depth, craftsmanship-focused luxury.' },
  { code: '/inmo-vistapiso', name: 'Vista panorámica', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Panoramic view photography: city skyline framed by floor-to-ceiling apartment windows, 16mm wide-angle, interior silhouette in the foreground, blue-hour glow outside, breathtaking urban vista unfolding below.' },
  { code: '/inmo-oficina', name: 'Oficina corporativa', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Corporate office photography: bright open-plan workspace with glass partitions and designer desks, daylight flooding in, 24mm wide-angle, green plants softening the space, professional modern-business atmosphere.' },
  { code: '/inmo-local', name: 'Local comercial', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Retail storefront photography: glass-front commercial space on a lively street, bright interior visible through the windows, 35mm lens, clean signage area, high-foot-traffic commercial appeal at midday.' },
  { code: '/inmo-obra', name: 'Avance de obra', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Construction progress photography: active building site with exposed concrete structure, warm late-day side light, 35mm lens, crane silhouette against the sky, sense of momentum and trustworthy development.' },
  { code: '/inmo-maqueta', name: 'Maqueta del proyecto', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Architectural model photography: detailed scale maquette of the development on a studio table, soft top-down lighting, 50mm lens, shallow depth, miniature precision, off-plan sales presentation feel.' },
  { code: '/inmo-vendida', name: 'Propiedad vendida', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Sold-property photography: elegant SOLD sign on a beautiful house facade, bright sunny day, 35mm lens, flowers in the foreground, celebratory social-proof moment for the agency.' },
  { code: '/inmo-llaves', name: 'Entrega de llaves', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Key handover photography: close-up of hands exchanging house keys, warm golden backlight, 50mm lens, shallow depth of field, new front door softly blurred behind, emotional new-beginning moment.' },
  { code: '/inmo-interiornoite', name: 'Living de noche', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Night interior photography: cozy living room lit by warm lamps with city lights beyond the windows, 35mm lens, amber glow on soft textures, intimate evening-at-home mood.' },
  { code: '/inmo-garaje', name: 'Cochera doble', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Double garage photography: spotless polished concrete floor with epoxy finish and LED strip lighting, 24mm wide-angle, two cars parked symmetrically, crisp clean architectural lines, premium secure-parking presentation.' },
  { code: '/inmo-dormitoriochicos', name: 'Dormitorio de chicos', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Kids bedroom photography: cheerful room with playful bedding and a wooden toy shelf, soft morning window light, 35mm lens, colorful accents on neutral walls, stuffed animals, happy family-home warmth.' },
  { code: '/inmo-biblioteca', name: 'Biblioteca en casa', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Home library photography: floor-to-ceiling wooden bookshelves with a leather reading chair, warm reading-lamp glow, 35mm lens, rich wood textures, stacked books and brass ladder, intellectual cozy retreat.' },
  { code: '/inmo-frentedepto', name: 'Frente de edificio', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Apartment building facade photography: modern residential tower shot from a low angle at blue hour, 16mm lens, lit windows patterning the facade, prestigious urban living statement.' },
  { code: '/inmo-mudanza', name: 'Día de mudanza', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Moving-day lifestyle photography: happy family carrying cardboard boxes into a bright new home, natural daylight streaming through the door, 35mm lens, candid genuine smiles, fresh-start emotional storytelling.' },
  { code: '/inmo-asesor', name: 'Retrato del asesor', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Real estate agent portrait: confident professional in a tailored blazer smiling before a modern property, soft golden-hour backlight, 85mm lens, shallow depth of field, trustworthy approachable personal brand.' },
  { code: '/inmo-antesdespues', name: 'Antes y después', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Renovation before-after diptych photography: the same room angle showing a dramatic transformation, bright even lighting on both sides, 24mm wide-angle, powerful visual proof of remodeling value.' },
  { code: '/inmo-terreno', name: 'Lote en venta', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Land lot photography: open parcel with boundary markers under a vast sky, golden-hour side light, 24mm wide-angle, distant trees framing the horizon, blank-canvas investment opportunity.' },
  { code: '/inmo-casaquinta', name: 'Casa quinta', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Country house photography: charming quinta with sprawling lawn, mature trees and gravel path at sunset, 35mm lens, warm light washing over the facade, weekend-escape aspirational mood.' },
  { code: '/inmo-bodega', name: 'Cava de vinos', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Private wine cellar photography: climate-controlled cava with backlit bottle walls and a rustic tasting table, moody low-key lighting, 35mm lens, decanter catching the glow, connoisseur luxury atmosphere.' },
  { code: '/inmo-rooftopcomun', name: 'Rooftop común', brandSafe: true,
    rubros: ['inmobiliaria', 'turismo', 'eventos'],
    prompt: 'Common rooftop lounge photography: shared terrace with pergola seating and a skyline view at dusk, warm string lights glowing overhead, 24mm wide-angle, neighbors chatting, community lifestyle appeal.' },
  { code: '/inmo-canchapadel', name: 'Cancha de pádel', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Padel court amenity photography: pristine glass-walled court glowing in late-afternoon light, 24mm wide-angle, long shadows stretching across the blue turf, players mid-rally, sporty residential-community lifestyle.' },
  { code: '/inmo-petfriendly', name: 'Hogar pet friendly', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Pet-friendly home photography: happy golden retriever lounging on a sunny living-room rug, soft window light, 50mm lens, shallow depth, chew toy nearby, warm family-and-pets welcome.' },
  { code: '/inmo-balconamanecer', name: 'Balcón al amanecer', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Balcony sunrise photography: steaming coffee cup on a railing with dawn light over the city, 50mm lens, soft pink-gold sky, shallow depth, slow-morning lifestyle dream.' },
  { code: '/inmo-coworking', name: 'Coworking del edificio', brandSafe: true,
    rubros: ['inmobiliaria'],
    prompt: 'Coworking amenity photography: stylish shared work lounge with hot desks and glass phone booths, bright daylight, 24mm wide-angle, focused creative professionals with laptops open, work-from-home upgrade.' },
];
