module.exports = [
  { code: '/joy-anillomacro', name: 'Anillo macro con destellos', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Ring macro with fire: solitaire diamond scattering rainbow sparkles, dark background, focused LED pin light, 100mm macro lens, extreme detail, luxury jewelry campaign, mesmerizing brilliance.' },
  { code: '/joy-joyero', name: 'Estuche abierto con piezas', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Open jewelry box reveal: velvet-lined case with gold pieces, soft directional light, 50mm lens at f2, shallow depth, heirloom luxury presentation, gift moment, treasure chest.' },
  { code: '/joy-puestamano', name: 'Anillo puesto en mano', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Ring worn on elegant hand: graceful fingers with statement ring, soft window light, 85mm lens, silk fabric drape, refined lifestyle jewelry photography, effortless sophistication, with vivid detail and true-to-life color.' },
  { code: '/joy-alianzas', name: 'Alianzas de boda', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Wedding bands pair: two gold rings entwined on white silk, soft diffused light, 100mm macro lens, romantic symbolism, bridal jewelry photography, eternal promise, with tack-sharp detail and natural tones.' },
  { code: '/joy-compromiso', name: 'Anillo de compromiso en caja', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Engagement ring in box: open ring box with solitaire, dramatic spotlight, 70mm lens, dark romantic background, proposal moment storytelling, she-said-yes energy, sparkling anticipation, with rich detail and natural color.' },
  { code: '/joy-collarcuello', name: 'Collar en cuello', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Necklace on neck close-up: gold chain resting on collarbone, soft beauty light, 85mm lens, bare-shoulder elegance, delicate jewelry lifestyle shot, subtle allure, with vivid detail and true-to-life color.' },
  { code: '/joy-cadenamacro', name: 'Cadena macro eslabones', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Chain link macro: interlocked gold links catching hard light, 100mm macro lens, dark background, metalwork precision, chain craftsmanship showcase, solid weight, with tack-sharp detail and natural tones.' },
  { code: '/joy-pulseramuneca', name: 'Pulsera en muñeca', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Bracelet on wrist: stacked gold bangles mid-gesture, warm daylight, 85mm lens, motion elegance, everyday luxury jewelry styling, wrist-stack trend, radiant layers, with rich detail and natural color.' },
  { code: '/joy-aretesoreja', name: 'Aretes en oreja', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Earrings worn close-up: dangling gold earrings catching light, soft side light, 100mm macro lens, hair swept back, elegant ear styling photography, graceful movement, with vivid detail and true-to-life color.' },
  { code: '/joy-aretesmacro', name: 'Aretes macro', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Earring pair macro: gemstone studs on dark velvet, dramatic pin lighting, 100mm macro lens, sparkle detail, fine jewelry product photography, exquisite brilliance, with tack-sharp detail and natural tones.' },
  { code: '/joy-dijescharm', name: 'Dijes charm', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Charm bracelet detail: tiny meaningful pendants, soft daylight, 90mm lens, storytelling composition, personalized jewelry concept, sentimental luxury, collected memories, with rich detail and natural color.' },
  { code: '/joy-relojmuneca', name: 'Reloj en muñeca', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Watch on wrist lifestyle: luxury timepiece with suit cuff, window light, 85mm lens, executive elegance, horology detail, refined masculine jewelry, quiet power, with vivid detail and true-to-life color.' },
  { code: '/joy-relojmacro', name: 'Reloj macro esfera', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Watch dial macro: intricate hands and indices, dramatic side light, 100mm macro lens, dark background, mechanical artistry, collector-grade detail, timeless precision, with tack-sharp detail and natural tones.' },
  { code: '/joy-collarperlas', name: 'Collar de perlas', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Pearl necklace drape: lustrous strand on black silk, soft diffused light, 70mm lens, timeless elegance, pearl luster macro feel, classic bridal luxury, gentle glow, with rich detail and natural color.' },
  { code: '/joy-diamantesuelto', name: 'Diamante suelto con pinza', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Loose diamond in tweezers: brilliant stone held against dark backdrop, intense pin light, 100mm macro lens, fire and scintillation, gemologist showcase, pure rarity, with vivid detail and true-to-life color.' },
  { code: '/joy-piedracolor', name: 'Piedra de color', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Colored gemstone macro: vivid emerald with internal glow, dramatic backlight, 100mm macro lens, dark background, saturated color jewelry photography, natural wonder, with tack-sharp detail and natural tones.' },
  { code: '/joy-oro18k', name: 'Piezas de oro 18k', brandSafe: true,
    rubros: ['joyeria'],
    prompt: '18k gold pieces arrangement: warm yellow gold catching studio light, 70mm lens, rich tones on dark stone, solid gold value storytelling, investment luxury, lasting worth.' },
  { code: '/joy-platapiezas', name: 'Piezas de plata', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Silver jewelry collection: polished pieces with cool reflections, soft daylight, 70mm lens, minimalist styling, contemporary silver design, accessible luxury, modern shine, with crisp detail and balanced tones.' },
  { code: '/joy-duooroplata', name: 'Dúo oro y plata', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Gold and silver mixed stack: two-tone layered necklaces, soft window light, 85mm lens, modern mixed-metal trend, versatile styling photography, effortless layering, with refined detail and cinematic color.' },
  { code: '/joy-setcompleto', name: 'Set collar + aretes', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Matching jewelry set: necklace and earrings arranged together, soft studio light, 50mm lens, coordinated luxury presentation, gift-set storytelling, perfect pairing, with luminous detail and authentic color.' },
  { code: '/joy-cajaregalo', name: 'Caja de regalo con moño', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Gift box with ribbon: luxury jewelry box tied with satin bow, warm festive light, 50mm lens, anticipation mood, gifting occasion photography, delightful surprise, with crisp detail and balanced tones.' },
  { code: '/joy-propuesta', name: 'Momento de propuesta', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Proposal hand moment: ring sliding onto finger, golden hour glow, 85mm lens at f1.8, blurred celebration, emotional jewelry storytelling, once-in-a-lifetime, tearful joy, with refined detail and cinematic color.' },
  { code: '/joy-medallabautismo', name: 'Medalla de bautismo', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Baptism medal: delicate gold pendant on white lace, soft nursery light, 90mm lens, tender family milestone, heirloom religious jewelry photography, blessed keepsake, with luminous detail and authentic color.' },
  { code: '/joy-quinceanios', name: 'Joyería de quince años', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Quinceañera jewelry set: tiara and earrings sparkling, pink celebration bokeh, 70mm lens, milestone glamour, princess-moment jewelry styling, unforgettable night, with crisp detail and balanced tones.' },
  { code: '/joy-graduacion', name: 'Joyería de graduación', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Graduation gift jewelry: engraved bracelet in gift box, bright hopeful daylight, 50mm lens, achievement celebration, milestone gifting photography, proud accomplishment, with refined detail and cinematic color.' },
  { code: '/joy-diamadre', name: 'Joyería Día de la Madre', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Mothers Day jewelry: heart pendant with fresh flowers, soft morning light, 70mm lens, tender emotional mood, mom-gift storytelling, sentimental luxury, grateful love, with luminous detail and authentic color.' },
  { code: '/joy-sanvalentin', name: 'Joyería San Valentín', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Valentine jewelry romance: red-gem ring among rose petals, warm candlelight glow, 70mm lens, passionate gifting mood, romantic occasion campaign, burning love, with crisp detail and balanced tones.' },
  { code: '/joy-navidad', name: 'Joyería de Navidad', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Christmas jewelry sparkle: gold pieces among pine and fairy lights, warm festive glow, 50mm lens, holiday gifting magic, seasonal luxury campaign, joyful giving, with refined detail and cinematic color.' },
  { code: '/joy-grabadopersonalizado', name: 'Grabado personalizado', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Engraving in progress: jeweler hand engraving initials on band, bright task light, 100mm macro lens, personalization craft, bespoke jewelry service, meaningful detail, with luminous detail and authentic color.' },
  { code: '/joy-tallerorfebre', name: 'Taller del orfebre', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Goldsmith workshop: artisan hands at workbench with tools, warm workshop light, 50mm lens, craft authenticity, handmade jewelry storytelling, trade pride, focused mastery, with crisp detail and balanced tones.' },
  { code: '/joy-fundicionoro', name: 'Fundición de oro', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Gold melting moment: crucible pouring molten gold, dramatic orange glow, 70mm lens, sparks and heat, raw material transformation, atelier drama, elemental craft, with refined detail and cinematic color.' },
  { code: '/joy-engastepiedra', name: 'Engaste de piedra', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Stone setting precision: gem placed into prong mount, bright magnifier light, 100mm macro lens, jeweler tweezers, meticulous craftsmanship photography, perfect seat, with luminous detail and authentic color.' },
  { code: '/joy-pulidofinal', name: 'Pulido final', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Final polishing: buffing wheel bringing mirror shine to ring, bright workshop light, 90mm lens, gleaming metal detail, finishing-touch craftsmanship, flawless reflection, with crisp detail and balanced tones.' },
  { code: '/joy-diseno3d', name: 'Diseño 3D de pieza', brandSafe: true,
    rubros: ['joyeria'],
    prompt: '3D jewelry design: CAD render of ring on screen beside wax model, cool monitor glow, 50mm lens, modern bespoke process, technology meets craft, custom creation.' },
  { code: '/joy-restauracion', name: 'Restauración antes y después', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Restoration before-after: tarnished versus gleaming heirloom piece, even studio light, 70mm lens, transformation storytelling, restoration service proof, revived beauty, with tack-sharp detail and natural tones.' },
  { code: '/joy-herenciafamiliar', name: 'Joya de herencia familiar', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Family heirloom: antique ring on old photograph, soft nostalgic light, 70mm lens, generations storytelling, emotional heritage jewelry photography, timeless bond, with rich detail and natural color.' },
  { code: '/joy-vintageestate', name: 'Joyería vintage estate', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Estate vintage jewelry: art-deco brooch on aged velvet, warm antique light, 90mm lens, collector treasure mood, one-of-a-kind vintage storytelling, storied elegance, with vivid detail and true-to-life color.' },
  { code: '/joy-minimalistadiaria', name: 'Joyería minimalista diaria', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Minimalist everyday jewelry: thin gold bands on clean white, soft daylight, 70mm lens, less-is-more styling, daily-wear collection photography, quiet luxury, with tack-sharp detail and natural tones.' },
  { code: '/joy-piezastatement', name: 'Pieza statement', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Statement cocktail ring: oversized gem on model hand, dramatic studio light, 85mm lens, bold fashion jewelry, red-carpet attitude photography, commanding presence, with rich detail and natural color.' },
  { code: '/joy-joyeriahombre', name: 'Joyería masculina', brandSafe: true,
    rubros: ['joyeria'],
    prompt: 'Men jewelry edge: chunky chain and signet ring, moody low-key light, 85mm lens, masculine luxury styling, modern gentleman accessories, confident statement, with vivid detail and true-to-life color.' },
];
