module.exports = [
  { code: "/masc-cachorroconsulta", name: "Cachorro en camilla veterinaria", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Golden retriever puppy sitting on a vet exam table while the vet gently checks its ear, bright clean clinic lighting, 50mm eye-level shot, heartwarming veterinary photography." },
  { code: "/masc-pelucanina", name: "Corte en peluquería canina", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Poodle mid-haircut on a grooming table, groomer trimming with scissors, fur clippings in the air, bright salon lighting, 50mm medium shot, professional grooming photography, natural vignette draws the eye, authentic documentary feel." },
  { code: "/masc-juguetemordida", name: "Perro con juguete en la boca", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Happy border collie running toward camera with a rope toy in its mouth, motion blur on paws, bright park daylight, 85mm action freeze, joyful pet photography." },
  { code: "/masc-gatovidriera", name: "Gato en la vidriera del local", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Orange tabby cat lounging in a pet shop window display among toys, soft daylight through glass, shallow 85mm focus on green eyes, irresistible storefront photography." },
  { code: "/masc-bañoperro", name: "Baño de perro en la peluquería", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Labrador covered in shampoo foam in a grooming bathtub, shaking water droplets everywhere, bright bathroom lighting, 50mm freeze frame, funny bathing photography, fine detail in highlights and shadows, premium magazine look." },
  { code: "/masc-vacunacion", name: "Vacunación de cachorro", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Vet gently vaccinating a calm beagle puppy held by its owner, reassuring smiles, bright clinical lighting, 50mm medium shot, trust-building veterinary photography, soft glow on key surfaces, harmonious balanced composition." },
  { code: "/masc-gatoadopcion", name: "Gato en adopción mirando a cámara", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Rescue kitten with big eyes looking straight into the lens, paws on a cardboard adoption sign, soft shelter lighting, 85mm tight portrait, emotional adoption photography." },
  { code: "/masc-comederopremium", name: "Perro comiendo alimento premium", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "French bulldog eating kibble from a ceramic bowl, kibble bag blurred behind, warm kitchen light, 60mm low close shot, appetizing pet-food photography, crisp focus with creamy bokeh, high-end production value." },
  { code: "/masc-paseogrupal", name: "Paseo grupal de perros", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Pack of diverse dogs walking with a professional dog walker on leashes in a park, autumn leaves, morning light, 35mm wide shot, lively dog-walking service photography." },
  { code: "/masc-gatocama", name: "Gato durmiendo en cama del local", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Cat curled asleep in a plush donut pet bed on a store shelf, price tag visible, soft warm lighting, 60mm close shot, cozy product-lifestyle photography." },
  { code: "/masc-corteuñas", name: "Corte de uñas profesional", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Groomer carefully clipping a dachshund's nails on a table, dog calm and relaxed, bright salon light, 60mm detail close-up, careful grooming-service photography, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/masc-ecografiavet", name: "Ecografía veterinaria", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Vet performing an ultrasound on a pregnant dog's belly, monitor glowing in a dim exam room, 50mm medium shot, advanced-care veterinary photography, gentle atmospheric haze adds depth, vivid natural color grading." },
  { code: "/masc-limpiezadentalvet", name: "Limpieza dental veterinaria", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Vet dentist cleaning a dog's teeth with ultrasonic scaler, dog under gentle sedation, bright surgical lamp, 60mm clinical close shot, dental-health veterinary photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/masc-conejotienda", name: "Conejo en la tienda de mascotas", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Fluffy white rabbit nibbling hay in a clean store enclosure, soft daylight, 60mm close shot with shallow depth, adorable small-pet retail photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/masc-peceratienda", name: "Pecera del local con peces tropicales", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Bright aquarium with colorful tropical fish and planted decor in a pet shop, blue tank lighting glowing, 35mm straight-on shot, vivid aquatics retail photography, clean background separation, professional commercial polish throughout." },
  { code: "/masc-lorojuguete", name: "Loro jugando con su juguete", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Green parrot chewing a wooden toy on a stand, feathers detailed, bright natural light, 85mm tight portrait, charismatic bird photography, delicate rim light defines edges, refined editorial finish." },
  { code: "/masc-perroplaya", name: "Perro corriendo en la playa", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Dog sprinting along the shoreline kicking up sand and spray, ocean behind, golden hour backlight, 85mm action freeze, epic beach pet photography, natural vignette draws the eye, authentic documentary feel." },
  { code: "/masc-gatocaja", name: "Gato metido en una caja de cartón", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Cat squeezed into a small cardboard box with a blissful face, soft home lighting, 60mm close shot, funny relatable cat photography, fine detail in highlights and shadows, premium magazine look." },
  { code: "/masc-perrocollar", name: "Perro estrenando collar nuevo", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Shiba inu posing proudly wearing a new leather collar, store display blurred behind, bright retail lighting, 85mm portrait, proud new-accessory photography, soft glow on key surfaces, harmonious balanced composition." },
  { code: "/masc-hamsterrueda", name: "Hámster corriendo en su rueda", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Hamster running in a wheel inside a glass habitat, motion blur on wheel, soft warm light, 60mm close shot, cute small-pet photography, crisp focus with creamy bokeh, high-end production value." },
  { code: "/masc-vetsonrisa", name: "Veterinaria abrazando a su paciente", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Smiling vet hugging a recovered senior dog in the clinic, warm genuine moment, bright daylight, 50mm medium shot, human caring veterinary photography, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/masc-guarderiacanina", name: "Guardería canina en hora de juego", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Dogs of all sizes playing together in a daycare yard with tunnels and balls, dust in the air, bright daylight, 35mm wide action shot, fun daycare photography." },
  { code: "/masc-cachorroslactando", name: "Camada de cachorros lactando", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Litter of newborn puppies nursing with their calm watchful mother on a soft blanket, warm nursery lamp light, 50mm close composition, tender breeding-care photography, gentle atmospheric haze adds depth, vivid natural color grading." },
  { code: "/masc-gatoarenero", name: "Gato con su arenero nuevo", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Cat curiously sniffing a new covered litter box, litter bag beside, bright home lighting, 50mm medium shot, practical cat-care product photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/masc-perroabrigo", name: "Perro con abrigo de invierno", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Small dog wearing a quilted winter coat on a frosty street, breath visible in cold air, soft overcast light, 85mm portrait, adorable winter pet-fashion photography." },
  { code: "/masc-snacknatural", name: "Snacks naturales para perros", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Natural dog treats arranged on a wooden board with ingredients around, dog nose entering frame, warm kitchen light, 60mm food-style shot, wholesome treat photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/masc-sesionfotos", name: "Sesión de fotos para mascotas", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Corgi posing with a tiny bow tie against a pastel pink studio backdrop, professional softbox lighting, 85mm tight portrait, polished pet-studio photography, clean background separation, professional commercial polish throughout." },
  { code: "/masc-perrosenior", name: "Perro senior con su dueño", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Grey-muzzled senior dog resting its head on its owner's lap, tender bond, soft window light, 85mm intimate portrait, emotional senior-pet photography, delicate rim light defines edges, refined editorial finish." },
  { code: "/masc-gatojuguete", name: "Gato cazando su juguete", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Cat mid-pounce on a feather wand toy, claws out, eyes locked, bright living room light, 85mm high-speed freeze, playful hunting photography, natural vignette draws the eye, authentic documentary feel." },
  { code: "/masc-cepilladopelo", name: "Cepillado de pelo en peluquería", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Groomer brushing a long-haired cat with loose fur floating in the air, cat purring relaxed, bright salon light, 60mm close shot, satisfying grooming photography, fine detail in highlights and shadows, premium magazine look." },
  { code: "/masc-pipetaantipulgas", name: "Aplicación de pipeta antipulgas", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Vet applying a flea pipette between a cat's shoulder blades, cat calm on exam table, bright clinic light, 60mm detail close-up, preventive-care photography, soft glow on key surfaces, harmonious balanced composition." },
  { code: "/masc-transportadora", name: "Mascota en su transportadora", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Kitten peeking out of an open pet carrier by a car door, travel blanket inside, soft daylight, 50mm medium shot, pet-travel product photography, crisp focus with creamy bokeh, high-end production value." },
  { code: "/masc-agility", name: "Perro en pista de agility", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Border collie weaving through agility poles at full speed, handler guiding, bright outdoor light, 85mm action freeze, exciting dog-sport photography, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/masc-gatoventana", name: "Gato mirando por la ventana", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Cat silhouetted watching birds from a sunny windowsill, leafy plants framing the scene, soft backlight glow on fur, 50mm contemplative shot, serene indoor-cat photography, gentle atmospheric haze adds depth, vivid natural color grading." },
  { code: "/masc-escuelacachorros", name: "Escuela de cachorros: primera clase", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Puppies of different breeds sitting in a row during obedience class, trainer with treats, bright training hall, 35mm wide shot, adorable training-school photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/masc-peceskoi", name: "Peces koi en estanque", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Colorful koi fish gliding in a clear garden pond, ripples and lily pads, bright daylight, 50mm top-down shot, tranquil pond photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/masc-reptilterrario", name: "Reptil en su terrario", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Bearded dragon basking on a rock under a heat lamp in a planted terrarium, detailed scales, warm lamp glow, 60mm close shot, exotic-pet photography, clean background separation, professional commercial polish throughout." },
  { code: "/masc-perropremio", name: "Perro recibiendo su premio", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Dog gently taking a treat from its owner's fingers, focused happy eyes, treat jar blurred behind, warm light, 85mm close shot, rewarding-moment photography, delicate rim light defines edges, refined editorial finish." },
  { code: "/masc-hotelmascotas", name: "Habitación del hotel de mascotas", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Cozy pet hotel suite with a small bed, toys and a dog napping, warm welcoming light, 35mm wide interior shot, premium pet-boarding photography, natural vignette draws the eye, authentic documentary feel." },
  { code: "/masc-farmaciavet", name: "Estantería de la farmacia veterinaria", brandSafe: true,
    rubros: ["mascotas"],
    prompt: "Neat pharmacy shelves stocked with pet medications and supplements, pharmacist handing a bag to a client, bright retail light, 35mm wide shot, trusted vet-pharmacy photography." },
];
