module.exports = [
  { code: '/moda-lookcalle', name: 'Look completo en calle', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Full outfit street style: head-to-toe look on urban sidewalk, golden hour backlight, 35mm lens, candid mid-stride motion, city architecture blur, fashion editorial energy, confident attitude.' },
  { code: '/moda-detalletela', name: 'Macro de textura de tela', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Fabric texture macro: woven linen threads catching raking daylight, 100mm macro lens, shallow depth of field, tactile luxury material study, quality craftsmanship evidence, natural fibers.' },
  { code: '/moda-probador', name: 'Espejo de probador', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Fitting room mirror moment: outfit reflection with garments on hooks beside, warm boutique spotlights, 35mm lens, intimate try-on storytelling, retail experience photography, decision moment, with vivid detail and true-to-life color.' },
  { code: '/moda-coleccionpercha', name: 'Nueva colección en perchas', brandSafe: true,
    rubros: ['moda'],
    prompt: 'New collection on wooden hangers: curated garment rail, soft boutique daylight, 50mm lens at f2, shallow depth isolating hero piece, drop announcement photography, anticipation mood.' },
  { code: '/moda-lookbook', name: 'Lookbook editorial', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Editorial lookbook frame: model in full look against brutalist concrete, hard midday shadows, 50mm lens, high-fashion campaign mood, collection storytelling photography, striking composition, with luminous detail and authentic color.' },
  { code: '/moda-detallecostura', name: 'Detalle de costura', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Stitching detail macro: precise contrast seams on denim, raking side light, 100mm macro lens, dark background, atelier craftsmanship proof, quality close-up, durable construction, with crisp detail and balanced tones.' },
  { code: '/moda-setaccesorios', name: 'Set de accesorios', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Accessory set composition: belt, sunglasses and watch arranged on linen, soft window light, 50mm lens top-down, curated styling flat composition, outfit finishing touches, coordinated palette.' },
  { code: '/moda-dropzapatillas', name: 'Drop de zapatillas', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Sneaker drop hero shot: fresh pair with dynamic laces mid-air, dramatic studio strobe, 70mm lens, dark background, hype release energy, streetwear product photography, coveted detail.' },
  { code: '/moda-denimfit', name: 'Denim fit', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Denim fit check: model in raw selvedge jeans mid-step, urban daylight, 50mm lens, full-body composition, authentic jean culture, timeless casual fashion photography, worn-in character, with luminous detail and authentic color.' },
  { code: '/moda-vestidofiesta', name: 'Vestido de fiesta', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Evening dress in motion: flowing gown twirl, warm event bokeh behind, 85mm lens at f1.8, fabric catching light, occasion-wear glamour, celebration fashion photography, unforgettable entrance.' },
  { code: '/moda-sastreria', name: 'Sastrería traje', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Tailored suit detail: lapel and pocket square close-up, soft directional light, 90mm lens, dark elegant background, bespoke menswear craftsmanship, sartorial luxury, immaculate construction, with vivid detail and true-to-life color.' },
  { code: '/moda-streetwear', name: 'Streetwear oversize', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Oversized streetwear fit: baggy hoodie and cargos, skate park concrete, overcast daylight, 35mm lens, youth culture attitude, urban fashion documentary, relaxed silhouette, with tack-sharp detail and natural tones.' },
  { code: '/moda-vintagecurado', name: 'Vintage curado', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Curated vintage rack: one-of-one retro pieces on brass rail, warm thrift-store light, 50mm lens, nostalgic textures, secondhand treasure hunt storytelling, unique finds, with rich detail and natural color.' },
  { code: '/moda-basicos', name: 'Básicos esenciales', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Essential basics lineup: folded white tees and neutral knits, soft minimal daylight, 50mm lens, clean Scandinavian styling, wardrobe foundation concept photography, timeless versatility, with vivid detail and true-to-life color.' },
  { code: '/moda-athleisure', name: 'Ropa deportiva athleisure', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Athleisure in action: model stretching in matching set, gym window light, 50mm lens, dynamic pose, sporty lifestyle energy, performance-meets-fashion photography, sculpted comfort, with tack-sharp detail and natural tones.' },
  { code: '/moda-lenceria', name: 'Lencería', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Lingerie detail: lace set arranged on silk, soft diffused morning light, 50mm lens, tasteful elegant composition, intimate apparel boutique aesthetic, delicate craftsmanship, with rich detail and natural color.' },
  { code: '/moda-trajesbano', name: 'Trajes de baño', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Swimwear poolside: model by turquoise water, bright midday sun, 50mm lens, vacation mood, summer collection campaign, bold color swim fashion, carefree energy, with vivid detail and true-to-life color.' },
  { code: '/moda-abrigoinvierno', name: 'Abrigo de invierno', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Winter coat statement: wool overcoat in falling snow, cool blue daylight, 85mm lens, visible breath vapor, cozy luxury outerwear, seasonal collection photography, warm elegance, with tack-sharp detail and natural tones.' },
  { code: '/moda-camperacuero', name: 'Campera de cuero', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Leather jacket attitude: model leaning on motorcycle, dusk city glow, 50mm lens, rugged texture close framing, timeless rebel fashion, leather craft detail, worn patina, with rich detail and natural color.' },
  { code: '/moda-remeraestampa', name: 'Remera con estampa', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Graphic tee close-up: bold print on cotton chest, bright daylight, 70mm lens, street culture vibe, artist collaboration drop, wearable art photography, statement graphics, with vivid detail and true-to-life color.' },
  { code: '/moda-pantalonsastre', name: 'Pantalón sastre', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Tailored trouser detail: crisp pleats and pressed crease, soft studio light, 70mm lens, neutral background, office-elegant menswear, precision tailoring proof, sharp drape, with tack-sharp detail and natural tones.' },
  { code: '/moda-faldapliegue', name: 'Falda plisada', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Pleated skirt motion: twirl freezing pleats mid-air, bright daylight, 85mm lens, joyful movement, feminine modern classic, fabric dynamics photography, airy elegance, with rich detail and natural color.' },
  { code: '/moda-conjuntolino', name: 'Conjunto de lino', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Linen two-piece set: relaxed resort look on terrace, warm Mediterranean light, 50mm lens, breezy natural fabric, summer vacation wardrobe, effortless elegance, sun-kissed ease, with vivid detail and true-to-life color.' },
  { code: '/moda-overshirt', name: 'Overshirt', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Overshirt layering: open flannel over tee, autumn park golden light, 50mm lens, casual layered styling, transitional season fashion, rugged comfort, textured warmth, with tack-sharp detail and natural tones.' },
  { code: '/moda-carteranueva', name: 'Cartera nueva', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Handbag hero shot: structured bag on marble pedestal, dramatic studio light, 70mm lens, dark luxe background, leather grain detail, accessory campaign photography, coveted design, with rich detail and natural color.' },
  { code: '/moda-bolsocuero', name: 'Bolso de cuero', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Leather duffle detail: worn patina and brass hardware, warm side light, 70mm lens, travel lifestyle staging, artisanal leather goods, timeless carry photography, journey companion, with vivid detail and true-to-life color.' },
  { code: '/moda-lentessol', name: 'Lentes de sol', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Sunglasses product shot: acetate frames reflecting sunset, dramatic rim light, 100mm macro lens, dark background, lens reflection detail, eyewear campaign, summer essential, with tack-sharp detail and natural tones.' },
  { code: '/moda-gorra', name: 'Gorra', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Snapback cap street shot: model adjusting cap, bright urban daylight, 50mm lens, skate culture backdrop, embroidered logo detail, headwear drop photography, casual cool, with rich detail and natural color.' },
  { code: '/moda-cinturondetalle', name: 'Cinturón detalle', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Belt buckle macro: engraved metal buckle on leather strap, raking light, 100mm macro lens, dark background, accessory craftsmanship detail, finishing touch, polished hardware, with vivid detail and true-to-life color.' },
  { code: '/moda-bufandainvierno', name: 'Bufanda de invierno', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Chunky knit scarf: wrapped cozily around neck, frosty morning light, 85mm portrait lens, wool texture macro feel, winter warmth styling, hygge fashion, soft comfort, with tack-sharp detail and natural tones.' },
  { code: '/moda-ropaninos', name: 'Ropa de niños', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Kids clothing joy: child twirling in colorful outfit, bright playground daylight, 50mm lens, genuine laughter, playful prints, children fashion lifestyle, carefree fun, with rich detail and natural color.' },
  { code: '/moda-ropabebe', name: 'Ropa de bebé', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Baby clothing softness: tiny knit set on cream blanket, gentle nursery light, 50mm lens, delicate textures, tender newborn boutique aesthetic, precious details, with vivid detail and true-to-life color.' },
  { code: '/moda-maternidad', name: 'Ropa de maternidad', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Maternity style portrait: flowing dress on expectant mother, golden hour meadow light, 85mm lens, serene glow, bump-celebrating fashion, tender elegance, radiant motherhood, with tack-sharp detail and natural tones.' },
  { code: '/moda-tallesreales', name: 'Talles reales', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Real bodies fashion: diverse models in same collection, bright inclusive daylight, 50mm lens, confident natural poses, body-positive brand storytelling, authentic representation, with rich detail and natural color.' },
  { code: '/moda-outfitoficina', name: 'Outfit de oficina', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Office outfit polish: blazer and tailored look in modern lobby, clean architectural light, 50mm lens, professional confidence, workwear capsule styling, boardroom ready, with vivid detail and true-to-life color.' },
  { code: '/moda-outfitcita', name: 'Outfit para cita', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Date night look: elegant outfit under restaurant warm glow, 85mm lens at f1.8, candlelight bokeh, romantic evening styling, occasion fashion photography, magnetic charm, with tack-sharp detail and natural tones.' },
  { code: '/moda-invitadaboda', name: 'Invitada de casamiento', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Wedding guest elegance: midi dress among garden florals, soft afternoon light, 85mm lens, celebratory sophistication, guest-dressing inspiration photography, joyful poise, with rich detail and natural color.' },
  { code: '/moda-egresados', name: 'Outfit de egresados', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Graduation outfit: cap and gown over sharp look, campus sunlight, 50mm lens, triumphant pose, milestone fashion moment, achievement celebration, proud smile, with vivid detail and true-to-life color.' },
  { code: '/moda-hechoamano', name: 'Hecho a mano local', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Handmade garment process: artisan hands stitching at atelier table, warm workshop light, 50mm lens, thread and tools, slow-fashion craft storytelling, human touch, with tack-sharp detail and natural tones.' },
  { code: '/moda-interiortienda', name: 'Interior de la tienda', brandSafe: true,
    rubros: ['moda'],
    prompt: 'Boutique interior wide shot: curated racks and warm spotlights, inviting evening glow, 24mm wide lens, aspirational retail space, come-visit-me storytelling, designed experience, with rich detail and natural color.' },
];
