module.exports = [
  { code: '/gen-equipofoto', name: 'Foto del equipo', brandSafe: true,
    rubros: ['otro'],
    prompt: "Small business team photo: smiling staff together in front of the shop, bright morning light, 35mm warm group framing, genuine happy energy, friendly welcoming faces, vibrant natural tones, the people behind the brand." },
  { code: '/gen-localmanana', name: 'El local a la mañana', brandSafe: true,
    rubros: ['otro'],
    prompt: "Storefront in the morning: shop opening its shutters under soft golden light, 24mm inviting wide framing, fresh new-day promise, warm welcoming glow, clean attractive facade, ready to serve you." },
  { code: '/gen-atencioncliente', name: 'Atendiendo a un cliente', brandSafe: true,
    rubros: ['otro'],
    prompt: "Shopkeeper helping a customer: friendly attendant showing a product across the counter, warm interior light, 50mm genuine framing, attentive caring service, bright welcoming tones, personal attention you can feel." },
  { code: '/gen-productoestrella', name: 'Producto estrella', brandSafe: true,
    rubros: ['otro'],
    prompt: "Hero product spotlight: bestseller on a clean surface with dramatic side light, 85mm shallow depth of field, crisp detail, elegant minimal styling, rich true colors, irresistible must-have presentation." },
  { code: '/gen-cartelabierto', name: 'Cartel de abierto', brandSafe: true,
    rubros: ['otro'],
    prompt: "Open sign on a glass door: glowing OPEN sign with warm shop interior behind, soft evening light, 50mm welcoming framing, inviting cozy glow, come-on-in energy, charming neighborhood business." },
  { code: '/gen-detrasdecamaras', name: 'Detrás de cámaras', brandSafe: true,
    rubros: ['otro'],
    prompt: "Behind the scenes: owner preparing products before opening, candid working moment, natural window light, 35mm authentic framing, real unfiltered hustle, warm honest tones, the work nobody sees." },
  { code: '/gen-manosobra', name: 'Manos a la obra', brandSafe: true,
    rubros: ['otro'],
    prompt: "Hands at work: close-up of skilled hands crafting, tools in motion, focused task lighting, 50mm macro framing, dedicated craftsmanship, rich textural detail, pride in every piece made." },
  { code: '/gen-empaque', name: 'Empacando un pedido', brandSafe: true,
    rubros: ['otro'],
    prompt: "Packing an order with care: hands wrapping a product in tissue paper, neat shipping box, bright clean light, 50mm thoughtful framing, love in every package, crisp fresh tones, ready to ship happiness." },
  { code: '/gen-delivery', name: 'Delivery en camino', brandSafe: true,
    rubros: ['otro'],
    prompt: "Delivery on its way: courier with branded bag heading out the door, bright daylight, 35mm dynamic framing, fast friendly service, vibrant energetic tones, your order is coming, excitement in motion." },
  { code: '/gen-mostrador', name: 'Mostrador lleno', brandSafe: true,
    rubros: ['otro'],
    prompt: "Full display counter: abundant products beautifully arranged, warm showcase lighting, 35mm appetizing wide framing, irresistible variety, rich inviting colors, come choose your favorite, small-business abundance." },
  { code: '/gen-antesdespues', name: 'Antes y después', brandSafe: true,
    rubros: ['otro'],
    prompt: "Before-and-after transformation: split composition showing dramatic improvement, even clear lighting on both sides, 50mm honest framing, real visible results, satisfying contrast, proof of quality work." },
  { code: '/gen-clientefeliz', name: 'Cliente feliz', brandSafe: true,
    rubros: ['otro'],
    prompt: "Happy customer moment: smiling client holding their purchase outside the shop, bright daylight, 50mm joyful framing, genuine satisfaction, warm natural tones, another happy customer, trust earned." },
  { code: '/gen-taller', name: 'El taller', brandSafe: true,
    rubros: ['otro'],
    prompt: "Workshop interior: tools organized on walls, workbench in warm lamplight, 24mm atmospheric wide framing, skilled trade pride, rich warm tones, where quality is built by hand." },
  { code: '/gen-bienvenida', name: 'Bienvenida con café', brandSafe: true,
    rubros: ['otro'],
    prompt: "Warm welcome: steaming coffee cup on the counter with a smile behind, soft morning light, 50mm cozy framing, hospitality in a cup, inviting warm tones, come in and feel at home." },
  { code: '/gen-localtarde', name: 'El local a la tarde', brandSafe: true,
    rubros: ['otro'],
    prompt: "Shop in the afternoon: golden light streaming through the windows onto products, 35mm warm framing, cozy afternoon shopping, glowing inviting interior, rich warm tones, perfect time to visit." },
  { code: '/gen-fachadanoche', name: 'Fachada de noche', brandSafe: true,
    rubros: ['otro'],
    prompt: "Storefront at night: illuminated facade glowing on a quiet street, warm light spilling from windows, 24mm cinematic framing, magical evening allure, deep blues with golden warmth, open late for you." },
  { code: '/gen-estanterias', name: 'Estanterías llenas', brandSafe: true,
    rubros: ['otro'],
    prompt: "Stocked shelves: rows of products neatly organized, bright even lighting, 35mm abundant framing, everything you need in stock, clean vibrant colors, well-kept small business pride." },
  { code: '/gen-artesano', name: 'Manos del artesano', brandSafe: true,
    rubros: ['otro', 'arte'],
    prompt: "Artisan hands close-up: weathered hands shaping material with care, dramatic side light, 100mm macro framing, years of skill visible, rich textural detail, handmade with soul, craft you can trust." },
  { code: '/gen-empaqueregalo', name: 'Empaque de regalo', brandSafe: true,
    rubros: ['otro'],
    prompt: "Gift wrapping moment: hands tying a ribbon on an elegant package, soft festive light, 50mm delicate framing, thoughtful presentation, charming warm tones, ready to make someone smile." },
  { code: '/gen-primeraventa', name: 'Primera venta del día', brandSafe: true,
    rubros: ['otro'],
    prompt: "First sale of the day: owner handing a bag to the first customer, morning light in the doorway, 50mm hopeful framing, new day new beginnings, bright optimistic tones, grateful for every customer." },
  { code: '/gen-cierredia', name: 'Cierre del día', brandSafe: true,
    rubros: ['otro'],
    prompt: "End-of-day closing: owner locking up with a satisfied smile, warm dusk light, 35mm reflective framing, another good day done, cozy golden tones, small-business owner pride." },
  { code: '/gen-vidrieranueva', name: 'Vidriera nueva temporada', brandSafe: true,
    rubros: ['otro'],
    prompt: "New window display: fresh seasonal arrangement in the shop window, dramatic display lighting, 35mm eye-catching framing, stop-and-stare appeal, vibrant curated colors, new season new treasures." },
  { code: '/gen-feria', name: 'Stand en feria', brandSafe: true,
    rubros: ['otro'],
    prompt: "Market fair booth: colorful stand with products and banner, lively crowd around, bright daylight, 24mm festive wide framing, community market energy, vibrant cheerful colors, come find us at the fair." },
  { code: '/gen-repartomoto', name: 'Reparto en moto', brandSafe: true,
    rubros: ['otro'],
    prompt: "Motorbike delivery: rider with delivery box speeding through the city, dynamic motion blur, bright daylight, 35mm action framing, fast and reliable, vivid urban energy, hot and fresh to your door." },
  { code: '/gen-inventario', name: 'Stock nuevo', brandSafe: true,
    rubros: ['otro'],
    prompt: "New stock arrival: boxes of fresh products being unpacked, bright warehouse light, 35mm exciting framing, new treasures just landed, crisp clean tones, come discover what is new." },
  { code: '/gen-detalleproducto', name: 'Detalle del producto', brandSafe: true,
    rubros: ['otro'],
    prompt: "Product detail macro: exquisite texture and craftsmanship in extreme close-up, dramatic raking light, 100mm macro framing, quality you can see, rich true colors, crafted to perfection." },
  { code: '/gen-clientesaliendo', name: 'Cliente saliendo contento', brandSafe: true,
    rubros: ['otro'],
    prompt: "Customer leaving happy: client walking out with shopping bags and a smile, bright doorway light, 50mm feel-good framing, mission accomplished, warm sunny tones, see you soon." },
  { code: '/gen-promovidriera', name: 'Promo en vidriera', brandSafe: true,
    rubros: ['otro'],
    prompt: "Sale sign in the window: bold promo poster on glass with products behind, bright daylight, 35mm attention-grabbing framing, unmissable deal energy, vibrant promotional colors, limited time come in." },
  { code: '/gen-barra', name: 'La barra', brandSafe: true,
    rubros: ['otro'],
    prompt: "The counter bar: polished counter with stools, warm pendant lights above, 35mm inviting framing, cozy gathering spot, rich warm tones, pull up a chair and stay awhile." },
  { code: '/gen-horno', name: 'Recién salido del horno', brandSafe: true,
    rubros: ['otro'],
    prompt: "Fresh from the oven: steaming tray just pulled out, heat glow and rising steam, 50mm appetizing framing, irresistible fresh-baked aroma, warm golden tones, still warm come get yours." },
  { code: '/gen-entregapuerta', name: 'Entrega en puerta', brandSafe: true,
    rubros: ['otro'],
    prompt: "Doorstep delivery: package handed over at a home entrance, bright daylight, 50mm satisfying framing, delivered with a smile, clean friendly tones, right to your door." },
  { code: '/gen-equipofestejo', name: 'El equipo festeja', brandSafe: true,
    rubros: ['otro'],
    prompt: "Team celebration: staff toasting together after a big day, warm festive light, 35mm joyful framing, genuine team spirit, vibrant happy tones, the family behind the business." },
  { code: '/gen-locallluvia', name: 'Día de lluvia en el local', brandSafe: true,
    rubros: ['otro'],
    prompt: "Cozy shop on a rainy day: rain streaking the windows, warm interior glow, 50mm hygge framing, perfect shelter from the storm, amber warmth against gray, come in and get cozy." },
  { code: '/gen-terraza', name: 'La terraza', brandSafe: true,
    rubros: ['otro'],
    prompt: "Outdoor terrace: tables under string lights with happy guests, blue-hour sky, 24mm magical wide framing, perfect evening out, warm lights against dusk, your favorite spot in town." },
  { code: '/gen-cajasorpresa', name: 'Caja sorpresa', brandSafe: true,
    rubros: ['otro'],
    prompt: "Mystery box reveal: hands opening a beautifully packed surprise box, soft excited light, 50mm anticipation framing, wonder in every layer, delightful vibrant tones, unbox the unexpected." },
  { code: '/gen-productomanos', name: 'Producto en manos', brandSafe: true,
    rubros: ['otro'],
    prompt: "Product in hands: customer holding the item up naturally, soft daylight, 50mm authentic framing, real-life scale and feel, true honest colors, see it like you would hold it." },
  { code: '/gen-apertura', name: 'Día de apertura', brandSafe: true,
    rubros: ['otro'],
    prompt: "Grand opening day: ribbon cutting with cheering crowd, bright festive daylight, 35mm celebratory framing, dreams coming true, vibrant joyful colors, we are officially open come celebrate." },
  { code: '/gen-aniversario', name: 'Aniversario del local', brandSafe: true,
    rubros: ['otro'],
    prompt: "Store anniversary: decorated shop with balloons and happy staff, warm celebratory light, 35mm festive framing, years of thanks, joyful vibrant tones, celebrating with our community." },
  { code: '/gen-temporada', name: 'Llegó la temporada', brandSafe: true,
    rubros: ['otro'],
    prompt: "New season launch: fresh seasonal products artfully displayed, bright crisp light, 35mm exciting framing, the best of the season has arrived, fresh vibrant colors, discover the new collection." },
  { code: '/gen-gracias', name: 'Gracias por elegirnos', brandSafe: true,
    rubros: ['otro'],
    prompt: "Thank-you moment: handwritten thank-you card beside a small gift, soft warm light, 50mm heartfelt framing, genuine gratitude, tender warm tones, thank you for choosing us." },
];
