module.exports = [
  { code: '/prof-reunioncliente', name: 'Reunión con cliente', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Client meeting in a bright modern office: consultant and client reviewing documents across a wooden table, soft daylight from large windows, 35mm natural framing, engaged expressions, trustworthy professional warmth, clean corporate tones, productive collaborative energy." },
  { code: '/prof-firma', name: 'Firma de documentos', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Document signing close-up: elegant pen touching paper on a polished desk, hands of two people in frame, soft window light with shallow depth of field, 50mm macro detail, decisive professional moment, warm trustworthy tones, important agreement sealed." },
  { code: '/prof-oficinamoderna', name: 'Oficina moderna', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Modern office interior with floor-to-ceiling windows: sleek desks and designer chairs in morning light, city view softly blurred, 24mm wide architectural framing, inspiring productive atmosphere, clean neutral palette, aspirational workspace, bright corporate elegance." },
  { code: '/prof-videollamada', name: 'Consultoría por video', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Video consultation scene: professional smiling at a laptop camera in a tidy home office, soft ring-light glow on face, 50mm screen-side framing, warm approachable demeanor, modern remote-work aesthetic, crisp clean tones, trusted digital advisor." },
  { code: '/prof-apreton', name: 'Apretón de manos', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Handshake sealing a deal: two professionals shaking hands across a desk, bright office bokeh behind, 50mm tight framing on joined hands, warm natural window light, trust and agreement, crisp professional tones, successful partnership moment." },
  { code: '/prof-bibliotecalegal', name: 'Biblioteca jurídica', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Law office library wall: towering shelves of legal volumes in warm lamplight, leather chair in foreground, 35mm rich interior framing, scholarly gravitas, deep browns and amber glow, established prestigious practice, timeless legal authority." },
  { code: '/prof-escritoriominimal', name: 'Escritorio minimalista', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Minimalist desk flat-lay from above: laptop, notebook and coffee arranged with precision, soft even daylight, 50mm top-down composition, calm organized productivity, clean white and wood tones, modern professional clarity, satisfying visual order." },
  { code: '/prof-pizarra', name: 'Presentación en pizarra', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Strategy presentation at a glass whiteboard: consultant sketching growth charts, marker in hand, bright office light, 35mm dynamic framing, engaged team watching, confident expertise, clean corporate blues and whites, decisive business momentum." },
  { code: '/prof-impuestos', name: 'Temporada de impuestos', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Tax season workspace: calculator, organized receipts and laptop on a desk, warm desk-lamp glow in evening light, 50mm detailed framing, diligent focused atmosphere, trustworthy financial order, warm professional tones, stress-free expert handling." },
  { code: '/prof-equipo', name: 'Equipo de trabajo', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Professional team portrait in a bright loft office: diverse colleagues laughing together, large windows with soft daylight, 35mm group framing, genuine camaraderie, modern collaborative culture, vibrant natural tones, united expert team." },
  { code: '/prof-despachoventana', name: 'Despacho con vista', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Executive office with panoramic window view: polished desk facing the city skyline, soft morning light streaming in, 24mm wide framing, powerful calm authority, clean sophisticated tones, prestigious corner-office presence, inspiring leadership." },
  { code: '/prof-notarial', name: 'Firma notarial', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Notarial signing ceremony: official stamping documents at an elegant wooden desk, warm focused lamplight, 50mm formal framing, solemn professional gravity, rich wood and gold tones, legal certainty, trusted institutional moment." },
  { code: '/prof-mesaredonda', name: 'Mesa de trabajo', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Round-table work session: professionals collaborating over open laptops and papers, bright meeting-room daylight, 35mm inclusive framing, animated discussion, modern teamwork energy, clean bright tones, productive collective intelligence." },
  { code: '/prof-cafecliente', name: 'Café con cliente', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Casual client coffee meeting: two professionals chatting over cappuccinos at a sunny cafe table, soft natural window light, 50mm relaxed framing, genuine smiles, approachable trusted advisor, warm inviting tones, relationship-first business." },
  { code: '/prof-oficinanocturna', name: 'Oficina de noche', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Office at night with city lights: single desk lamp glowing in a dark modern workspace, blue-hour skyline through glass, 35mm moody framing, dedicated late-work ethic, deep blues with warm accent, committed professional hustle." },
  { code: '/prof-archivo', name: 'Archivo y expedientes', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Organized case files on wooden shelves: labeled binders in neat rows under warm office light, 35mm depth-filled framing, meticulous professional order, trustworthy systematic practice, warm amber tones, decades of expertise archived." },
  { code: '/prof-tabletcontrato', name: 'Contrato en tablet', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Digital contract review on a tablet: professional hands holding tablet with document, stylus poised, soft office daylight, 50mm modern framing, paperless efficiency, clean tech-forward tones, seamless digital professionalism." },
  { code: '/prof-mentoria', name: 'Mentoría uno a uno', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "One-on-one mentoring session: senior advisor listening intently across a small table, warm natural light, 50mm intimate framing, attentive caring expression, trusted guidance, soft warm tones, personal professional growth." },
  { code: '/prof-conferencia', name: 'Conferencia en escenario', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Keynote speaker on a conference stage: presenter gesturing before a large audience, dramatic stage lighting with spotlight, 70-200mm telephoto framing, commanding expertise, deep blues with bright accent, influential thought leadership." },
  { code: '/prof-networking', name: 'Evento de networking', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Networking event with professionals mingling: champagne glasses and animated conversation in an elegant venue, warm ambient event lighting, 35mm lively framing, valuable connections forming, sophisticated golden tones, thriving business community." },
  { code: '/prof-despachoclasico', name: 'Despacho clásico', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Classic wood-paneled private office: leather chairs and brass lamp in warm lamplight, 35mm timeless framing, distinguished traditional prestige, rich mahogany and green tones, old-school professional gravitas, heritage of trust." },
  { code: '/prof-coworking', name: 'Espacio coworking', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Vibrant coworking space: freelancers working at long shared tables, abundant natural light from skylights, 24mm wide energetic framing, creative collaborative buzz, bright modern tones, dynamic independent professional community." },
  { code: '/prof-llamada', name: 'Llamada con cliente', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Important phone call: professional speaking intently by a bright office window, city softly blurred, 50mm focused framing, soft daylight on face, decisive communication, clean professional tones, trusted advisor in action." },
  { code: '/prof-laptopcafe', name: 'Trabajando desde café', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Working remotely from a cafe: laptop open beside a latte on a marble table, soft morning window light, 50mm cozy framing, relaxed productive freedom, warm inviting tones, modern flexible professional lifestyle." },
  { code: '/prof-lupa', name: 'Revisión de documentos', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Document review with magnifying glass: careful hands examining fine print under a bright desk lamp, 50mm macro detail framing, meticulous professional scrutiny, warm focused light, precision and diligence, trusted expert thoroughness." },
  { code: '/prof-firmadigital', name: 'Firma digital', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Digital signature moment: finger tapping sign on a tablet screen, glowing interface in soft office light, 50mm close framing, seamless modern transaction, clean blue and white tones, effortless paperless professionalism." },
  { code: '/prof-reunionvirtual', name: 'Reunión virtual de equipo', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Virtual team meeting on screen: grid of smiling colleagues in a video call, warm monitor glow in a home office, 50mm screen-focused framing, connected remote collaboration, friendly digital tones, united distributed team." },
  { code: '/prof-oficinaverde', name: 'Oficina con plantas', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Office filled with plants: green foliage softening a modern workspace, gentle daylight filtering through leaves, 35mm fresh framing, calm healthy work environment, vibrant natural greens, balanced mindful professionalism." },
  { code: '/prof-desdearriba', name: 'Escritorio desde arriba', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Overhead desk composition: open planner, pen and coffee from directly above, soft even window light, 50mm geometric flat-lay, organized productive day, clean minimal tones, satisfying professional ritual." },
  { code: '/prof-teclado', name: 'Manos en el teclado', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Hands typing on a backlit laptop keyboard: close-up with screen glow in a dim office, 50mm shallow depth of field, focused productive flow, cool blue tones with warm accent, dedicated professional momentum." },
  { code: '/prof-edificio', name: 'Edificio corporativo', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Corporate headquarters at blue hour: glass tower reflecting the sunset sky, dramatic low-angle view, 24mm architectural framing, prestigious established firm, deep blues and warm reflections, impressive professional landmark." },
  { code: '/prof-lobby', name: 'Lobby corporativo', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Elegant corporate lobby: marble floors and modern art under warm recessed lighting, 24mm grand wide framing, welcoming prestigious first impression, sophisticated neutral tones, established trustworthy institution." },
  { code: '/prof-salajuntas', name: 'Sala de juntas', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Boardroom ready for a meeting: long polished table with chairs, skyline view through glass walls, soft morning light, 24mm spacious framing, decisive corporate atmosphere, clean powerful tones, where important decisions happen." },
  { code: '/prof-tribunales', name: 'Frente a tribunales', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Lawyer ascending courthouse steps: confident stride with briefcase, dramatic morning light on classical columns, 35mm powerful framing, determined professional purpose, strong contrast tones, justice and advocacy in motion." },
  { code: '/prof-cierremes', name: 'Cierre de mes contable', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Month-end accounting close: spreadsheets and calculator under warm evening desk light, 50mm focused framing, diligent financial precision, calm organized intensity, warm professional tones, numbers handled with expert care." },
  { code: '/prof-whiteboard', name: 'Estrategia en whiteboard', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Business strategy on a whiteboard: consultant drawing market diagrams with colored markers, bright collaborative light, 35mm energetic framing, sharp strategic thinking, clean vibrant tones, expert roadmap taking shape." },
  { code: '/prof-amanecer', name: 'Oficina al amanecer', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Empty office at sunrise: first golden light hitting desks through tall windows, 24mm serene wide framing, fresh ambitious morning, warm gold and soft blue tones, new day of professional possibility." },
  { code: '/prof-libroscontables', name: 'Libros contables', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Classic accounting ledgers: open leather-bound books with neat handwritten figures, warm lamplight on an old desk, 50mm nostalgic detail, timeless financial trust, rich sepia tones, generations of careful bookkeeping." },
  { code: '/prof-asesoria', name: 'Asesoría personalizada', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Personalized advisory session: consultant explaining charts to a client one-on-one, warm natural office light, 50mm attentive framing, clear caring guidance, soft trustworthy tones, expert advice tailored to you." },
  { code: '/prof-entrega', name: 'Entrega de resultados', brandSafe: true,
    rubros: ['profesionales'],
    prompt: "Delivering results to a client: professional handing over a finished report with a smile, bright office daylight, 50mm satisfying framing, successful outcome, clean confident tones, promises kept, expertise delivered." },
];
