module.exports = [
  { code: "/salud-sonrisafinal", name: "Sonrisa post tratamiento dental", brandSafe: true,
    rubros: ["salud"],
    prompt: "Patient with a radiant confident smile after dental treatment, dentist blurred behind giving thumbs up, bright clinic lighting, 85mm tight portrait, transformative dental-result photography, fine detail in highlights and shadows, premium magazine look." },
  { code: "/salud-consultoriolimpio", name: "Consultorio minimal y luminoso", brandSafe: true,
    rubros: ["salud"],
    prompt: "Minimalist medical office with white walls, light wood desk and a single orchid, soft daylight from large window, 24mm wide architectural shot, calm trustworthy clinic photography." },
  { code: "/salud-kinesiosesion", name: "Sesión de kinesiología en camilla", brandSafe: true,
    rubros: ["salud"],
    prompt: "Kinesiologist guiding a patient's shoulder mobilization on a treatment table, focused professional hands, bright therapy room light, 50mm medium shot, expert rehabilitation photography, soft glow on key surfaces, harmonious balanced composition." },
  { code: "/salud-limpiezadental", name: "Limpieza dental profesional", brandSafe: true,
    rubros: ["salud"],
    prompt: "Dental hygienist polishing a patient's teeth with modern equipment, patient relaxed, bright operatory lamp, 60mm clinical close shot, preventive dental-care photography, crisp focus with creamy bokeh, high-end production value." },
  { code: "/salud-ortodoncia", name: "Control de ortodoncia", brandSafe: true,
    rubros: ["salud"],
    prompt: "Orthodontist adjusting a teenager's colorful braces, teen smiling in the dental chair, bright friendly lighting, 60mm close shot, positive orthodontic photography, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/salud-masajeterapeutico", name: "Masaje terapéutico de espalda", brandSafe: true,
    rubros: ["salud"],
    prompt: "Therapist's hands massaging a patient's back with oil, warm dim spa lighting, candles blurred, 60mm close detail shot, deeply relaxing therapeutic photography, gentle atmospheric haze adds depth, vivid natural color grading." },
  { code: "/salud-fisiobanda", name: "Fisioterapia con bandas elásticas", brandSafe: true,
    rubros: ["salud"],
    prompt: "Patient doing resistance-band shoulder rehab guided by a physiotherapist correcting form, bright modern gym-clinic with mirrors, 50mm medium shot, active recovery photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/salud-ecografiamedica", name: "Ecografía médica con explicación", brandSafe: true,
    rubros: ["salud"],
    prompt: "Doctor showing ultrasound images on a monitor to a patient, pointing at the screen, dim exam room with screen glow, 50mm medium shot, clear diagnostic photography." },
  { code: "/salud-consultanutri", name: "Consulta con nutricionista", brandSafe: true,
    rubros: ["salud"],
    prompt: "Nutritionist reviewing a colorful meal plan with a client across a desk, fresh foods on the table, bright office daylight, 50mm medium shot, friendly nutrition photography." },
  { code: "/salud-chequeocardio", name: "Chequeo cardiológico", brandSafe: true,
    rubros: ["salud"],
    prompt: "Cardiologist listening to a patient's heart with a stethoscope, patient calm on exam table, clean bright lighting, 50mm medium shot, reassuring cardiac-care photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/salud-consultaderma", name: "Consulta dermatológica", brandSafe: true,
    rubros: ["salud"],
    prompt: "Dermatologist examining a patient's skin with a dermatoscope pressed gently to the cheek, magnified detail on screen, bright clinical lamp, 60mm close shot, precise skin-health photography." },
  { code: "/salud-pediatriajuego", name: "Pediatría: control con juego", brandSafe: true,
    rubros: ["salud"],
    prompt: "Pediatrician playfully examining a laughing toddler with a toy stethoscope, colorful kid-friendly office, bright cheerful light, 50mm medium shot, warm pediatric photography, clean background separation, professional commercial polish throughout." },
  { code: "/salud-examenvisual", name: "Examen visual en óptica", brandSafe: true,
    rubros: ["salud"],
    prompt: "Optometrist testing a patient's vision with a phoropter, eye chart glowing behind, dim exam room, 50mm medium shot, professional eye-care photography, delicate rim light defines edges, refined editorial finish." },
  { code: "/salud-audiometria", name: "Audiometría en cabina", brandSafe: true,
    rubros: ["salud"],
    prompt: "Patient wearing headphones in a soundproof audiometry booth, audiologist observing through glass, soft clinical lighting, 50mm medium shot, precise hearing-test photography, natural vignette draws the eye, authentic documentary feel." },
  { code: "/salud-vacunatorio", name: "Vacunatorio: aplicación sin dolor", brandSafe: true,
    rubros: ["salud"],
    prompt: "Nurse gently vaccinating a relaxed adult patient, patient looking away smiling, bright clean vaccination room, 50mm medium shot, calm immunization photography, fine detail in highlights and shadows, premium magazine look." },
  { code: "/salud-laboratorio", name: "Laboratorio de análisis clínicos", brandSafe: true,
    rubros: ["salud"],
    prompt: "Lab technician handling labeled blood sample tubes, modern analyzer machines behind, cool clean lighting, 50mm medium shot, high-tech laboratory photography, soft glow on key surfaces, harmonious balanced composition." },
  { code: "/salud-radiografia", name: "Sala de rayos X moderna", brandSafe: true,
    rubros: ["salud"],
    prompt: "Modern X-ray suite with digital panel and patient positioned comfortably, technician at console, cool clinical lighting, 35mm wide shot, advanced imaging photography, crisp focus with creamy bokeh, high-end production value." },
  { code: "/salud-quiropraxia", name: "Ajuste quiropráctico", brandSafe: true,
    rubros: ["salud"],
    prompt: "Chiropractor performing a precise spinal adjustment on a patient lying face down, serene clinic, soft focused lighting, 50mm medium shot, expert chiropractic photography, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/salud-psicologiasesion", name: "Sesión de psicología cálida", brandSafe: true,
    rubros: ["salud"],
    prompt: "Warm therapy office with two armchairs facing each other, tissue box and plant, soft lamp light, empty chairs, 35mm wide shot, safe-space psychology photography, gentle atmospheric haze adds depth, vivid natural color grading." },
  { code: "/salud-fonoaudiologia", name: "Sesión de fonoaudiología infantil", brandSafe: true,
    rubros: ["salud"],
    prompt: "Speech therapist playing articulation games with a child using picture cards, bright playful room, 50mm medium shot, joyful speech-therapy photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/salud-podologia", name: "Tratamiento de podología", brandSafe: true,
    rubros: ["salud"],
    prompt: "Podiatrist treating a patient's foot with professional instruments, patient relaxed in recliner, bright clinical light, 60mm close detail shot, careful foot-care photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/salud-odontopediatria", name: "Odontopediatría sin miedo", brandSafe: true,
    rubros: ["salud"],
    prompt: "Child giggling in a colorful dental chair while the dentist shows a mirror, cartoon murals on walls, bright cheerful light, 50mm medium shot, fear-free kids-dental photography." },
  { code: "/salud-implantedental", name: "Implante dental: tecnología 3D", brandSafe: true,
    rubros: ["salud"],
    prompt: "Dentist showing a 3D implant model to a patient, digital scan on screen behind, bright modern operatory, 50mm medium shot, cutting-edge implant photography, clean background separation, professional commercial polish throughout." },
  { code: "/salud-blanqueamiento", name: "Blanqueamiento dental", brandSafe: true,
    rubros: ["salud"],
    prompt: "Patient with whitening lamp over their smile in a spa-like dental room, relaxed with sunglasses on, soft blue light glow, 60mm close shot, aesthetic whitening photography." },
  { code: "/salud-recepcionclinica", name: "Recepción de la clínica", brandSafe: true,
    rubros: ["salud"],
    prompt: "Welcoming clinic reception with light wood counter, smiling receptionist and green wall, bright daylight, 35mm wide shot, hospitality-grade medical photography, delicate rim light defines edges, refined editorial finish." },
  { code: "/salud-sillondental", name: "Sillón dental de última generación", brandSafe: true,
    rubros: ["salud"],
    prompt: "State-of-the-art dental chair with monitor arm and sleek instruments, pristine operatory, bright even lighting, 35mm wide shot, premium dental-equipment photography, natural vignette draws the eye, authentic documentary feel." },
  { code: "/salud-equipokinesio", name: "Gimnasio de kinesiología equipado", brandSafe: true,
    rubros: ["salud"],
    prompt: "Physiotherapy gym with parallel bars, therapy balls, resistance stations and treatment tables, bright airy space with daylight, 24mm wide shot, professional rehab-facility photography, fine detail in highlights and shadows, premium magazine look." },
  { code: "/salud-terapiaocupacional", name: "Terapia ocupacional con actividades", brandSafe: true,
    rubros: ["salud"],
    prompt: "Occupational therapist guiding a patient through fine-motor pegboard exercises, encouraging smiles, bright therapy room, 50mm medium shot, purposeful rehab photography, soft glow on key surfaces, harmonious balanced composition." },
  { code: "/salud-platosaludable", name: "Plato saludable de la nutricionista", brandSafe: true,
    rubros: ["salud"],
    prompt: "Perfectly balanced plate with grilled chicken, quinoa and rainbow vegetables, nutritionist's hands presenting it, bright daylight, 60mm overhead food shot, appetizing nutrition photography, crisp focus with creamy bokeh, high-end production value." },
  { code: "/salud-yogaterapeutico", name: "Yoga terapéutico para la espalda", brandSafe: true,
    rubros: ["salud"],
    prompt: "Instructor guiding gentle spinal twists in a therapeutic yoga class, props and bolsters, soft morning light, 35mm wide shot, healing yoga photography, soft bounced fill keeps shadows open, warm editorial color grading." },
  { code: "/salud-meditacionguiada", name: "Meditación guiada en el centro", brandSafe: true,
    rubros: ["salud"],
    prompt: "Group meditating cross-legged in a serene studio with eyes closed, candles flickering and soft warm light, 35mm wide elevated shot, tranquil mindfulness photography, gentle atmospheric haze adds depth, vivid natural color grading." },
  { code: "/salud-controlpresion", name: "Control de presión arterial", brandSafe: true,
    rubros: ["salud"],
    prompt: "Nurse measuring a patient's blood pressure with a digital cuff, patient relaxed, bright consulting room, 50mm medium shot, routine check-up photography, subtle lens flare and crisp detail, cinematic warm tones." },
  { code: "/salud-electrocardiograma", name: "Electrocardiograma en consultorio", brandSafe: true,
    rubros: ["salud"],
    prompt: "Technician placing ECG electrodes on a patient's chest, heart trace on monitor, calm clinical lighting, 50mm medium shot, precise cardiac-diagnostic photography, balanced exposure with rich texture detail, inviting warm palette." },
  { code: "/salud-drenajelinfatico", name: "Drenaje linfático manual", brandSafe: true,
    rubros: ["salud"],
    prompt: "Therapist performing gentle lymphatic drainage on a patient's leg with light feathered strokes, soft spa lighting and calm tones, 60mm close detail shot, delicate wellness photography." },
  { code: "/salud-acupuntura", name: "Sesión de acupuntura", brandSafe: true,
    rubros: ["salud"],
    prompt: "Patient relaxed face-down with fine acupuncture needles along the back, dim serene room with warm lamps, 60mm close shot, tranquil acupuncture photography, clean background separation, professional commercial polish throughout." },
  { code: "/salud-rehabpostquirurgica", name: "Rehabilitación post quirúrgica", brandSafe: true,
    rubros: ["salud"],
    prompt: "Physiotherapist assisting a patient's first steps with parallel bars after knee surgery, determined expressions, bright rehab gym, 50mm medium shot, hopeful recovery photography, delicate rim light defines edges, refined editorial finish." },
  { code: "/salud-chequeoanual", name: "Chequeo anual integral", brandSafe: true,
    rubros: ["salud"],
    prompt: "Doctor reviewing annual check-up results with a patient, charts and a healthy-lifestyle brochure on desk, bright office light, 50mm medium shot, preventive-care photography, natural vignette draws the eye, authentic documentary feel." },
  { code: "/salud-telemedicina", name: "Consulta por telemedicina", brandSafe: true,
    rubros: ["salud"],
    prompt: "Doctor on a video call with a patient shown on a laptop, warm home-office lighting, 50mm over-shoulder shot, modern telehealth photography, fine detail in highlights and shadows, premium magazine look." },
  { code: "/salud-sonrisaniño", name: "Sonrisa sana de un niño", brandSafe: true,
    rubros: ["salud"],
    prompt: "Child with a big healthy smile holding a toothbrush, dentist giving thumbs up behind, bright cheerful clinic light, 85mm portrait, joyful kids-dental photography, soft glow on key surfaces, harmonious balanced composition." },
  { code: "/salud-higienepostural", name: "Taller de higiene postural", brandSafe: true,
    rubros: ["salud"],
    prompt: "Ergonomics workshop with participants adjusting office chairs and monitors, instructor demonstrating posture, bright training room, 35mm wide shot, workplace-wellness photography, crisp focus with creamy bokeh, high-end production value." },
];
