module.exports = [
  { code: '/serv-tableroelectrico', name: 'Tablero eléctrico', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Neat electrical panel with labeled breakers and color-coded wires perfectly routed, electrician hand closing the cover, bright task lighting, macro detail, order and safety you can see.' },
  { code: '/serv-soldadura', name: 'Soldadura', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Welding sparks flying in bright orange arcs from the electrode point, welder masked silhouette behind, dark workshop with dramatic contrast, high-speed frozen motion, raw trade craftsmanship.' },
  { code: '/serv-herramientasorden', name: 'Herramientas en orden', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Perfectly organized trade tools laid out top-down on a dark mat: wrenches, pliers and drivers in size order, soft even overhead light, symmetrical flat composition, a professional discipline on display.' },
  { code: '/serv-airesplit', name: 'Aire split instalado', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Technician mounting a split AC indoor unit on a living room wall, level tool and drill nearby, bright daylight from the window, clean installation composition, cool comfort taking shape.' },
  { code: '/serv-griferia', name: 'Grifería nueva', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Plumber hands tightening a modern chrome faucet onto a bathroom sink, fresh water droplets sparkling on metal, bright bathroom lighting, macro detail composition, the small upgrade that changes the whole room.' },
  { code: '/serv-destapacion', name: 'Destapación', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Drain cleaning machine with steel cable feeding into a floor drain, technician guiding it with gloves, bright basement lighting, action composition, the unglamorous rescue every home needs.' },
  { code: '/serv-termotanque', name: 'Termotanque instalado', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Brand-new water heater installed in a tidy utility room, copper pipes and safety valves neatly connected, bright even lighting, clean three-quarter composition, endless hot water guaranteed.' },
  { code: '/serv-calefon', name: 'Calefón a gas', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Gas water heater mounted on a kitchen wall with blue flame visible through the window, technician checking connections, warm practical lighting, close technical composition, instant hot water.' },
  { code: '/serv-bombaagua', name: 'Bomba de agua', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'New water pressure pump installed beside a storage tank, pressure gauge needle sharp in focus, bright utility room lighting, macro detail composition, steady water flow for the whole house.' },
  { code: '/serv-tanquetecho', name: 'Tanque en techo', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Technician securing a rooftop water tank against a golden-hour sky, city skyline soft behind, wrench in hand, dramatic backlit wide composition, the silent guardian of the household water supply.' },
  { code: '/serv-cableado', name: 'Cableado prolijo', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Electrician pulling color-coded cables through a ceiling conduit, organized wire bundles, bright work light from below, upward angle composition, the hidden arteries of a safe home.' },
  { code: '/serv-led', name: 'Iluminación LED', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Warm LED strip glowing beneath kitchen cabinets at dusk, electrician hand fine-tuning the aluminum profile, cozy ambient lighting, close atmospheric composition, the instant upgrade that transforms any room.' },
  { code: '/serv-portero', name: 'Portero eléctrico', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Video intercom panel being mounted beside a front door, technician leveling it with a spirit level, bright entrance lighting, clean installation composition, answering the door from anywhere in the house.' },
  { code: '/serv-camaras', name: 'Cámaras de seguridad', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Technician installing a dome security camera beneath a porch roof, drill in hand and cable routed neatly, bright daylight, upward angle including the house facade, watchful protection taking its place.' },
  { code: '/serv-alarma', name: 'Alarma instalada', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Modern alarm keypad glowing on a hallway wall, installer testing a motion sensor nearby, warm interior lighting, clean composed shot, the quiet feeling of a protected home.' },
  { code: '/serv-cerradura', name: 'Cerradura nueva', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Locksmith fitting a high-security deadbolt into a wooden door, brass mechanism in macro focus, bright entrance lighting, precise craft composition, the first line of home defense.' },
  { code: '/serv-puertablindada', name: 'Puerta blindada', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Armored security door slightly ajar in a modern hallway, steel frame and multi-point locks visible, dramatic side lighting, low-angle strong composition, serious protection with style.' },
  { code: '/serv-vidriero', name: 'Vidrio a medida', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Glazier carrying a large custom glass pane with suction cups into a bright living room, empty window frame waiting, daylight streaming through, dynamic action composition, crystal-clear transparency installed.' },
  { code: '/serv-persiana', name: 'Reparación de persiana', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Technician repairing a roller shutter mechanism with slats and spring box exposed, bright window light flooding in, close-up action composition, smooth morning light back on schedule.' },
  { code: '/serv-cortina', name: 'Cortina metálica', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Metal roller shutter half-raised on a storefront at dawn, technician adjusting the side motor, streetlight mixing with sunrise glow, urban wide composition, the business opening right on time.' },
  { code: '/serv-heladera', name: 'Reparación de heladera', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Technician with manifold gauges servicing a refrigerator compressor at the back of the unit, tools neatly laid on a mat, bright kitchen lighting, documentary angle, the week groceries saved.' },
  { code: '/serv-lavarropas', name: 'Service de lavarropas', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Washing machine with its front panel open revealing drum and hoses, technician testing circuits with a multimeter, bright laundry room lighting, technical close composition, laundry day officially rescued.' },
  { code: '/serv-cocina', name: 'Cocina instalada', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Brand-new gas stove with flexible hose connected and a level check in progress, technician hand turning a knob, bright kitchen lighting, clean installation composition, family dinner is back on.' },
  { code: '/serv-horno', name: 'Reparación de horno', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Oven door open with the heating element glowing bright orange, technician replacing it wearing heat gloves, warm kitchen lighting, close-up repair moment, baking heat fully restored.' },
  { code: '/serv-tv', name: 'TV en pared', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Large flat TV mounted on a living room wall with all cables hidden, technician tightening the final bracket bolt, bright daylight, clean symmetrical composition, private cinema ready at home.' },
  { code: '/serv-antena', name: 'Antena instalada', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Technician adjusting a rooftop antenna against a dramatic cloudy sky, signal meter in hand, bright harsh daylight, heroic low-angle composition, perfect reception captured from above.' },
  { code: '/serv-wifi', name: 'Red WiFi', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Network rack with glowing router LEDs and neatly patched cables, technician labeling each port, cool blue equipment lighting, macro technical composition, whole-home connectivity finally organized.' },
  { code: '/serv-grupo', name: 'Grupo electrógeno', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Backup generator installed beside a house with its automatic transfer switch, technician running a test start, bright clear daylight, solid three-quarter composition, electricity that never quits.' },
  { code: '/serv-solar', name: 'Paneles solares', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Solar panels being bolted onto a tiled roof at golden hour, installer silhouette rimmed by the sun, dramatic backlit wide composition, the roof quietly harvesting clean energy.' },
  { code: '/serv-pileta', name: 'Mantenimiento de pileta', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Pool technician skimming a crystal-clear pool in the morning, water test kit and chemicals lined on the edge, sparkling daylight reflections, fresh inviting wide composition, swim-ready water.' },
  { code: '/serv-riego', name: 'Riego automático', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Pop-up sprinklers watering a lush green lawn at sunrise, water droplets frozen mid-air catching the light, low-angle fresh composition, the entire garden drinking right on schedule.' },
  { code: '/serv-jardin', name: 'Jardinería', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Gardener pruning an overgrown hedge into a perfect straight shape, shears mid-snip with leaves falling, bright garden daylight, satisfying action composition, nature brought under expert control.' },
  { code: '/serv-fumigacion', name: 'Fumigación', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Pest control technician spraying a fine protective mist along a baseboard, full protective gear on, dramatic side lighting in a dim room, professional action composition, unwanted guests officially evicted.' },
  { code: '/serv-tanque', name: 'Limpieza de tanque', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Technician inside a scrubbed water tank with brush and hose, interior walls gleaming wet, bright work light inside the tank, unusual immersive angle, drinking water you can trust.' },
  { code: '/serv-membrana', name: 'Impermeabilización', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Worker rolling liquid waterproof membrane across a flat roof, glossy black coating half-applied in a clean line, bright midday sun, wide process composition, the next storm has no chance.' },
  { code: '/serv-emergencia', name: 'Emergencia 24h', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Service van with amber beacons glowing on a dark street at night, technician walking to a doorway with toolbox, dramatic night lighting, cinematic wide shot, help on the way.' },
  { code: '/serv-presupuesto', name: 'Presupuesto en el acto', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Uniformed technician showing a clear digital quote on a tablet to a homeowner at their door, friendly natural daylight, over-the-shoulder composition, transparent pricing agreed before any work begins.' },
  { code: '/serv-equipo', name: 'Equipo uniformado', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Team of uniformed technicians standing confidently beside their equipped service van, bright morning light, strong symmetrical group composition, the crew every homeowner wants at their door.' },
  { code: '/serv-garantia', name: 'Trabajo garantizado', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Technician shaking hands with a smiling homeowner in a finished room, the completed installation gleaming behind them, warm natural light, genuine documentary composition, done right and fully backed up.' },
  { code: '/serv-detallefinal', name: 'Detalle final', brandSafe: true,
    rubros: ['servicios'],
    prompt: 'Technician giving a finished installation its final wipe-down with a microfiber cloth, the spotless result sharp in focus, bright clean lighting, macro pride composition, the signature of a job well done.' },
];
