module.exports = [
  { code: '/tech-celularroto', name: 'Pantalla trizada', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Extreme macro of a shattered smartphone screen, spiderweb cracks catching dramatic side light on a dark background, shallow depth of field, the painful moment every great repair starts from.' },
  { code: '/tech-reparacionmesa', name: 'Mesa de técnico', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Technician repair bench with microscope, hot air station and precision tools, phone motherboard under the lens, bright task lighting, top-down craft composition, surgery for electronics.' },
  { code: '/tech-setupgamer', name: 'Setup gamer', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Gaming setup glowing with synchronized RGB: curved monitor, mechanical keyboard and a glass-panel PC tower, dark room filled with neon reflections, wide cinematic composition, the ultimate battlestation dream.' },
  { code: '/tech-pantallacelu', name: 'Cambio de pantalla', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Technician carefully placing a new OLED screen onto a phone frame with fine tweezers, bright magnifier lamp overhead, macro precision composition, the rebirth of a beloved phone.' },
  { code: '/tech-bateriacelu', name: 'Batería nueva', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'New smartphone battery placed beside the swollen old one on an anti-static mat, precision tools arranged around, bright bench lighting, revealing macro comparison, full power restored safely.' },
  { code: '/tech-placa', name: 'Reparación de placa', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Phone motherboard under a stereo microscope with a micro-soldering iron touching a tiny chip, bright ring-light illumination, extreme macro composition, invisible repairs happening at the edge of sight.' },
  { code: '/tech-microsoldadura', name: 'Microsoldadura', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Soldering iron tip joining microscopic components with a delicate wisp of smoke, flux glistening under intense magnifier lighting, extreme close-up composition, where the steadiest hands meet the tiniest worlds.' },
  { code: '/tech-ultrasonido', name: 'Limpieza profunda', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Water-damaged circuit board submerged in an ultrasonic cleaner with rippling solution, technician lifting it with tweezers, cool blue backlight glowing, macro technical composition, corrosion washed completely away.' },
  { code: '/tech-datos', name: 'Recuperación de datos', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Technician connecting a damaged drive to a data recovery workstation, progress bars glowing on surrounding monitors, dim lab lit by screen glow, tense documentary composition, precious memories rescued from dead hardware.' },
  { code: '/tech-notebook', name: 'Service de notebook', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Laptop opened on a repair bench with its bottom cover removed, technician cleaning the cooling fan with a brush, bright task lighting, clear technical angle, the daily workhorse getting its tune-up.' },
  { code: '/tech-teclado', name: 'Teclado nuevo', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'New laptop keyboard being carefully fitted into the chassis, backlit keys catching soft light, technician precise fingers at work, macro detail composition, the pleasure of typing fully restored.' },
  { code: '/tech-pantallanb', name: 'Pantalla de notebook', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Replacement laptop screen displaying vivid test colors beside the cracked old panel, bright bench lighting, side-by-side comparison composition, the dramatic upgrade you notice in one second.' },
  { code: '/tech-limpiezainterna', name: 'Limpieza interna', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Cloud of dust erupting from a laptop heatsink under compressed air, masked technician holding the nozzle, bright backlight cutting through the dust, dramatic macro moment, the hidden dirt that was slowing everything.' },
  { code: '/tech-pasta', name: 'Pasta térmica', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Fresh thermal paste applied in a perfect dot on a polished CPU, syringe tip sharp in macro focus, bright ring-light illumination, extreme close-up composition, a few degrees that change absolutely everything.' },
  { code: '/tech-pcarmada', name: 'PC armada a medida', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Custom PC build in progress with components laid out around an open tempered-glass case, builder routing cables with care, bright room lighting, wide enthusiast composition, raw power assembled entirely by hand.' },
  { code: '/tech-gabinete', name: 'Gabinete con estilo', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Tempered-glass PC case glowing with synchronized RGB fans inside, immaculate cable management, dark room filled with color reflections, dramatic low-angle composition, computer hardware as interior design.' },
  { code: '/tech-gpu', name: 'Placa de video', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'High-end graphics card with triple cooling fans resting on a dark surface, subtle RGB accents glowing, dramatic rim lighting, low-angle hero composition, the beating engine of every great game.' },
  { code: '/tech-ssd', name: 'Upgrade a SSD', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'NVMe SSD being slotted into a motherboard M.2 slot, precision screwdriver waiting nearby, bright macro lighting, extreme close-up composition, the five-minute upgrade that feels like a brand-new computer.' },
  { code: '/tech-ram', name: 'Más memoria RAM', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'DDR memory sticks being clicked into motherboard slots, gold contacts catching the light, technician thumbs pressing evenly, bright macro lighting, satisfying close-up, multitasking without mercy.' },
  { code: '/tech-fuente', name: 'Fuente de poder', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Modular power supply with braided cables fanned neatly on a bench, certification labels clearly readable, bright even lighting, clean product composition, stable silent energy for the entire system.' },
  { code: '/tech-watercooling', name: 'Refrigeración líquida', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Custom water-cooling loop with glowing coolant flowing through crystal-clear tubes, pump and radiator artfully visible, dark room with ultraviolet accents, mesmerizing macro composition, silence with sub-zero style.' },
  { code: '/tech-perifericos', name: 'Periféricos', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Backlit mechanical keyboard and precision gaming mouse arranged on a large desk mat, RGB glow reflecting, dramatic low lighting, shallow-focus composition, the essential tools of digital precision.' },
  { code: '/tech-monitor', name: 'Monitor', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Ultrawide curved monitor displaying a vivid colorful workspace, slim bezels catching soft ambient light, dark stylish room, wide cinematic composition, the screen real estate that changes how you work.' },
  { code: '/tech-silla', name: 'Silla gamer', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Ergonomic gaming chair photographed in an RGB-lit room, dramatic side lighting sculpting the premium upholstery, lumbar pillow and 4D armrests in sharp focus, low-angle hero composition, the throne built for marathon sessions.' },
  { code: '/tech-consola', name: 'Service de consola', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Game console opened on a workbench with its internals fully exposed, technician cleaning the disc drive mechanism, bright task lighting, geeky technical composition, Friday game night officially saved.' },
  { code: '/tech-joystick', name: 'Joystick reparado', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Game controller with its shell open revealing the thumbstick modules, technician replacing the drifted sticks, bright macro lighting, satisfying close-up composition, precise aim fully restored.' },
  { code: '/tech-tablet', name: 'Reparación de tablet', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Tablet with its glass digitizer lifting off on a heated separator machine, technician careful gloved hands guiding it, warm machine glow, macro repair moment, the big screen lives again.' },
  { code: '/tech-smartwatch', name: 'Smartwatch', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Smartwatch with cracked glass lying beside precision opening tools on a repair mat, tiny screws sorted in a tray, bright macro lighting, miniature watchmaker composition, wrist technology revived.' },
  { code: '/tech-auriculares', name: 'Auriculares', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Premium over-ear headphones displayed on a stand with dramatic side lighting, stitched leather cushions in macro detail, dark elegant background, product hero composition, sound quality you can almost see.' },
  { code: '/tech-parlante', name: 'Parlante', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Portable bluetooth speaker with woven fabric texture in extreme macro, subtle LED ring glowing softly, moody dark background with rim lighting, product hero composition, the entire party inside a compact box.' },
  { code: '/tech-impresora', name: 'Service de impresora', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Office printer with open panels revealing the ink system, technician replacing cartridges with fresh ones, bright office lighting, documentary angle composition, the office lifeline back online.' },
  { code: '/tech-rack', name: 'Redes y rack', brandSafe: true,
    rubros: ['tecnologia', 'servicios'],
    prompt: 'Server rack with blinking status LEDs and color-coded patch cables, technician crimping a fresh connector, cool blue data-center lighting, technical wide composition, the invisible backbone of the business.' },
  { code: '/tech-camaraip', name: 'Cámara IP', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'IP security camera mounted under a roof eave at dusk, infrared LEDs glowing faint red, installer fine-tuning the angle on a ladder, moody evening light, watchful wide composition, eyes that never blink.' },
  { code: '/tech-drone', name: 'Drone', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Camera drone with propellers spread wide on a launch pad, pilot holding the controller nearby, golden-hour light over an open field, dynamic low-angle composition, cinematic perspectives waiting to take flight.' },
  { code: '/tech-vitrina', name: 'Vitrina de accesorios', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Retail display wall with phone cases, chargers and gadgets arranged in perfect rows, bright commercial spotlights, wide commercial composition, everything a device could need captured in one glance.' },
  { code: '/tech-fundas', name: 'Fundas', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Colorful phone cases fanned across a bright studio surface, textures and graphic designs clearly visible, soft even lighting, playful product composition, personality-packed protection for every phone.' },
  { code: '/tech-cargadores', name: 'Carga rápida', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'GaN fast chargers and braided cables coiled neatly on a dark surface, wattage labels clearly readable, dramatic product lighting, clean commercial composition, dead-battery anxiety permanently cured.' },
  { code: '/tech-local', name: 'Nuestro local', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Modern tech repair shop storefront with glowing signage at dusk, display windows full of devices and accessories, warm inviting interior light spilling out, wide establishing composition, the neighborhood trusted gadget hospital.' },
  { code: '/tech-retiro', name: 'Retiro a domicilio', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Courier handing a carefully packed repaired laptop to a smiling customer at their door, branded protective packaging, bright natural daylight, friendly documentary moment, expert repair without leaving home.' },
  { code: '/tech-garantia', name: 'Garantía escrita', brandSafe: true,
    rubros: ['tecnologia'],
    prompt: 'Technician handing a stamped warranty card along with the repaired phone, relieved customer smiling, bright shop lighting, trust-building close composition, every repair backed in writing.' },
];
