// image-styles-rubros/turismo.js — Presets de estilos de imagen: TURISMO (hotelería, agencias, destinos).
// 40 presets. Formato: { code, name, brandSafe, rubros[], prompt }
// code único global con prefijo '/turi-'. Todos brandSafe: fotografía real que respeta el destino.
'use strict';

module.exports = [
  { code: '/turi-habitacionvista', name: 'Habitación con vista', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Hotel room photography: elegant bedroom with the bed facing panoramic windows over the sea, soft morning light, 24mm wide-angle, crisp white linens, breakfast tray waiting, wake-up-to-paradise luxury.' },
  { code: '/turi-desayunobandeja', name: 'Desayuno en bandeja', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Breakfast tray photography: lavish breakfast served on a wooden tray over white hotel sheets, soft window light, 50mm lens, steam rising from coffee, indulgent slow-morning luxury.' },
  { code: '/turi-piscinaatardecer', name: 'Pileta al atardecer', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Sunset pool photography: infinity pool glowing at golden hour with palm silhouettes, 24mm wide-angle, warm reflections dancing on the water, loungers waiting, pure resort bliss.' },
  { code: '/turi-destinoemblematico', name: 'Destino emblemático', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Iconic landmark photography: famous monument framed dramatically at blue hour, 24mm lens, perfect symmetry, small travelers in the foreground for scale, glowing city lights, bucket-list wanderlust.' },
  { code: '/turi-lobbyhotel', name: 'Lobby del hotel', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Hotel lobby photography: grand reception with designer furniture and a statement chandelier, warm welcoming light, 16mm wide-angle, marble floors gleaming, fresh flowers, prestigious arrival experience.' },
  { code: '/turi-spa', name: 'Spa y masajes', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Hotel spa photography: serene treatment room with a massage table, flickering candles and orchids, soft dim lighting, 35mm lens, rolled towels and oils, tranquil wellness escape.' },
  { code: '/turi-restaurantehotel', name: 'Restaurante del hotel', brandSafe: true,
    rubros: ['turismo', 'gastronomia'],
    prompt: 'Hotel restaurant photography: candlelit tables set for dinner with city lights beyond glass walls, warm ambient glow, 35mm lens, wine glasses gleaming, refined evening dining.' },
  { code: '/turi-banohotel', name: 'Baño con vista', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Hotel bathroom photography: deep soaking tub positioned before a panoramic window, soft warm daylight, 35mm lens, marble surfaces and orchid styling, bubbles waiting, soak-with-a-view indulgence.' },
  { code: '/turi-playa', name: 'Playa paradisíaca', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Tropical beach photography: powder-white sand with turquoise waves and palm shade, bright midday sun, 24mm wide-angle, gentle waves, footprints in the sand, saturated paradise colors.' },
  { code: '/turi-montana', name: 'Cabaña en la montaña', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Mountain cabin photography: cozy wooden lodge with snow peaks behind, warm windows glowing at dusk, 35mm lens, smoke curling from the chimney, crisp alpine air feeling.' },
  { code: '/turi-maleta', name: 'Valija lista', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Travel lifestyle photography: open suitcase on a hotel bed with folded clothes and a camera, soft window light, 50mm lens, passport on top, the-trip-just-started excitement.' },
  { code: '/turi-ventanaavion', name: 'Vista desde el avión', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Airplane window photography: wing over cotton clouds at sunset, warm golden light flooding the cabin frame, 50mm lens, tiny window view, wanderlust in a single frame.' },
  { code: '/turi-mapa', name: 'Mapa con ruta', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Itinerary flat-lay photography: vintage map with a marked route in red, brass compass, tickets, pins and a polaroid, top-down composition, warm daylight, 50mm lens, adventure-planning inspiration.' },
  { code: '/turi-pasaporte', name: 'Pasaporte y pasajes', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Travel documents flat-lay photography: open passport, boarding passes and sunglasses arranged artfully on linen, top-down, bright daylight, 50mm lens, camera and headphones beside them, ready-to-fly anticipation.' },
  { code: '/turi-crucero', name: 'Crucero', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Cruise ship photography: majestic white liner on the open ocean at golden hour, 70mm lens, foamy wake trailing behind, deck lights twinkling, grand voyage romance.' },
  { code: '/turi-glamping', name: 'Glamping', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Glamping photography: luxury canvas tent glowing under a starry night sky, warm interior light spilling out, 24mm wide-angle, long exposure stars, campfire nearby, wild comfort.' },
  { code: '/turi-bodega', name: 'Tour de bodega', brandSafe: true,
    rubros: ['turismo', 'gastronomia'],
    prompt: 'Winery tour photography: oak barrel cellar with tasting glasses catching warm glowing light, 35mm lens, rich amber tones, sommelier pouring red wine, enotourism sensory experience.' },
  { code: '/turi-gastronomialocal', name: 'Sabores del destino', brandSafe: true,
    rubros: ['turismo', 'gastronomia'],
    prompt: 'Local cuisine photography: traditional regional dishes styled on rustic wood, warm side light, 50mm lens, steam rising, vibrant colors, hands reaching in sharing, taste-the-destination invitation.' },
  { code: '/turi-mercado', name: 'Mercado local', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Local market photography: vibrant stalls of tropical fruit and handmade crafts, midday sun filtering through awnings, 35mm lens, saturated colors, vendors smiling, authentic cultural immersion.' },
  { code: '/turi-museo', name: 'Museo imperdible', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Museum photography: grand gallery hall with dramatic skylight beams cutting through darkness, 16mm wide-angle, tiny visitors dwarfed by monumental art, marble floors, hushed cultural grandeur.' },
  { code: '/turi-callehistorica', name: 'Calle histórica', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Historic street photography: empty cobblestone lane with colonial facades glowing in golden light, 35mm lens, long soft shadows, flowered balconies overhead, timeless preserved old-town charm.' },
  { code: '/turi-mirador', name: 'Mirador panorámico', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Viewpoint photography: lone traveler with arms open before a sweeping green valley vista, 24mm wide-angle, dramatic clouds above, wind in hair, pure freedom-and-awe moment captured.' },
  { code: '/turi-cascada', name: 'Cascada natural', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Waterfall photography: powerful thundering cascade with mist catching the sunlight, 24mm wide-angle, silky water motion, lush green frame, rainbow in spray, raw roaring nature power.' },
  { code: '/turi-aventura', name: 'Turismo aventura', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Adventure tourism photography: kayakers paddling through turquoise water in a red-rock canyon at midday, 70mm lens, splashing action frozen, helmets gleaming, adrenaline and wild landscapes.' },
  { code: '/turi-buceo', name: 'Buceo', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Scuba diving photography: diver gliding over a vibrant coral reef with sun rays piercing blue water, 16mm underwater wide-angle, bubbles rising, turtles nearby, weightless marine wonder.' },
  { code: '/turi-esqui', name: 'Esquí', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Ski photography: skier carving fresh powder with snow spraying, bright alpine sun on a bluebird day, 70mm lens, frozen dynamic action, mountain panorama, pure winter thrill.' },
  { code: '/turi-termas', name: 'Termas', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Hot springs photography: steaming turquoise thermal pools with snowy mountains behind at dawn, soft misty light, 35mm lens, bathers relaxing, serene natural wellness, towels waiting.' },
  { code: '/turi-fogata', name: 'Fogata en la playa', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Beach bonfire photography: friends around a crackling fire under the stars, warm firelight on their faces, 35mm lens, guitars out, night-sky backdrop, unforgettable summer night.' },
  { code: '/turi-lunademiel', name: 'Luna de miel', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Honeymoon photography: newlywed couple embracing on a secluded beach at sunset, 85mm lens, shallow depth, soft golden backlight, footprints in the sand, romantic once-in-a-lifetime glow.' },
  { code: '/turi-familia', name: 'Vacaciones en familia', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Family vacation photography: happy family splashing together in a turquoise resort pool, bright sunny day, 35mm lens, candid laughter, colorful inflatable toys everywhere, memory-making joy.' },
  { code: '/turi-amigos', name: 'Viaje con amigos', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Friends road-trip photography: group of friends laughing beside a vintage van on a scenic coastal route, golden-hour light, 35mm lens, surfboards on top, carefree adventure friendship.' },
  { code: '/turi-solo', name: 'Viajar solo', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Solo travel photography: lone backpacker with a big pack gazing at a vast mountain landscape, 35mm lens, contemplative scale, journal in hand, empowering independent journey.' },
  { code: '/turi-barhotel', name: 'Bar del hotel', brandSafe: true,
    rubros: ['turismo', 'bar'],
    prompt: 'Hotel bar photography: crafted cocktail on a marble counter with a backlit bottle wall, moody evening light, 50mm lens, skilled hands at work, sophisticated nightcap mood.' },
  { code: '/turi-gymhotel', name: 'Gym del hotel', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Hotel gym photography: sleek modern gleaming fitness room with treadmills facing panoramic windows, bright morning light, 24mm wide-angle, runner in stride, dumbbells racked, keep-your-routine appeal.' },
  { code: '/turi-piscinaclimatizada', name: 'Pileta climatizada', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Indoor heated pool photography: steamy spa pool with underwater lights in a stone grotto, soft diffused glow, 24mm wide-angle, lone swimmer gliding peacefully, winter-wellness refuge.' },
  { code: '/turi-cenaromantica', name: 'Cena romántica', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Romantic dinner photography: table for two with candles and rose petals on a terrace, city lights bokeh behind, 50mm lens, wine poured, intimate celebration night.' },
  { code: '/turi-traslado', name: 'Traslado privado', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Private transfer photography: premium black van with the driver opening the door at an airport curb, bright daylight, 35mm lens, luggage ready, seamless arrival service.' },
  { code: '/turi-guia', name: 'Guía turístico', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Tour guide photography: smiling guide with a small flag leading travelers through the old town, warm morning light, 35mm lens, curious faces following, expert-led discovery.' },
  { code: '/turi-cabalgata', name: 'Cabalgata', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'Horseback ride photography: riders crossing a golden wheat field slowly at sunset, 70mm lens, dust glowing in the backlight, gaucho hats on, rustic countryside adventure.' },
  { code: '/turi-allinclusive', name: 'Todo incluido', brandSafe: true,
    rubros: ['turismo'],
    prompt: 'All-inclusive photography: close-up of a resort wristband beside a frosty tropical cocktail, bright blue pool-day light, 50mm lens, shallow depth, palm trees blurred, everything-taken-care-of ease.' },
];
