module.exports = [
  { code: '/viaje-playacaribe', name: 'Playa caribeña', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Caribbean beach paradise: turquoise water lapping white sand, palm trees leaning in sea breeze, bright midday sun with vivid colors, 24mm wide postcard framing, pure tropical bliss, saturated azure and gold, dream vacation calling." },
  { code: '/viaje-europacalle', name: 'Calle europea', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Charming European old-town street: cobblestones and colorful facades in soft morning light, cafe tables spilling onto the sidewalk, 35mm wanderlust framing, timeless romantic atmosphere, warm golden tones, storybook travel magic." },
  { code: '/viaje-crucero', name: 'Crucero', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Luxury cruise ship at sea: grand vessel cutting through deep blue water under a bright sky, 24mm majestic wide framing, sparkling sun reflections, exciting voyage energy, vivid maritime blues, unforgettable ocean adventure." },
  { code: '/viaje-montana', name: 'Montaña con nieve', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Snow-capped mountain peak at sunrise: alpenglow painting the summit pink and gold, pine forest in soft shadow below, 70-200mm compressed telephoto view, crisp alpine air, majestic serene wilderness, breathtaking high-altitude beauty." },
  { code: '/viaje-machupicchu', name: 'Machu Picchu', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Machu Picchu at dawn: ancient stone terraces emerging from morning mist, soft golden light on the peaks, 24mm epic wide framing, mystical timeless wonder, lush greens and warm stone, bucket-list archaeological marvel." },
  { code: '/viaje-safari', name: 'Safari africano', brandSafe: true,
    rubros: ['viajes'],
    prompt: "African safari at golden hour: elephants crossing the savanna with acacia trees silhouetted, warm dusty backlight, 200mm telephoto wildlife framing, raw untamed beauty, rich amber tones, once-in-a-lifetime wild encounter." },
  { code: '/viaje-auroras', name: 'Auroras boreales', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Northern lights over a snowy fjord: green aurora ribbons dancing across a starry sky, moonlit snow reflections, 14mm ultra-wide night framing, long exposure magic, ethereal electric greens, otherworldly Arctic wonder." },
  { code: '/viaje-desierto', name: 'Dunas del desierto', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Desert dunes at sunset: rippled sand glowing orange and red, a lone camel caravan on the ridge, 35mm sweeping framing, warm dramatic light, endless golden wilderness, exotic serene adventure, timeless Saharan beauty." },
  { code: '/viaje-venecia', name: 'Venecia en góndola', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Venice canal with gondola: striped-shirt gondolier gliding past pastel palazzos, soft morning light on the water, 50mm romantic framing, gentle ripples and reflections, dreamy Italian elegance, timeless floating-city charm." },
  { code: '/viaje-santorini', name: 'Santorini', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Santorini at blue hour: whitewashed houses and blue domes above the Aegean, warm lights flickering on, 24mm iconic wide view, soft twilight glow, romantic Mediterranean perfection, crisp whites against deep blue." },
  { code: '/viaje-paris', name: 'París', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Paris with the Eiffel Tower at dusk: tower sparkling against a lavender sky, Seine reflections below, 35mm classic framing, lovers strolling the bridge, romantic golden-hour glow, timeless City of Light magic." },
  { code: '/viaje-iguazu', name: 'Cataratas del Iguazú', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Iguazu Falls in full force: massive curtains of water thundering down, rainbow in the rising mist, bright daylight with dramatic spray, 24mm powerful wide framing, raw natural power, vibrant greens and whites, awe-inspiring wonder." },
  { code: '/viaje-maldivas', name: 'Maldivas', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Maldives overwater bungalow: wooden villa above crystal-clear lagoon, bright tropical sun, 24mm idyllic framing, gentle waves and swaying palms, ultimate honeymoon escape, vivid turquoise and white, pure barefoot luxury." },
  { code: '/viaje-roadtrip', name: 'Road trip', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Open-road adventure: vintage car on a desert highway stretching to the horizon, dramatic clouds at golden hour, 35mm cinematic framing, windshield reflecting the sun, freedom and wanderlust, warm nostalgic tones, epic journey ahead." },
  { code: '/viaje-glamping', name: 'Glamping', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Luxury glamping tent under the stars: canvas tent glowing warmly in a mountain meadow, Milky Way above, 24mm night framing, cozy fire pit light, wild comfort, deep blues with golden warmth, magical outdoor escape." },
  { code: '/viaje-tren', name: 'Tren panorámico', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Panoramic train through the Alps: glass-roofed carriage winding past snowy peaks, bright daylight on pristine snow, 35mm scenic framing, cozy traveler silhouettes inside, breathtaking alpine journey, crisp vivid mountain beauty." },
  { code: '/viaje-esqui', name: 'Esquí', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Ski resort in fresh powder: skier carving down a pristine slope, snow spraying in bright sunlight, 70-200mm action telephoto, crisp blue sky, exhilarating winter energy, sparkling whites and blues, perfect alpine day." },
  { code: '/viaje-buceo', name: 'Buceo en arrecife', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Scuba diving over a coral reef: diver floating above vibrant corals and schooling fish, sunbeams piercing turquoise water, 16mm underwater wide framing, weightless aquatic wonder, brilliant marine colors, unforgettable ocean exploration." },
  { code: '/viaje-kioto', name: 'Templos de Kioto', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Kyoto temple in autumn: vermilion pagoda framed by fiery maple leaves, soft morning mist, 35mm serene framing, tranquil spiritual beauty, rich reds and golds, timeless Japanese harmony, peaceful cultural journey." },
  { code: '/viaje-nuevayork', name: 'Nueva York', brandSafe: true,
    rubros: ['viajes'],
    prompt: "New York City skyline at dusk: Manhattan towers glowing against a pink-orange sky, 24mm dramatic wide view, city lights flickering on, electric urban energy, vibrant metropolitan colors, the city that never sleeps." },
  { code: '/viaje-atardecerbarco', name: 'Atardecer en barco', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Sunset sailboat cruise: sailboat gliding on golden water, sun melting into the horizon, 50mm romantic framing, warm glowing reflections, gentle sea breeze, dreamy honeymoon mood, rich amber and rose tones." },
  { code: '/viaje-islandia', name: 'Laguna glaciar', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Iceland glacial lagoon: floating blue icebergs on mirror-still water, soft Arctic twilight, 24mm surreal wide framing, otherworldly icy blues, pristine silent wonder, dramatic Nordic landscape, unforgettable frozen beauty." },
  { code: '/viaje-petra', name: 'Petra', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Petra Treasury at sunrise: rose-red facade glowing in a shaft of morning light, narrow canyon framing the view, 35mm dramatic composition, ancient mystery, warm sandstone tones, legendary archaeological wonder, timeless desert marvel." },
  { code: '/viaje-capadocia', name: 'Globos en Capadocia', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Hot air balloons over Cappadocia: dozens of colorful balloons rising above fairy chimneys at dawn, soft pastel sky, 24mm magical wide framing, dreamlike floating serenity, gentle pinks and golds, bucket-list sunrise flight." },
  { code: '/viaje-patagonia', name: 'Patagonia', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Patagonian peaks at golden hour: jagged granite towers above a turquoise lake, dramatic clouds, 24mm epic wide framing, wild untamed grandeur, crisp vivid colors, raw southern wilderness, ultimate adventurer frontier." },
  { code: '/viaje-bali', name: 'Arrozales de Bali', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Bali rice terraces at sunrise: emerald paddies cascading down the valley, morning mist and golden light, 35mm lush framing, tranquil tropical harmony, vibrant greens with warm glow, serene island spirituality, paradise found." },
  { code: '/viaje-egipto', name: 'Pirámides de Egipto', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Egyptian pyramids at golden hour: Great Pyramid rising from desert sands, camel in foreground, warm dramatic light, 24mm monumental framing, ancient eternal mystery, rich golds and deep shadows, legendary wonder of the world." },
  { code: '/viaje-catamaran', name: 'Catamarán caribeño', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Caribbean catamaran day trip: white sails billowing over turquoise sea, happy travelers on deck, bright midday sun, 35mm joyful framing, sparkling water and sea breeze, carefree island hopping, vivid tropical fun." },
  { code: '/viaje-toscana', name: 'Viñedos de Toscana', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Tuscan vineyard at harvest: rolling hills of grapevines in warm afternoon light, cypress trees lining the road, 50mm idyllic framing, rustic Italian romance, golden greens and ambers, wine-country bliss, timeless countryside charm." },
  { code: '/viaje-marruecos', name: 'Zocos de Marruecos', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Marrakech souk at dusk: vibrant market stalls with lanterns glowing, spices in colorful mounds, warm ambient light, 35mm exotic framing, bustling sensory richness, rich oranges and reds, magical Arabian-nights atmosphere." },
  { code: '/viaje-fiordos', name: 'Fiordos noruegos', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Norwegian fjord in soft light: steep cliffs plunging into mirror-calm water, waterfall ribbons, moody overcast glow, 24mm dramatic wide framing, serene Nordic majesty, deep greens and grays, pristine Scandinavian wilderness." },
  { code: '/viaje-grancanon', name: 'Gran Cañón', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Grand Canyon at sunrise: layered red rock glowing in first light, vast depth stretching out, 24mm epic wide framing, ancient geological wonder, fiery oranges and purples, humbling natural grandeur, unforgettable American icon." },
  { code: '/viaje-surfplaya', name: 'Surf en la playa', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Surf break at dawn: perfect wave curling under golden light, surfer dropping in, 200mm telephoto action framing, ocean spray glowing, pure adrenaline joy, vibrant aqua and gold, endless summer stoke." },
  { code: '/viaje-lagocanoa', name: 'Lago en canoa', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Canoe on a glassy mountain lake: red canoe gliding over perfect reflections, mist rising at dawn, 35mm tranquil framing, silent wilderness peace, soft pastel morning tones, serene paddling escape, untouched natural calm." },
  { code: '/viaje-estrellas', name: 'Noche estrellada', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Starry desert night: Milky Way blazing over towering dunes, tiny tent glowing below, 14mm ultra-wide long exposure, profound cosmic silence, deep indigo with warm lantern light, humbling celestial wonder, unforgettable night sky." },
  { code: '/viaje-ruta66', name: 'Ruta 66', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Route 66 roadside Americana: vintage neon motel sign glowing at dusk, classic car parked below, 35mm nostalgic framing, warm retro neon glow, timeless road-trip romance, saturated vintage colors, legendary highway adventure." },
  { code: '/viaje-castillo', name: 'Castillo escocés', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Scottish castle in morning mist: ancient stone fortress above a glassy loch, soft diffused light, 24mm moody wide framing, haunting historic romance, muted greens and grays, legendary highland mystery, timeless fairytale." },
  { code: '/viaje-roma', name: 'Coliseo de Roma', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Rome Colosseum at golden hour: ancient amphitheater glowing warm against a dramatic sky, 24mm monumental framing, cobblestone foreground, eternal city grandeur, rich ambers and deep blues, two thousand years of history alive." },
  { code: '/viaje-laguna', name: 'Laguna turquesa', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Hidden turquoise lagoon: crystal water ringed by jungle cliffs, sunbeams dancing on the surface, 24mm secret-paradise framing, untouched tropical purity, vivid aqua and emerald, secluded swimming dream, natural private pool." },
  { code: '/viaje-mercadolocal', name: 'Mercado local', brandSafe: true,
    rubros: ['viajes'],
    prompt: "Local street-food market: sizzling stalls and colorful produce under string lights, steam rising in warm evening glow, 35mm vibrant documentary framing, authentic local flavors, rich appetizing colors, delicious cultural immersion." },
];
